### ISSUE TITLE
normalize-by-median skip consuming kmers of PE reads

### ISSUE THREAD

**Issue by drtamermansour** [dib-lab/khmer#1000]
The normalize-by-median script in the PE mode keeps both paired ends if only one of them is below the coverage cutoff. However then script only consume the kmers from one end. This is why if we run abound-dist.py on the output k-mer counting table, 1st line will show some no of kmers with 0 frequency.

**Comment by drtamermansour** [comment]
Another important point, current implantation replace 'N's with 'A's then use this modified sequence to consume kmers. I think load-into-counting.py consume 'N's creating of course much more unique kmers. This might answer the question raised here http://lists.idyll.org/pipermail/khmer/2015-May/000691.html .

**Comment by drtamermansour** [comment]
Both issues raised here of course would impact the behavior of downstream filter-abund.py script

**Comment by bocajnotnef** [comment]
#1010 resolves the bug in normalize-by-median.
