### ISSUE TITLE
[Discussion] The fate of load-graph

### ISSUE THREAD

**Issue by bocajnotnef** [dib-lab/khmer#1005]
In the spirit of https://github.com/dib-lab/khmer/commit/93c47ecaff45d3240f77f01497bf934b6393b14e and since https://github.com/dib-lab/khmer/pull/961 is nearly mergable and since I'm about to shift focus from oxli to UX stuff and I don't want build-graph to be left behind while additional changes are made, would it be possible to delete load-graph entirely and redirect everything that used it to build-graph? As it stands I've taken every test in the unit test suite that uses load-graph (even indirectly) and made versions that use build-graph, so in theory it's trustworthy. 

@mr-c @ctb @luizirber @camillescott thoughts?

**Comment by mr-c** [comment]
This could be part of the upcoming API breakage release.

**Comment by bocajnotnef** [comment]
@ctb Thoughts on this, since said release is supposedly in the works?

**Comment by ctb** [comment]
As per #961, load-graph was replaced by the contents of build-graph; there is no build-graph script. If you're proposing to now go back in and rename load-graph to build-graph, please make a case for it in a new issue :).
