### ISSUE TITLE
Refactor normalize-by-median with extreme prejudice

### ISSUE THREAD

**Issue by ctb** [dib-lab/khmer#1006]
There is mounting dissatisfaction amongst the natives with the agglomerative mess that normalize-by-median has become.

In casual conversation, @camillescott has pointed out that much of the mess comes from fail-safe attempts, and that context managers (see e.g. http://eigenhombre.com/2013/04/20/introduction-to-context-managers/) could potentially simplify this. 

I think this could also be part of addressing #988.

I'd like to see this done in stages by refactoring, with code review at each stage. @bocajnotnef you up for it? cc @drtamermansour

**Comment by bocajnotnef** [comment]
Sounds fun. Normalize-by-median was on my list of things to oxlize
(oxlify?).

I would like to see https://github.com/dib-lab/khmer/pull/961 merged first,
as it contains some API stuff that could be useful.

**Comment by ctb** [comment]
On Sat, May 16, 2015 at 07:41:31AM -0700, Jake Fenton wrote:
> Sounds fun. Normalize-by-median was on my list of things to oxlize
> (oxlify?).
> 
> I would like to see https://github.com/dib-lab/khmer/pull/961 merged first,
> as it contains some API stuff that could be useful.

"Refactoring" here means taking the existing code and modifying progressively,
rather than going for a clean rewrite.  The latter is more likely to lead to
unexpected and mass breakage, especially in the absence of comprehensive
tests.  I need to talk with @mr-c about #961, too; the prototype code
in khmer_api is not necessarily ready for the khmer repo, and I am not
sure we want to start putting oxli code into the codebase just yet, especially
given http://ivory.idyll.org/blog/2015-modifying-our-dev-process.html.

So -1 on predicating this on #961, +0 on moving towards code that looks
as simple as the khmer_api code.  Will revisit after talking with @mr-c.

**Comment by drtamermansour** [comment]
+1 for working on code simplification while addressing #988
<https://github.com/dib-lab/khmer/issues/988>.

**Comment by bocajnotnef** [comment]
So, specific pain points:

 - [ ] Lots of error checking/failsafing that could and should be done with context managers
 - [ ] Should accept and deal with broken-pairs
 - [ ] Better default arguments for enhanced understanding / less intimidating CLI appearance (in the vein of UX)

What'll the stages be?

**Comment by bocajnotnef** [comment]
as per discussion with Dr Tamer:

Stage 0:
- [ ] a) proper dealing with broken-paired input
- [ ]  b) -p require correct pairing and complain if not 
- [ ] c)  Add --force-single to to force into singleton mode
- [ ] d) Add --singletons to allow a singleton file (or files) to be passed in simultaneously with -p 

Stage 1 (subject to further discussion):
- [ ] Refactor normalize-by-median to change error checking/fail safing to be done with context managers

**Comment by ctb** [comment]
On Sun, May 17, 2015 at 01:02:24PM -0700, Jake Fenton wrote:
> as per discussion with Dr Tamer:
> 
> Stage 0:
> - [ ] a) proper dealing with broken-paired input
> - [ ]  b) -p require correct pairing and complain if not 
> - [ ] c)  Add --force-single to to force into singleton mode
> - [ ] d) Add --singletons to allow a singleton file (or files) to be passed in simultaneously with -p 
> 
> Stage 1 (subject to further discussion):
> - [ ] Refactor normalize-by-median to change error checking/fail safing to be done with context managers

Seems like a good plan.  My suggestion was going to be to invert that -
invest in a context manager up front, to clean up the code, and then
add the other functionality, but this approach will also work.

**Comment by bocajnotnef** [comment]
I was thinking similarly.

Re: context managers: I take this to mean I'm going to hunt through and find the big messy blocks of try/except/else like https://github.com/dib-lab/khmer/blob/master/scripts/normalize-by-median.py#L149 and replace all that with a context manager--Yes? No? Right track?

**Comment by camillescott** [comment]
@ctb @bocajnotnef that's right -- generally, context managers are used when you have some boilerplate that needs to be run on entry and/or exist. What you linked is more or less an example of that; see also https://github.com/dib-lab/khmer/blob/master/scripts/normalize-by-median.py#L312, where we've got this boilerplate for dumping the hashtable and exiting which would be generally useful, and calls for something to be done when failures happen. Image something looking like:

```
with FailSafe(file_list, counting_table, save_frequency=5) as fs:
    for fn in fs:
        normalize_by_median(fs, ...)
```

Where `FailSafe` has the logic for dumping the counting table to disk into its `__exit__` method, or into an `__iter__` method defined on it.

I haven't really thought out all the minutiae, but that's the direction I'm leaning.

**Comment by bocajnotnef** [comment]
so, for stage 2: Shall I push to develop the skeleton @camillescott provided in the last round (https://github.com/dib-lab/khmer/pull/1057#issuecomment-109082444)? That would seem to be the logical next step IMO.

CC @ctb

**Comment by ctb** [comment]
On Tue, Jun 09, 2015 at 12:56:20PM -0700, Jake Fenton wrote:
> so, for stage 2: Shall I push to develop the skeleton @camillescott provided in the last round (https://github.com/dib-lab/khmer/pull/1057#issuecomment-109082444)? That would seem to be the logical next step IMO.
> 
> CC @ctb 

No, leave it for now, IMO. I've reached normalize-by-median exhaustion,
and honestly @camillescott needs to get the threading stuff in before
we do much more (see #655 and #656)

**Comment by ctb** [comment]
Done in #1057 and #1010.
