### ISSUE TITLE
Dropping Python 2.6 (and before) support?

### ISSUE THREAD

**Issue by ctb** [dib-lab/khmer#1009]
Shall we formally drop Python 2.6 support with khmer 2.0?

http://astrofrog.github.io/blog/2015/05/09/2015-survey-results/

**Comment by luizirber** [comment]
Related issues and discussion:

#904 
https://github.com/dib-lab/khmer/issues/625#issuecomment-57820771
#94

**Comment by ctb** [comment]
Also, @luizirber, you've been adding Python 3 support in stealth-mode, right? Is that PR ready to merge? Does it break 2.6?

**Comment by luizirber** [comment]
Shh! It's stealth-mode! =] #978

It is ready-ish to merge, we decided to hold it for merging after 1.4. There are some merge conflicts now, but they should be easy to fix (the bigger issues involved unicode and are solved).

I need to check 2.6 status, but I'm pretty sure it is broken on the PR.

**Comment by ctb** [comment]
1.4 was released. Schedule for 2.0, next release?

**Comment by luizirber** [comment]
I updated the milestone for #978 to 2.0.

**Comment by ctb** [comment]
Note, deadline for 2.0 ~end of July, so if you can get this merged in by ~end of June that will give us plenty of time to figure out what it breaks.  Will confirm with @mr-c today.

**Comment by mr-c** [comment]
I'll need to drop some platforms from BaTLab testing; I think just RHEL6

**Comment by ctb** [comment]
Is this officially done @luizirber @mr-c? Is 2.6 support gone with 2.0?

**Comment by mr-c** [comment]
We still claim Python 2.6 compatibility in the docs; however I don't think that is true anymore.

**Comment by ctb** [comment]
Updated doc/user/install.rst in #1180.

**Comment by mr-c** [comment]
Fixed in #1180

**Comment by soundar-git** [comment]
Python 2.6.6 is default on RHEL 6.7 server.  Do we have any enterprise support with this version to build? Please share the details.

**Comment by ctb** [comment]
Hi, @soundar-git, we don't have the resources to maintain compatibility across old versions of Python and GCC, I'm afraid. However, you can go with khmer 1.4.1 for most of the core functionality - see https://github.com/dib-lab/khmer/releases/tag/v1.4.1.
