### ISSUE TITLE
abnormal kmer counting if consuming a read with non ACGT characters

### ISSUE THREAD

**Issue by drtamermansour** [dib-lab/khmer#1014]
If we feed the consume_string function with read containing non-ACGT characters, the function does not check for them and start adding the kmers to the counting table. The bigger issue here is that the function does not add these kmers uniformly. I have 2 representative examples. In both examples I started the analysis with those 2 identical reads:
>read1
GGTTGACGGGGCTCAGGGGGCGGCTGACTCCGAGAGACAGCAGCCGCAGCTGTCGTCAGGGGATTTCCGGGGCGGAGGCCGCAGACGCGAGTGGTGGAGGGAGAAGGCCTGA
>read2
GGTTGACGGGGCTCAGGGGGCGGCTGACTCCGAGAGACAGCAGCCGCAGCTGTCGTCAGGGGATTTCCGGGGCGGAGGCCGCAGACGCGAGTGGTGGAGGGAGAAGGCCTGA
 
The read length is 112 bp as expected you would get 96 unique kmer out of these reads.

The 1st example:
If you mutated any of the 1st 3 bases to other ACGT characters, you will get the expected increase of unique kmer count. However if you change any of these to non-ACGT character, the unique kmer count will not increase. Only after the 3rd base, the function would start recognize the new unique kmers.

The 2nd more wired example:
I added a 'G' to the end of the reads so that the total length of each read is 113, as expected you get one more unique. When I mutate the last base of the 1st read in each pair, I get a different increment of unique kmers!!.  
   
I have a file documenting the mutations and the corresponding unique kmer counts if anybody interested to replicate this.

I think we should abandon the consume_string function completely. In #1001, I used check_and_process_read instead. The later function check for non-ACGT characters before start counting kmers.

Also I wish anyone can understand why this is happening to make sure that we do not have similar situation with ACGT characters (I do not do C++ so reading the implementation of these functions to figure out what is going on is a nightmare for me)

**Comment by ctb** [comment]
thanks - the behavior of consume_string is undefined in the case of Ns;
currently I believe that it treats Ns as if they are Gs, based on
kmer_hash.hh line 40.

**Comment by drtamermansour** [comment]
This explains everything. All the mutated sites where the unique kmers did not count up were 'G's. Thank you. This makes me feels much better.

**Comment by ctb** [comment]
On Mon, May 18, 2015 at 01:35:15PM -0700, Tamer Mansour wrote:
> This explains everything. All the mutated sites where the unique kmers did not count up were 'G's. Thank you. This makes me feels much better.

Explanation: checking to see if the string is valid DNA is expensive,
computationally.  So consume_string should be used only when we're sure
it's valid, due to preprocessing elsewhere.

**Comment by ctb** [comment]
Inspired #1036; discuss there.
