### ISSUE TITLE
not all CPython functions convert all possible C++ khmer exceptions to Python exceptions

### ISSUE THREAD

**Issue by mr-c** [dib-lab/khmer#1016]
`InvalidStreamBuffer` is only thrown in trace_logger.cc (but never caught). `InvalidValue` and `ReadOnlyAttribute` is thrown from the HLL.  `InvalidStreamHandle` is thrown in read_parsers.cc as is `StreamReadError`, `InvalidRead`, `InvalidReadPair`, `NoMoreReadsAvailable`, `UnknownPairReadingMode`

**Comment by mr-c** [comment]
From @kdmurray91 "[...]  the C++ ReadParser, which throws StreamReadError if it gets an empty file. [...] This whole issue was discovered after hashing the output of a QC pipeline, running over GBS reads. GBS has a funky homebrew protocol and several samples dropped out (0 reads). l-i-c.py errored out, but left an empty counting hash file, which crashed some downstream code."

**Comment by mr-c** [comment]
"What's your opinion on the diversity of exceptions? Should we just raise one for EOF and one for all errors, specialising by actually setting the message when we throw them? Or just catch them all." @kdmurray91

**Comment by kdmurray91** [comment]
To reproduce:

```
touch empty.fastq
gzip empty.fastq
load-into-counting.py -x 1e7 -N 1 test.kh empty.fastq.gz
```
`./test.kh` should exist and be empty

**Comment by kdmurray91** [comment]
See also #1015

**Comment by kdmurray91** [comment]
A list of places which should probably be catching more exceptions:

`khmer/_khmermodule.cc`:

- `hash_consume_fasta`
- `hash_consume_fasta_with_reads_parser`

**Comment by kdmurray91** [comment]
Also see working ongoing in [this branch](https://github.com/dib-lab/khmer/tree/gotta-catch-them-all)

**Comment by kdmurray91** [comment]
More gitter copy-paste:

So, overall "plan":
- Ensure all exceptions raised in `read_parsers` inherit from `khmer_file_exception`
- Ensure any use of `throw` sets a unique and meaningful message, unless the subclass already has one
- catch just `khmer_file_exception` everywhere in `khmermodule.cc`
- Use `PyExc_IOError` to pass message to python land

**Comment by kdmurray91** [comment]
@mr-c, I have a question on C++ => python exception mapping.

Should we discern between errors of formatting, e.g. invalid fastq file, invalid pairs, invalid reads, etc, and errors in low-level I/O, e.g. empty/non-existent files. I'm +0 on splitting, as it seems conceptually nicer.

So, the C++ => Python mapping would be:
 - `NoMoreReadsAvailable`: `return NULL;`, i.e. `StopIteration`
 - `InvalidRead`,  `InvalidReadPair`, `UnknownPairReadingMode`: `ValueError`
 - ` khmer_file_exception`,  `InvalidStreamHandle`, `StreamReadError`: `OSError` (or should we stick with `IOError`, which is deprecated)

**Comment by mr-c** [comment]
We should use OSError, yes.

I don't personally see the value of a Python superclass for exceptions we throw but I am open to the perspectives of others.

**Comment by kdmurray91** [comment]
@mr-c that would be a C++ super-class, sorry

**Comment by mr-c** [comment]
Ah. Would that clean up the CPython glue or make life easier for direct consumers of libkhmer?

**Comment by kdmurray91** [comment]
Probably both, but the former was my motivation

**Comment by mr-c** [comment]
Sounds like a good enough reason for me, :+1:

**Comment by kdmurray91** [comment]
Sweet, shall do. I'll add it to `khmer_exception.hh`

**Comment by mr-c** [comment]
I think this is done, yes @kdmurray91 ?

**Comment by kdmurray91** [comment]
Ah, the original bug was fixed, but comprehensive tests never got made. But i think that is in another issue, so this is done. Closing

**Comment by mr-c** [comment]
Thanks!

On Thu, Jul 30, 2015 at 5:55 PM Kevin Murray <notifications@github.com>
wrote:

> Ah, the original bug was fixed, but comprehensive tests never got made.
> But i think that is in another issue, so this is done. Closing
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dib-lab/khmer/issues/1016#issuecomment-126532771>.
>
-- 
Michael R. Crusoe: Programmer & Bioinformatician crusoe@ucdavis.edu
The lab for Data Intensive Biology; University of California, Davis
https://impactstory.org/MichaelRCrusoe http://twitter.com/biocrusoe
