### ISSUE TITLE
interleave-reads.py SRA naming bug

### ISSUE THREAD

**Issue by macmanes** [dib-lab/khmer#1027]
root@ip-172-31-27-66:/mnt/reads# head -4 test1.fq
    @SRR797058.3 HWI-ST600:227:C0WR4ACXX:7:1101:17167:2000/1
    NCTACCAAAAAAATGCCCGATAATTCTGACCATTCCTTCCTCATTCTCGTCTGGCGTTTGGTCACGACGCACGATACCTTCTGCACTTGTCAAGACAGCGG
    +
    #00@#################################################################################################

and 

    root@ip-172-31-27-66:/mnt/reads# head -4 test2.fq
    @SRR797058.3 HWI-ST600:227:C0WR4ACXX:7:1101:17167:2000/2
    CTTGACAAGAGCAGAAGTTATCTTGCCTCGGGACCAAACGCCAGACGAGCACGAGGGAGCGATCGTCCGCATTAGCCGGCATTCTTTTGCTAGCAGATCGG
    +
    =?###################################################################################################

attempt at interleaving.

    root@ip-172-31-27-66:/mnt/reads# interleave-reads.py test1.fq test2.fq -o inter.fq
    
    || This is the script 'interleave-reads.py' in khmer.
    || You are running khmer version 1.4
    || You are also using screed version 0.8
    ||
    || If you use this script in a publication, please cite EACH of the following:
    ||
    ||   * MR Crusoe et al., 2014. http://dx.doi.org/10.6084/m9.figshare.979190
    ||
    || Please see http://khmer.readthedocs.org/en/latest/citations.html for details.
    
    Interleaving:
            test1.fq
            test2.fq
    ... 0 pairs
    ERROR: This doesn't look like paired data! SRR797058.3 HWI-ST600:227:C0WR4ACXX:7:1101:17167:2000/1/1 SRR797058.3 HWI-ST600:227:C0WR4ACXX:7:1101:17167:2000/2/2

Seems like an extra `/1` or `/2` is being appended.

**Comment by macmanes** [comment]
Apparently the space in the fastQ header is tripping things up, as a simple sed command removing the space makes the interleaving process work.

`sed -i 's_3 H_3-H_g' test{1,2}.fq`

**Comment by mr-c** [comment]
Drat. Thanks for the report

**Comment by ctb** [comment]
Not yet fixed - see comments in #1088.  The right-hand side needs to be checked properly.

**Comment by kdmurray91** [comment]
PR to fix is #1173

**Comment by mr-c** [comment]
Given that #1173 has been merged is this still an issue?

**Comment by ctb** [comment]
Testing against @standage examples, it's fixed by #1173.
