### ISSUE TITLE
rename LabelHash to something else

### ISSUE THREAD

**Issue by ctb** [dib-lab/khmer#1032]
now that it's no longer a hash-based object, we should name it something else before 2.0.

cc @camillescott - how about SparseLabels?

**Comment by camillescott** [comment]
How about just Labeller? Seeing as it's now more of a device for labelling, and it could be made more or less sparse.

**Comment by ctb** [comment]
@mr-c @luizirber any bikeshedding to offer? :)

**Comment by ctb** [comment]
What about LabelGraph? or LabeledGraph?

**Comment by mr-c** [comment]
GraphLabels

**Comment by mr-c** [comment]
@ctb What's the decision?

**Comment by ctb** [comment]
On Wed, Jul 29, 2015 at 04:37:26PM -0700, Michael R. Crusoe wrote:
> @ctb What's the decision?

GraphLabels.

**Comment by mr-c** [comment]
Done in #1209
