### ISSUE TITLE
write truncation tests for file load functions

### ISSUE THREAD

**Issue by ctb** [dib-lab/khmer#1037]
see test_labelhash.py, function test_save_load_corrupted(), added in #1021; this could usefully be applied to all of the file load functions.  Of course, then we'd need to fix the bugs, too...

Might be interesting to try postpending garbage into the files, too. Are the load functions robust to random crud?

**Comment by mr-c** [comment]
Sweet, fuzz'ing time

**Comment by ctb** [comment]
fixed by #1048.
