### ISSUE TITLE
Gzipped counting hash infinite loop w/ HT size 5e9?

### ISSUE THREAD

**Issue by kdmurray91** [dib-lab/khmer#1038]
Hi all,

This is basically a request to see if anyone can reproduce a weird bug.

If i use `load-into-counting.py -x 2e9 -k 20 -N 1 test.ct.gz my-10M-read.fastq.gz`, all is fine and dandy. But if I change that to `-x 5e9`, there seems to be an infinte loop in the writing of the hash table. `test.ct.gz.info` is produced, and contains `through file.fastq`. `test.ct.gz` is also produced, and contains a small amount of data in a valid gzip stream (say 1MB or thereabouts).

I haven't titrated the point at which this fails, but will if anyone can reproduce.

(side note: @mr-c, do you guys get notifications for new issues, or should I ping you with an @ like for PRs. I assume you do get notifications but thought I'd check.)

Cheers,
K

**Comment by kdmurray91** [comment]
Ahh, could [the use of `int` here](https://github.com/dib-lab/khmer/blob/master/lib/counting.cc#L849) be the issue? Does zlib even support writing chunks of >2**31-1?

**Comment by kdmurray91** [comment]
Ok, I think that could be the bug. `gzwrite` takes `unsigned int`, we give it `int`, and we ask it to write more than `2**31-1` bytes. I'll confirm that explicitly writing in chunks of less than `2**31` fixes the bug, and submit a PR if it does.

**Comment by kdmurray91** [comment]
Also, I wonder if this affects reading...

**Comment by ctb** [comment]
Good catch, @kdmurray91!

Regarding notifications, I wouldn't ping people explicitly unless you need their attention in short order; notifications are configurable on a per-project basis, so presumably people that have them turned off do so for a reason :).  In my case I see all of the new issues immediately.

**Comment by kdmurray91** [comment]
Can confirm that this was the bug, and that it affected reading AFAICT. PR incomming.

**Comment by kdmurray91** [comment]
`Lines's stability is 87.83 and set mininum stability is 87.84.` Soooo close!

**Comment by kdmurray91** [comment]
this was fixed in #1043, closing
