### ISSUE TITLE
Strange test failure in Jenkins OSX slave

### ISSUE THREAD

**Issue by kdmurray91** [dib-lab/khmer#1046]
@bocajnotnef  and I complained on gitter about the following failure on the OSX slave.

```
tests.test_read_parsers.test_read_pair_iterator_in_error_mode_xfail ... FAIL
======================================================================
FAIL: tests.test_read_parsers.test_read_pair_iterator_in_error_mode_xfail
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jenkins/workspace/khmer-pullrequest/label/osx/.env/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/jenkins/workspace/khmer-pullrequest/label/osx/tests/test_read_parsers.py", line 335, in test_read_pair_iterator_in_error_mode_xfail
    assert "Invalid read pair detected" in str(exc), str(exc)
AssertionError
```

Once the OSX slave is alive again, I'll try and work out why. This issue is to remind me :)

**Comment by ctb** [comment]
Note, this doesn't fail on OS X 10.9.5, Python 2.7.2.  But my laptop is a bit odd.  I do have access to some other more up-to-date OS X machines, will give it a try.

**Comment by kdmurray91** [comment]
Curiouser and curiouser...

Our lab mac box just got re-built so I will try on that. It's running yosemite, whatever version that is (not a mac man, myself).

**Comment by mr-c** [comment]
See #1190 for an explanation. Fixed via workaround
