### ISSUE TITLE
All scripts/ possible should support '-' input

### ISSUE THREAD

**Issue by ctb** [dib-lab/khmer#1055]
This is for better, more productive streaming.

Should '-' be default? Probably not.

Also, always allow '-' in output.

**Comment by ctb** [comment]
Check for, fix, write tests for, update docs for:

- [ ] normalize-by-median
- [ ] split-paired-reads
- [ ] load-into-counting
- [ ] filter-abund
- [ ] trim-low-abund
- [ ] load-graph
- [ ] normalize-by-median
- [ ] extract-long-sequences
- [ ] extract-paired-reads
- [ ] fastq-to-fasta
- [ ] sample-reads-randomly

Maybe not needed for streaming, since it's fundamentally a two pass algorithm:
- [ ] abundance-dist (?)
- [ ] count-median

Definitely not:
- [ ] abundance-dist-single
- [ ] filter-abund-single
- [ ] do-partition
- [ ] partition-graph
- [ ] merge-partition
- [ ] annotate-partitions
- [ ] extract-partitions
- [ ] make-initial-stoptags
- [ ] find-knots
- [ ] filter-stoptags
- [ ] interleave reads (should & does support streaming output)
- [ ] readstats.py (although perhaps a streaming mode?)

**Comment by standage** [comment]
I did this for `normalize-by-median.py` at PyCon. See #882. Verified on the command line and with `test_normalize_by_median_stdout` in `test_scripts.py`, and updated the docs, which is reflected in the usage statement and RTD.

**Comment by ctb** [comment]
Excellent, thanks @standage!

**Comment by ctb** [comment]
Uh, let me revise that - you did it for *output*, not *input*, @standage :)

**Comment by standage** [comment]
:100:

**Comment by ctb** [comment]
Fixing in #1186.
