### ISSUE TITLE
Fix pypi page

### ISSUE THREAD

**Issue by ctb** [dib-lab/khmer#1061]
https://pypi.python.org/pypi/khmer

- [x] ged-lab to dib-lab
- [x] ged.msu.edu to ivory.idyll.org/lab/

**Comment by bocajnotnef** [comment]
The page doesn't say anything about python3

(I don't know if we care, just thought I'd point it out)

**Comment by mr-c** [comment]
@bocajnotnef python3 will be listed when v2.0 is released: https://github.com/dib-lab/khmer/blob/master/setup.py#L155

**Comment by mr-c** [comment]
Fixed as of v2.0-rc8: https://testpypi.python.org/pypi/khmer/2.0-rc8
