### ISSUE TITLE
Build fail on Windows

### ISSUE THREAD

**Issue by SreeHarshaRamesh** [dib-lab/khmer#1068]
I'm getting the following error on trying to build using gnu make for windows:
```process_begin: CreateProcess(NULL, uname, ...) failed.
./setup.py develop
process_begin: CreateProcess(NULL, env python2 C:\Users\b2091\khmer\setup.py develop, ...) failed.
make (e=2): The system cannot find the file specified.
make: *** [test] Error 2.```

There seems to be an issue with make. Has somebody faced this issue before?

Also, for contributing to khmer, is it recommended to use Windows at all - because I don't see any support for Windows in [Getting Started](https://khmer.readthedocs.org/en/latest/dev/getting-started.html) ?

**Comment by ctb** [comment]
Hi, I'm afraid we don't support Windows at all!

best,
-titus

On Sat, Jun 06, 2015 at 11:27:35PM -0700, Sree Harsha Ramesh wrote:
> I'm getting the following error on trying to build using gnu make for windows:
> ```process_begin: CreateProcess(NULL, uname, ...) failed.
> ./setup.py develop
> process_begin: CreateProcess(NULL, env python2 C:\Users\b2091\khmer\setup.py develop, ...) failed.
> make (e=2): The system cannot find the file specified.
> make: *** [test] Error 2.```
> 
> There seems to be an issue with make. Has somebody faced this issue before?
> 
> Also, for contributing to khmer, is it recommended to use Windows at all - because I don't see any support for Windows in [Getting Started](https://khmer.readthedocs.org/en/latest/dev/getting-started.html) ?
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/dib-lab/khmer/issues/1068
-- 
C. Titus Brown, ctbrown@ucdavis.edu
