### ISSUE TITLE
Update whatsnew for changes to normalize-by-median.py

### ISSUE THREAD

**Issue by ctb** [dib-lab/khmer#1076]
ref #1057

**Comment by bocajnotnef** [comment]
see also #1006

**Comment by ctb** [comment]
While we're at it, fix --fault-tolerant in the docstring.

**Comment by bocajnotnef** [comment]
see also: https://github.com/dib-lab/khmer/pull/1031

**Comment by bocajnotnef** [comment]
(which is apparently where the `whatsnew` lives)

**Comment by mr-c** [comment]
@bocajnotnef #1031 has landed

**Comment by ctb** [comment]
Fixed in #1139.
