### ISSUE TITLE
screed 0.9 release

### ISSUE THREAD

**Issue by mr-c** [dib-lab/khmer#1082]
- [x] rc-2 passed checklist
- [x] rc-2 passed acceptance tests with khmer master branch
- [x] write release notes & merge them
- [x] cut the release
- [x] advertise it

**Comment by mr-c** [comment]
Release notes at https://github.com/dib-lab/screed/releases/edit/untagged-7e3cc0d8cf3381e6a4a9

Any feedback @ctb, @luizirber @camillescott ?

**Comment by mr-c** [comment]
- [ ] update docs with new lab info?

**Comment by luizirber** [comment]
Can I edit the draft? The title still says 0.8

**Comment by luizirber** [comment]
@mr-c already edited it. Fixed title and also "known issues". Otherwise LGTM!
