### ISSUE TITLE
make diff-cover runs huge tests which breaks on small memory machines

### ISSUE THREAD

**Issue by bocajnotnef** [dib-lab/khmer#1107]
```
tests.test_counting_hash.test_save_load_large ... terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Makefile:159: recipe for target '.coverage' failed
make: *** [.coverage] Aborted (core dumped)
(env)2 bocajnotnef@GCU-Caconym:~/git/khmer⟫ 
```

hotfix for master was to disable huge tests on `make test`--not sure if that's optimal in this case

**Comment by mr-c** [comment]
I was looking into this yesterday. There's some weird version detail that also matters. Running coverage on Athyra only takes a couple hundred megabytes of memory. Yet the CI server and others consume many gigabytes in the same situation..

**Comment by bocajnotnef** [comment]
see also #1109

**Comment by mr-c** [comment]
This is fixed
