### ISSUE TITLE
Some tests have grown too memory hungry

### ISSUE THREAD

**Issue by bocajnotnef** [dib-lab/khmer#1109]
re: gitter conversation starting nearish https://gitter.im/dib-lab/khmer?at=5584b7e73039387b1577f66a

some of the tests have gotten to the point where they take several gigs of ram and disk and ~20s to complete. Since they test edge cases it's excessive to have to run these constantly.

**Proposed/general consensus:** we should implement some new testing tags ("large" and "huge") and have the "huge" tests run as part of the release process and/or only on merges into master.

@mr-c @ctb @kdmurray91: Further thoughts?

**Comment by kdmurray91** [comment]
@bocajnotnef no further thoughts, but +1 for two sets. And I'd say +1 to two makefile targets.

Additionally, I'm happy to run vaguely regular build/test runs on our CI server here, which runs debian Jessie, and also can run things on a Fujitsu supercomputer (Centos 6.X based, with Intel's `cc` and GCC). I kinda already do this with a subset of the C++ API, or at least it's integration with [kWIP](https://github.com/kdmurray91/kWIP).

**Comment by kdmurray91** [comment]
Side note: the `coverage` call doesn't have `--attr=!huge` in the coverage targets of the makefile.

**Comment by luizirber** [comment]
An interesting exercise: http://threebean.org/blog/speeding-up-that-test-suite/

**Comment by mr-c** [comment]
This is fixed
