### ISSUE TITLE
Allow for skipping of pysam tests

### ISSUE THREAD

**Issue by ctb** [dib-lab/khmer#1120]
Also see https://github.com/dib-lab/khmer/pull/1019#discussion_r30709115

cc @bocajnotnef

**Comment by bocajnotnef** [comment]
Any way we could build a 

```
try:
    import
except:
    # skip test
```

kinda thing?

**Comment by ctb** [comment]
+1

**Comment by ctb** [comment]
Will be fixed by #750 (see #1121).

**Comment by mr-c** [comment]
Done
