### ISSUE TITLE
Change setup.cfg to have stop=FALSE

### ISSUE THREAD

**Issue by ctb** [dib-lab/khmer#1124]
Back When, when setup.cfg was put into place to provide default parameters, `-x`/stop=TRUE was set as default.  This was more or less chosen randomly.

It has been bugging me increasingly ever since, for a few reasons:

* it is very rare for me to break dozens of tests at once, but it is quite common to break one test intentionally (which then stops the test running) while breaking three tests unintentionally (which then isn't reported).
* the compiled-C-code vs git-version-check breaks a lot on me and stops the tests, even when I'm only making Python changes that don't need recompilation;
* it's actually impossible to unset stop=TRUE at the command line to nosetests;

as such, I've actually created my own copy of setup.cfg with 'stop=FALSE' set and I run that myself. But I actually think the default should be stop=TRUE for everyone.

A separate and longer term fix might be to make the test running faster, but that's out of scope for this issue.

Any objections?

**Comment by mr-c** [comment]
I also hate this default. +1 to dropping the line

**Comment by bocajnotnef** [comment]
Closing #1124, changes merged
