### ISSUE TITLE
Turn off default hashtable/graph size output on unique-kmers.py

### ISSUE THREAD

**Issue by ctb** [dib-lab/khmer#1141]
So... finally got around to running `unique-kmers.py`, and noticed that by default this outputs a bunch of info about hashtables and so on.  This isn't a good default option, IMO; people will want to count k-mers without necessarily doing anything else. Moreover, there's no way to turn it off.  I think we should have it off by default, and then provide an option to turn on bloom filter/countmin sketch parameter settings.

Last but not least, size_hashtable is -x, number_hashtable is -N, and expected memory usage is -M in khmer parlance - probably shouldn't use Z and H here.

@bocajnotnef @luizirber thoughts?

**Comment by bocajnotnef** [comment]
All good points. I can fire up a new pull for this soon.

**Comment by ctb** [comment]
Fixed by #1145.
