### ISSUE TITLE
collect_high_abundance_kmers partially removed

### ISSUE THREAD

**Issue by mr-c** [dib-lab/khmer#1142]
#1044 removed the CPython function `hashtable_collect_high_abundance_kmers` which is used by `sandbox/find-high-abund-kmers.py`.

Unless someone objects, after three days I am going to remove this script and the underlying C++ function in `lib/counting.cc`

**Comment by ctb** [comment]
On Sun, Jul 05, 2015 at 05:16:34AM -0700, Michael R. Crusoe wrote:
> #1044 removed the CPython function `hashtable_collect_high_abundance_kmers` which is used by `sandbox/find-high-abund-kmers.py`.
> 
> Unless someone objects, after three days I am going to remove this script and the underlying C++ function in `lib/counting.cc`

It appears to have been removed from the CPython API already.

**Comment by mr-c** [comment]
Yep, but not the C++ API nor from all sandbox scripts.
