### ISSUE TITLE
[lib/labelhash.hh:112]: (error) Memory is allocated but not initialized: c

### ISSUE THREAD

**Issue by mr-c** [dib-lab/khmer#1143]
@camillescott @ctb  is this a false positive?

**Comment by ctb** [comment]
I don't see anything relevant to this at lib/labelhash.hh line 112.  Is this referring to something in `check_and_allocate_label`? Looks like legit code to me.

**Comment by mr-c** [comment]
Yeah, the code shifted a bit; now line 105. I thought the same thing. Guess I'll mail the cppcheck people

**Comment by ctb** [comment]
Code removed in #1376.
