### ISSUE TITLE
Argparse arg naming inconsistencies throughout codebase

### ISSUE THREAD

**Issue by bocajnotnef** [dib-lab/khmer#1169]
https://github.com/dib-lab/khmer/blob/master/scripts/trim-low-abund.py#L86 
vs
https://github.com/dib-lab/khmer/blob/master/oxli/build_graph.py#L34

We should settle on a single thing; I nominate `output_filename`'

@mr-c @luizirber @mr-c @camillescott thoughts?

**Comment by ctb** [comment]
On Fri, Jul 10, 2015 at 01:05:36PM -0700, Jake Fenton wrote:
> https://github.com/dib-lab/khmer/blob/master/scripts/trim-low-abund.py#L86 
> vs
> https://github.com/dib-lab/khmer/blob/master/oxli/build_graph.py#L34
> 
> We should settle on a single thing; I nominate `output_filename`'

Why not have the controlling script specify the directory/location to
check in this case?

**Comment by bocajnotnef** [comment]
we'd have to add an arg to the function which just seems excessive when it already takes in the `args` object from the controlling script.

**Comment by ctb** [comment]
On Fri, Jul 10, 2015 at 01:13:02PM -0700, Jake Fenton wrote:
> we'd have to add an arg to the function which just seems excessive when it already takes in the `args` object from the controlling script.

presumably this happens elsewhere in the codebase - maybe look through and see
whether it looks like the proposed global standardization causes problems
anywhere.

or, replace 'args' with a list of the directories being considered.

**Comment by bocajnotnef** [comment]
we rely on `_calculate_tablesize` which requires the args object (to determine if args.max_memory_usage is set, which we could work around I suppose); otherwise +1 to the list.

**Comment by ctb** [comment]
did you look through the codebase to see whether standardizing on names in `args` makes sense?

**Comment by bocajnotnef** [comment]
I believe it does--especially if we're getting in the habit of tossing `args` objects about to do information gathering/checking on them.

increases modularity of the scripts and would also probably make it easier to migrate to an oxli-like API.

**Comment by luizirber** [comment]
Explicit is better than implicit, we are using only three arguments from the `args`. Why not refactor the function to take these three arguments instead?

**Comment by mr-c** [comment]
+1 for never passing the args object around

On Thu, Jul 16, 2015 at 11:48 AM Luiz Irber <notifications@github.com>
wrote:

> Explicit is better than implicit, we are using only three arguments from
> the args. Why not refactor the function to take these three arguments
> instead?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dib-lab/khmer/issues/1169#issuecomment-122047525>.
>
-- 
Michael R. Crusoe: Programmer & Bioinformatician crusoe@ucdavis.edu
The lab for Data Intensive Biology; University of California, Davis
https://impactstory.org/MichaelRCrusoe http://twitter.com/biocrusoe

**Comment by ctb** [comment]
On Thu, Jul 16, 2015 at 12:50:50PM -0700, Michael R. Crusoe wrote:
> +1 for never passing the args object around

Mmmh, good general rule, but I support passing in 'args' for functions in
khmer_args.  Consider the future situation in which we want to make use of a
passed in # of k-mers and false positive rate!  But outside of khmer_args,
sure, let's not do it.

--titus

**Comment by bocajnotnef** [comment]
hm. and I just about finished refactoring everything to play nice without
having access to an args object. Oops.

So--throw `args` around inside of khmer_args (and bits of kfile, since
that's usually the portal to khmer_args)?

**Comment by ctb** [comment]
On Thu, Jul 16, 2015 at 01:38:52PM -0700, Jake Fenton wrote:
> hm. and I just about finished refactoring everything to play nice without
> having access to an args object. Oops.

Well, throw it up in the PR and we'll see how it looks.

> So--throw `args` around inside of khmer_args (and bits of kfile, since
> that's usually the portal to khmer_args)?

Dunno about kfile.

--t

**Comment by ctb** [comment]
Closing for now, with #1170. Maybe it will rear i's ugly head again later.
