### ISSUE TITLE
Deal appropriately with --unique-kmers argument

### ISSUE THREAD

**Issue by ctb** [dib-lab/khmer#1179]
The addition of `-U/--unique-kmers` should not have applied to *all scripts* (see https://github.com/dib-lab/khmer/pull/1126/files#diff-2ebccdb74ba5df72b22cff1bd70d9696R63) if it was going to be ignored by all of them!  We should either make it work for all scripts (which should be easy after #1050, no?) or move the parameter addition into the one bit of code that uses it on `oxli/functions.py`.

**Comment by ctb** [comment]
If we make it work for all scripts, this will fix #347.

**Comment by ctb** [comment]
Oh, and I found a reference to args.unique_kmers in scripts/normalize-by-median.py - this should be moved into khmer_args.py, and the warning message starting with `WARNING: You are loading a saved k-mer table from...` should be updated.

**Comment by ctb** [comment]
Note the argument optimization language should change to `counting table size will NOT be set automatically.` as per https://github.com/dib-lab/khmer/pull/1126/files#r34570761.

**Comment by bocajnotnef** [comment]
I'll get this sorted once #1170 lands.

**Comment by ctb** [comment]
#1170 has landed. ;)

**Comment by bocajnotnef** [comment]
Hooplah!

**Comment by ctb** [comment]
ping @bocajnotnef

**Comment by bocajnotnef** [comment]
Yup, this is up next after I finish current stuff.

**Comment by ctb** [comment]
Ping wrt #1117.
