### ISSUE TITLE
Standardize long form of -o to be consistent across scripts/

### ISSUE THREAD

**Issue by ctb** [dib-lab/khmer#1188]
We currently use --out and -output, variously.  I don't care which we use.

Note the use of --output-first, --output-dir, etc. Not sure we should do anything about that.

**Comment by bocajnotnef** [comment]
+1 for 'output'

I touch most of these files in #747 anyway--I could add it into that PR

**Comment by ctb** [comment]
On Fri, Jul 24, 2015 at 02:24:31PM -0700, Jake Fenton wrote:
> +1 for 'output'
> 
> I touch most of these files in #747 anyway--I could add it into that PR

I would wait until #1186 and #1180 are merged; those are going to be somewhat
painful already for you in #747...

**Comment by bocajnotnef** [comment]
Mm, good point.

**Comment by ctb** [comment]
Note, we may want to consider reserving -o as *always* meaning --output or whatever (so change --output-dir to be -d or something).

**Comment by ctb** [comment]
Update: I've changed the short form of `--output-dir` to `-d` in #1164, for both interleave-reads and split-paired-reads.

**Comment by ctb** [comment]
In-meeting decision: `-o/--output`. Fixing globally (for scripts/ at least) in #1164.

**Comment by ctb** [comment]
Fixed in #1164.
