### ISSUE TITLE
Document OS X Python bug and submit a minimal test case

### ISSUE THREAD

**Issue by bocajnotnef** [dib-lab/khmer#1190]
debugging led by @mr-c revealed the error plauging the OSX builder is in fact a python bug, solved by upgrading stock python (2.7.6) using python.org's 2.7.10

The problem appeared to be that the exception message was optimized out. We attempted to work around this by explicitly setting the exception text in read_parsers.cc instead of using the default constructor.

so, to do:

 - [x] install pythons 2.7.7+ (official releases) until we find which one fixes the problem
    - [x] scan the release notes to see what they fix

if release note grokking fails we could disable that test for OSX.

@luizirber Got a good way to download/install multiple python versions (and/or make them coexist nicely?)

Bonus: test Python installed via Brew & Anaconda; also Python 3.3+ on OS X

**Comment by kdmurray91** [comment]
@bocajnotnef  [pythonz?](https://github.com/saghul/pythonz)

**Comment by bocajnotnef** [comment]
Ooh, I like.

@mr-c would that work for a jenkins environment?

**Comment by mr-c** [comment]
- [ ] split test into two: one that looks for the exception and the other that tests for the specific value exception message
- [ ] add a `@attr` to the second test to prevent running on OS X
- [ ] make a PR for the above while the rest of this issue is being investigated

**Comment by bocajnotnef** [comment]
Workaround  up in #1192

**Comment by bocajnotnef** [comment]
python.org python 2.7.7 also passes.

Whee

**Comment by bocajnotnef** [comment]
python.org python 2.7.6 passes

What version of python ships with OSX, you ask? Why, 2.7.6 of course!

**Comment by mr-c** [comment]
@kdmurray91 alas pythonz compiles new Python; we are interested in testing the various binary distributions of Python

Since python.org's Python doesn't have the issue I declare this to be a problem with Apple's customization. 

A very enterprising person could:
- [ ] construct an irreducible test case and file a bug

**Comment by mr-c** [comment]
The test case at https://github.com/dib-lab/khmer/commit/34502900472a009754fa1921b9afae68a5b52a2f#diff-0e869b7a17ce1f9ac85bc00b330c804fR327 triggers the bug

**Comment by kdmurray91** [comment]
Note that this bug or a similar one appears to affect Debian unstable too. See #885 for build logs etc.

Some gitter notes from @mr-c  and myself
> I'd just quilt patch as it is only a problem for Debian Unstable right now

> A minimal test case + report upstream needs to be made at some point

> It's not anything to do with how we store exception strings is it? does using char * instead of std::string change things perhaps?
> I.e. dtors delete-ing the string after PyErr_SetString(msg.c_str()); (or whatever it is)

**Comment by ctb** [comment]
Fixed in #1192, I think.
