### ISSUE TITLE
Write a utility function for copying test data into a temp directory

### ISSUE THREAD

**Issue by ctb** [dib-lab/khmer#1225]
This is a common code pattern in our test code:

    infile = utils.get_temp_filename('test.fq')
    shutil.copyfile(utils.get_test_data('paired-mixed-2.fq'), infile)

We could make this a one-liner quite easily...

Suggested approach:

* write a function in khmer_tst_utils called `copy_test_data(testfile)`.
* refactor into some tests.
* ask for review.

**Comment by caitsydney** [comment]
Working on this issue

**Comment by camillescott** [comment]
You might try following this pattern: https://github.com/camillescott/dammit/blob/master/dammit/tests/utils.py#L68

You'd have to add in support for multiple files and whatnot, but the `with TestData('data.fa', directory) as testdata: ...` pattern has been pretty nice for dammit's tests.

**Comment by caitsydney** [comment]
@camillescott - not sure I'm following. What's the benefit to doing this instead of just adding a `copy_test_data(testfile)` function to `khmer_tst_utils.py`? Is it because then we can use `with`?

**Comment by luizirber** [comment]
The `with` statement does the cleanup (deletes the temporary file after
usage).

**Comment by ctb** [comment]
The CLEANUPLIST mechanism is also fine to use & the code is simpler. I don't think it matters which one you use.

**Comment by ctb** [comment]
Closed in #1400.
