### ISSUE TITLE
Update installation instructions for people without root

### ISSUE THREAD

**Issue by ctb** [dib-lab/khmer#1227]
http://khmer.readthedocs.org/en/latest/user/install.html

in particular, we should point out that HPC/shared server users may be able to use virtualenv to install things.

**Comment by betatim** [comment]
The install docs already assume you are using a virtualenv, should we add an explicit mention "this might also work on your cluster"?

**Comment by ctb** [comment]
On Fri, Feb 24, 2017 at 11:55:54AM -0800, Tim Head wrote:
> The install docs already assume you are using a virtualenv, should we add an explicit mention "this might also work on your cluster"?

yes!
