### ISSUE TITLE
Can we remove -x and -N options from -h and doc/user/scripts.txt output?

### ISSUE THREAD

**Issue by ctb** [dib-lab/khmer#1232]
With the new -M and -U we don't need them any more and I think we would prefer they be hidden.

ping @mr-c

**Comment by ctb** [comment]
Yes - http://stackoverflow.com/questions/11114589/creating-hidden-arguments-with-python-argparse

@mr-c can I add this to #1214?

**Comment by mr-c** [comment]
+1 for hiding

We also need to update `whats-new.rst` due to #1214

**Comment by ctb** [comment]
See also #399 for `--force` and `--expert` flag settings.

**Comment by ctb** [comment]
I'm actually +/- 0 on this, since it turns out the official argparse way to do this is to replace the help message with argparse.SUPPRESS - so now there's no user-accessible docs on what -x and -N do.  That's probably OK for 2.0 but down the road I'd like to add something where advanced users can ask for all possible args, and get sensible help on them... will require argparse hacking tho.

**Comment by mr-c** [comment]
Bumping to 2.0+
