### ISSUE TITLE
unique-kmers: option to stream out sequences

### ISSUE THREAD

**Issue by luizirber** [dib-lab/khmer#1239]
`--stream-out` option was [added][1] on #1053. It is somewhat clear, but not so concise.

Other scripts use `-o -`, but in `unique-kmers` context it doesn't sound right, because the output of the script is the # of unique kmers (and it is covered by `-R outfile`).

Should we stick with it for future scripts, or do we need a better short/long option combination?

@ctb

[1]: https://github.com/dib-lab/khmer/pull/1053/files#diff-063fcf6aa34dea5e1df4d9b40c01d3b8R69

**Comment by mr-c** [comment]
how about `--stream-seqs` or `--stream-records`?

**Comment by ctb** [comment]
On Thu, Aug 13, 2015 at 12:14:00PM -0700, Michael R. Crusoe wrote:
> how about `--stream-seqs` or `--stream-records`?

+1 stream-records

**Comment by mr-c** [comment]
Fixed in #1252
