### ISSUE TITLE
Dead link in docs

### ISSUE THREAD

**Issue by bocajnotnef** [dib-lab/khmer#1242]
http://angus.ged.msu.edu.s3.amazonaws.com/88m-reads.fa.gz from https://github.com/dib-lab/khmer/blob/master/doc/user/blog-posts.rst is dead.

ping @ctb

**Comment by mr-c** [comment]
I've found a copy on Athyra:

`/home/LYORN_HOME/ftp/public/titus/88m-reads.fa.gz`

**Comment by mr-c** [comment]
Fixed in #1269
