### ISSUE TITLE
Determine system memory automatically and offer suggestions?

### ISSUE THREAD

**Issue by ctb** [dib-lab/khmer#1249]
I noticed that MEGAHIT (https://github.com/voutcn/megahit) has the following output --

```
 14.0Gb memory in total.
 Using: 13.219Gb.
```

I'm not sure we want to do this - it seems potentially problematic for HPC & queuing environments! - but would be nice to provide it as an option, maybe.

**Comment by mr-c** [comment]
Now that `-M` has landed it could be a nice alternative to not running at all. There should be a warning printed, though.

**Comment by standage** [comment]
@ctb I'm -0 on this one.

**Comment by ctb** [comment]
why? too confusing?

**Comment by standage** [comment]
Mostly for the HPC / shared environment issue you raised above. I think #1259 would be great in terms of use experience.

**Comment by ctb** [comment]
Should be possible to do something sensible on default, like

* automatically grab 80% of available memory, up to 16 GB;
* ignore automatic behavior whenever -x, -N, -M etc specified.

Our memory parameter stuff is becoming a morass so ... simplification welcome :)

**Comment by standage** [comment]
Embarrassingly I've never had to worry about this much, so: with memory, do we compute 16 GB as `16 x 1000 x 1000 x 1000` or `16 x 1024 x 1024 x 1024`?

**Comment by ctb** [comment]
Decision in #1396 was wontfix.
