### ISSUE TITLE
Look into upgrading README and/or using Description of a Project schema

### ISSUE THREAD

**Issue by ctb** [dib-lab/khmer#1250]
See conversation at https://twitter.com/mkramer/status/631559419168489472. @melodykramer suggests:
1. In plain language, what is this project and what does it do?
2. Who made this project?
3. Who is the audience for this project?
4. How do I set this project up on my own machine?
5. How do I test this project to make sure it works?
6. Who has adapted this project and can I see screenshots or examples?
7. Who do I contact if I need help with this project?
8. What languages is this project in?
9. If I wanted to help with this project, what is the best way to do that?
10. Is the project in active development?
11. What is the licensing on this project?

and then julianhyde suggested looking at "Description of a Project", https://en.wikipedia.org/wiki/DOAP

**Comment by mr-c** [comment]
FYI, our  PyPI page gets us DOAP for free. We could also ship it directly.

**Comment by melodykramer** [comment]
This discussion might also be of interest: https://github.com/18F/open-source-guide/issues/15#issuecomment-129455754

**Comment by mr-c** [comment]
Thank you @melodykramer for linking to that conversation

**Comment by betatim** [comment]
Closed via #1644
