### ISSUE TITLE
create link to latest version at top of previous versions of documentation 

### ISSUE THREAD

**Issue by ljcohen** [dib-lab/khmer#1253]
backstory: @ACharbonneau and I were reading previous version of documentation and doing wrong things before realizing we were in the wrong version

**Comment by mr-c** [comment]
Adding a link to "latest" is easy. A link that says "this isn't the latest!!" isn't straightforward.

**Comment by ctb** [comment]
Could also point people at correct version for the script at the bottom
of the script help output.

Perhaps relevant: #1224.

**Comment by betatim** [comment]
A simple thing to improve the odds of people finding the latest version of the docs would be to adjust the default version on RTD to 'latest' instead of a specific version. I can't look at the RTD config but I guess that v2.0 has been selected explicitly as the default version. This means http://khmer.readthedocs.io/ redirects to http://khmer.readthedocs.io/en/v2.0 not http://khmer.readthedocs.io/en/latest/ which people then bookmark and visit for ever after.

---

Couldn't find any ready made "add a warning banner to your docs" blog posts/guides with a quick google

**Comment by standage** [comment]
Yes, changing the default in RTD is trivial.

**Comment by betatim** [comment]
Do you have enough privilege to do it? Might be worth waiting a moment to hear from someone why they chose to use explicit versions before changing it.

**Comment by ctb** [comment]
-1 - the docs should be set to whatever version of the code people get when
they do 'pip install'.

--t

On Fri, Feb 24, 2017 at 08:24:31AM -0800, Tim Head wrote:
> A simple thing to improve the odds of people finding the latest version of the docs would be to adjust the default version on RTD to 'latest' instead of a specific version. I can't look at the RTD config but I guess that v2.0 has been selected explicitly as the default version. This means http://khmer.readthedocs.io/ redirects to http://khmer.readthedocs.io/en/v2.0 not http://khmer.readthedocs.io/en/latest/ which people then bookmark and visit for ever after.
> 
> ---
> 
> Couldn't find any ready made "add a warning banner to your docs" blog posts/guides with a quick google
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/dib-lab/khmer/issues/1253#issuecomment-282334720
-- 
C. Titus Brown, ctbrown@ucdavis.edu

**Comment by betatim** [comment]
Ah yes, because latest -> master. There is also http://khmer.readthedocs.io/en/stable/ which points to the last tag/release:
```
We also create a `stable` version, if your project has any tagged
releases. `stable` will be automatically kept up to date to
point at your highest version.
```

**Comment by standage** [comment]
We haven't been cutting releases frequently enough for this to be much of a problem, but changing the default to `stable` would save us the trouble of having to manually update the default each time to do cut a release.

**Comment by standage** [comment]
I just changed the default to `stable` on ReadTheDocs. I don't think there's much else we can do for now. Anyone with specific ideas feel free to reopen this thread.
