### ISSUE TITLE
[RFC] Putting version numbers into .info files?

### ISSUE THREAD

**Issue by kdmurray91** [dib-lab/khmer#1254]
Do you think it could be valuable to write the precise version of khmer used to generate a {Count,Node}graph into the corresponding `.info` files? I came across some old files and wanted to know which version of khmer had created them, but this isn't recorded in the info files AFAICT.

**Comment by mr-c** [comment]
Yes!

**Comment by kdmurray91** [comment]
While we're at it, are there any other things that should go in there? Like dimensions, or k size?

**Comment by kdmurray91** [comment]
And where other than `load-into-countgraph` would this be welcome?

**Comment by mr-c** [comment]
All the metadata would be great, and all the scripts should eventually do this. See #676
