### ISSUE TITLE
Loading older Countgraphs causes `std::bad_alloc`

### ISSUE THREAD

**Issue by kdmurray91** [dib-lab/khmer#1258]
Loading a counting hash created about a month ago with the current master causes a C++ ``std::bad_alloc`` exception to be thrown. My hunch is that this has something to do with the new field in the file format for the number of occupied bins. I don't have time to test this today but will do a git bisect on Monday if I get time and no-one beats me to it.

If my hunch is correct, then I'd advocate bumping the file format version at a minimum, so that the user gets an "invalid file" error, rather than ``std::bad_alloc``.

Cheers,
K

**Comment by kdmurray91** [comment]
@ctb would this be a 2.0 blocker? If so I can do my best to debug it on Monday...

**Comment by ctb** [comment]
On Sat, Aug 15, 2015 at 10:23:37PM -0700, Kevin Murray wrote:
> Loading a counting hash created about a month ago with the current master causes a C++ ``std::bad_alloc`` exception to be thrown. My hunch is that this has something to do with the new field in the file format for the number of occupied bins. I don't have time to test this today but will do a git bisect on Monday if I get time and no-one beats me to it.
> 
> If my hunch is correct, then I'd advocate bumping the file format version at a minimum, so that the user gets an "invalid file" error, rather than ``std::bad_alloc``.

You're almost certainly correct.  @mr-c and I discussed it and decided not
to bump file version numbers multiple times in a release; maybe that should
be revisited.

**Comment by mr-c** [comment]
.Hey @kdmurray91, thank you for reporting this.

My understanding is that this will only affect those who have been using a non-released version. 

There is a trade off between the development version having room to grow and break and keeping everything strictly stable.

Fundamentally I am okay with that.

**Comment by kdmurray91** [comment]
Yep, and I'm OK with it too. I'll close it as a 'wont-fix' bug.

**Comment by kdmurray91** [comment]
Although, is it worth noting in the release notes? Just in case someone else has done similarly?
