### ISSUE TITLE
--max-memory-usage input

### ISSUE THREAD

**Issue by macmanes** [dib-lab/khmer#1259]
It seems that `--max-memory-usage` should take the samtools-like human readable options, instead of what it does now. So, instead of `--max-memory-usage 4e10`, wouldn't `--max-memory-usage 8G` or `--max-memory-usage 400M` be easier for users to specify?

**Comment by mr-c** [comment]
Howdy @macmanes!

This is a great idea, thank you for suggesting it. I've added it to the Milestone for the release after 2.0.

**Comment by blubse** [comment]
I will work on this

**Comment by mr-c** [comment]
@blubse Great! Let us know if you have any questions.

**Comment by blubse** [comment]
Is it OK to use a library which is licensed under the MIT license?

**Comment by ctb** [comment]
@blubse should be ok, but in general we want to minimize dependencies. What library are you thinking of?

**Comment by blubse** [comment]
https://humanfriendly.readthedocs.org/ But If you don't want an extra library it should not take me too long to reimplement the needed function.

**Comment by ctb** [comment]
Happy to consider. We can also make it an optional dependency. Pure Python dependencies are much easier than not, too.

What is the full range of functionality you're thinking of here? I'm not even sure what samtools supports, frankly.

**Comment by standage** [comment]
Found the [humanfriendly](https://github.com/xolox/python-humanfriendly) package, but unfortunately it [doesn't handle units correctly](https://github.com/xolox/python-humanfriendly/issues/4). :(

**Comment by standage** [comment]
@macmanes Human-friendly memory requests are available from the current master, and will be included in the v2.1 release. It allows K, M, G, or T as a suffix when requesting memory.
