### ISSUE TITLE
'nosetests' fail on Mac OS X

### ISSUE THREAD

**Issue by ctb** [dib-lab/khmer#1264]
with latest master (94d679f2e), Python 2.7.2,

```13.4.0 Darwin Kernel Version 13.4.0: Wed Mar 18 16:20:14 PDT 2015; root:xnu-2422.115.14~1/RELEASE_X86_64 x86_64.```

I get:

```
======================================================================
FAIL: tests.test_read_parsers.test_read_pair_iterator_in_error_mode_xfail
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/t/dev/ipy/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/t/dev/khmer/tests/test_read_parsers.py", line 338, in test_read_pair_iterator_in_error_mode_xfail
    assert "Invalid read pair" in str(exc), str(exc)
AssertionError

----------------------------------------------------------------------
Ran 349 tests in 4.954s
```

**Comment by mr-c** [comment]
Yep, that is an OS X Mavericks box so I'm not surprised.

**Comment by ctb** [comment]
039e5cc5f is broken; 28193b132a works (via git bisect). I'm sensing a trend (see #1263).

**Comment by ctb** [comment]
There's too many files changed for me to figure out where this problem lies. It seems like a change that is probably unrelated to the commit, though... @camillescott?

**Comment by ctb** [comment]
Oh, I see; this test is turned off in 'make test' but not in 'nosetests'. Not sure there's anything to be done about that.

**Comment by mr-c** [comment]
If you add `!linux` to the `-attr` line you can use `nosetests` still (that's what the Makefile does).

**Comment by ctb** [comment]
On Mon, Aug 17, 2015 at 06:35:52PM -0700, Michael R. Crusoe wrote:
> If you add `!linux` to the `-attr` line you can use `nosetests` still (that's what the Makefile does).

Yes, well, I know that ;). But since 'make test' wasn't working...
