### ISSUE TITLE
error about load_countgraph in count-kmers.py

### ISSUE THREAD

**Issue by chvlyl** [dib-lab/khmer#1271]
Hi,
    Thanks for this great software! 
    I'm trying to get the kmer counts by using the following code:
    ```../../sandbox/count-kmers.py -o test_kmers_count.txt stamps-reads.ct ../../data/stamps-reads.fa.gz```
    However, I got an error 
    ```AttributeError: 'module' object has no attribute 'load_countgraph'```
    
     Any idea how to solve this?
     Thanks for the help!

Best
Eric

**Comment by chvlyl** [comment]
I ran the above code in virtualenv. If I try install the khmer first by python setup.py install, then the error is gone.

**Comment by ctb** [comment]
On Fri, Aug 21, 2015 at 10:59:40AM -0700, Eric Z Chen wrote:
> I ran the above code in virtualenv. If I try install the khmer first by python setup.py install, then the error is gone.

Hi Eric,

I'm guessing you had an older version of khmer hanging out in your virtualenv;
we've been making a lot of internal naming changes lately in preparation for
2.0, which is what's behind this error.  I'm not sure how to help fix the
more general issue other than to say that if you get these kinds of problems
*after* installation, we definitely want to know :)

**Comment by mr-c** [comment]
Thank you @chvlyl for your report. Sounds like you fixed your problem so I'm going to close this issue.
