### ISSUE TITLE
test-data/goodversion* not all good anymore

### ISSUE THREAD

**Issue by mr-c** [dib-lab/khmer#1274]
and not all tested to be good.

Example:

```
(env)(sid)mcrusoe@localhost:~/khmer$ sandbox/print-tagset.py tests/test-data/goodversion-k32.stoptags 
Traceback (most recent call last):
  File "sandbox/print-tagset.py", line 24, in <module>
    main()
  File "sandbox/print-tagset.py", line 18, in main
    ht.load_tagset(sys.argv[1])
OSError: Incorrect file signature 0x44200 while reading tagset from tests/test-data/goodversion-k32.stoptags; should be OXLI
```

**Comment by mr-c** [comment]
@ctb I can't get the `_build_testfiles()` to work; it just runs forever.

**Comment by mr-c** [comment]
@ctb can you assist or should this get bumped to post-2.0?

**Comment by ctb** [comment]
On Sun, Aug 30, 2015 at 12:36:28PM -0700, Michael R. Crusoe wrote:
> @ctb can you assist or should this get bumped to post-2.0?

I don't have time/focus to work on khmer for the near future.
