### ISSUE TITLE
doc/dev/getting-started.rst has become too complex and also seems wrong in places

### ISSUE THREAD

**Issue by ctb** [dib-lab/khmer#1281]
This is no longer friendly to new users at all!

Suggestions:
- move prerequisites/dependencies stuff to another section; much of this requires root, too, which needs to be discussed;
- think about moving the virutalenv stuff elsewhere;
- omit macports, homebrew, and conda stuff, or move it elsewhere;
- remove ccache stuff to an advanced section, or omit completely
- move squash stuff out of "getting started";
- move merging changes to a new file (sentence starting with 'It is possible that when you do a')
- spellcheck the darn thing;
- get rid of cppcheck, maybe;
- pretty sure the commands under "Your second contribution..." are redundant and not correct - in particular, shouldn't we do a 'git pull dib master' here?
- Advanced merging also doesn't belong in a document named "getting started".

**Comment by mr-c** [comment]
Agreed! Punt to 2.0.1?
