### ISSUE TITLE
fix broken interleaved

### ISSUE THREAD

**Issue by macmanes** [dib-lab/khmer#1287]
Hi People, 

Is there a way to fix broken interleaved files to 'intact interleaved'? I was thinking about something like `extract-paired-reads.py`, but with option to output interleaved (to the stdout) instead of to `.pe` and  `.se` file. I'm thinking about ways to stream, like this:

```
 interleave-reads.py reads1.fastq reads2.fastq \
| skewer -Q 10 -t 2 -x /share/trinityrnaseq/trinity-plugins/Trimmomatic-0.32/adapters/TruSeq3-PE.fa - -1 \
| bwa mem -p test - | samtools view -Sb - > test.bam
```

This actually works for BWA, because if nicely deals with broken interleaved, but most tools to not..

**Comment by ctb** [comment]
On Wed, Sep 02, 2015 at 06:04:59AM -0700, Matt MacManes wrote:
> Is there a way to fix broken interleaved files to 'intact interleaved'? I was thinking about something like `extract-paired-reads.py`, but with option to output interleaved (to the stdout) instead of to `.pe` and  `.se` file. I'm thinking about ways to stream, like this:
> 
> ```
>  interleave-reads.py reads1.fastq reads2.fastq \
> | skewer -Q 10 -t 2 -x /share/trinityrnaseq/trinity-plugins/Trimmomatic-0.32/adapters/TruSeq3-PE.fa - -1 \
> | bwa mem -p test - | samtools view -Sb - > test.bam
> ```
> 
> This actually works for BWA, because if nicely deals with broken interleaved, but most tools to not.. 

So you don't mean:

     "extract-paired-reads.py -p - -s /some/where/else -"

From the above, I'm thinking that you might mean a flag that lets
interleave-reads build a broken-paired file?  Or only output reads
that are actually properly interleaved?
-- 
C. Titus Brown, ctbrown@ucdavis.edu

**Comment by macmanes** [comment]
ok.. this works as intended.. streaming from raw reads, through trimming, to a BAM file. Hey, this streaming stuff is *REALLY* great!! ;) 

```
interleave-reads.py reads1.fastq reads2.fastq \
| skewer -Q 2 -t 2 -x /share/trinityrnaseq/trinity-plugins/Trimmomatic-0.32/adapters/TruSeq3-PE.fa - -1 \
| extract-paired-reads.py -p - -s /dev/null - \
| bwa mem -p test - | samtools view -Sb - > test.bam
```

**Comment by ctb** [comment]
On Wed, Sep 02, 2015 at 06:19:26AM -0700, Matt MacManes wrote:
> ok.. this works as intended.. streaming from raw reads, through trimming, to a BAM file. Hey, this streaming stuff is *REALLY* great!! ;) 

excellent :)
