### ISSUE TITLE
README.rst & doc/index.rst duplicate a lot of content

### ISSUE THREAD

**Issue by mr-c** [dib-lab/khmer#1296]
Often some piece of information will get updated in one location but not the other. Would be nice if there was less duplication.

Ideas:
- Have sphinx include the contents of README.rst when rendering doc/index.rst
- Have README.rst include not much more than a link to the docs

**Comment by betatim** [comment]
Another PR related to this #1529

**Comment by betatim** [comment]
The README is pretty minimal now, closing.

**Comment by standage** [comment]
I'm doing a bit of cleanup right now :)
