### ISSUE TITLE
Unpaired reads file gets overwritten in some circumstances in khmer v1.4.1

### ISSUE THREAD

**Issue by ctb** [dib-lab/khmer#1298]
If -o is specified with -u, then the -u file is trashed.  Happens in khmer v1.4.1 for sure.

Following fix seems to work:

```
index 22c84dc..d95ca67 100755
--- a/scripts/normalize-by-median.py
+++ b/scripts/normalize-by-median.py
@@ -329,10 +329,9 @@ file for one of the input files will be generated.)" % filename 

     if args.paired and args.unpaired_reads:
         args.paired = False
-        output_name = args.unpaired_reads
         if not args.single_output_file:
             output_name = os.path.basename(args.unpaired_reads) + '.keep'
-        outfp = open(output_name, 'w')
+            outfp = open(output_name, 'w')
         total_acc, discarded_acc, corrupt_files = \
             normalize_by_median_and_check(
                 args.unpaired_reads, htable, args.single_output_file,
```

Not sure we should do anything about this, though, since 2.0 is coming out?

**Comment by mr-c** [comment]
I guess we should write a test for this if it doesn't already exist.

**Comment by betatim** [comment]
Running `normalize-by-median.py -p -k 17 -o blahha -u tests/test-data/single-read.fq tests/test-data/paired.fq` on b2ab51575c2 I end up with all reads in `blahha` and the two input files are untouched. I think this means this has been fixed in the meantime?

**Comment by ctb** [comment]
Yes, there's even a test for it.  Did we forget to reference it in the issue?

Anyway, I don't think we are planning to release 1.4.2 or anything so yes
we can close :)
