### ISSUE TITLE
normalize-by-median.py doesn't support streaming IO

### ISSUE THREAD

**Issue by grassa** [dib-lab/khmer#1303]
eg:

(khmerEnv)cgrassa@lipm-cnode3:~/pan_genome/test$ cat test.c.il.fq | normalize-by-median.py -k 31 -M 800000000 -o test.norm.fq /dev/stdin 

|| This is the script normalize-by-median.py in khmer.
|| You are running khmer version 2.0
|| You are also using screed version 0.7
||
|| If you use this script in a publication, please cite EACH of the following:
||
||   * MR Crusoe et al., 2015. http://dx.doi.org/10.12688/f1000research.6924.1
||   * CT Brown et al., arXiv:1203.4802 [q-bio.GN]
||
|| Please see http://khmer.readthedocs.org/en/latest/citations.html for details.

PARAMETERS:
 - kmer size =    31 		(-k)
 - n tables =     4 		(-N)
 - max tablesize = 2e+08 	(-x)

Estimated memory usage is 8e+08 bytes (n_tables x max_tablesize)
--------
making countgraph
** ERROR: [Errno 29] Illegal seek
** Failed on /dev/stdin: 
** Exiting!

**Comment by ctb** [comment]
Hi, please upgrade screed to 0.9 as well - this will fix.

If you could tell us how you are installing things we can amend our packages to detect this automatically - pip should have upgraded screed in the process, for example.

Thanks for the report!

--
Titus Brown, ctbrown@ucdavis.edu

**Comment by grassa** [comment]
Thanks for the quick response. I believe you. Oddly, my current setup seems to insist on importing screed 0.7. I'm not sure where its getting it from, though. I've tried uninstalling and installing screed in and out of the virtual environment, with and without sudo. The install messages all report that 0.9 is installed, but khmer always reports "|| You are also using screed version 0.7". I also fired up a python shell, imported screed, and printed the version, with the result being 0.7. This is probably an edge case - the computers are setup a little differently than what I'm accustomed to and I only have sudo access on this node - _but_ isn't the point of using the virtual environment to ensure everything is being pulled from the correct place? I also tried starting the virtual environment with "--no-site-packages", but alas, no dice. I'm not really a pythonisto, so it's possible that I'm missing something very basic.

**Comment by ctb** [comment]
On Fri, Sep 11, 2015 at 09:11:24AM -0700, Chris Grassa wrote:
> Thanks for the quick response. I believe you. Oddly, my current setup seems to insist on importing screed 0.7. I'm not sure where its getting it from, though. I've tried uninstalling and installing screed in and out of the virtual environment, with and without sudo. The install messages all report that 0.9 is installed, but khmer always reports "|| You are also using screed version 0.7". I also fired up a python shell, imported screed, and printed the version, with the result being 0.7. This is probably an edge case - the computers are setup a little differently than what I'm accustomed to and I only have sudo access on this node - _but_ isn't the point of using the virtual environment to ensure everything is being pulled from the correct place? I also tried starting the virtual environment with "--no-site-packages", but alas, no dice. I'm not really a pythonisto, so it's possible that I'm missing something very basic.

How odd!

try:

    print screed

right after the import, and it will tell you what file is being imported -- a
good way to find the location of screed 0.7.  Then go nuke that directory :)
(Or just chmod a-rwx it, maybe?)

**Comment by grassa** [comment]
thanks for the tip! 
export PYTHONPATH=""
before launching the virtualenv made it work.

**Comment by ctb** [comment]
great, thank you!

On Fri, Sep 11, 2015 at 09:31:07AM -0700, Chris Grassa wrote:
> Closed #1303.
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/dib-lab/khmer/issues/1303#event-407263189
-- 
C. Titus Brown, ctbrown@ucdavis.edu
