### ISSUE TITLE
DOI is Broken

### ISSUE THREAD

**Issue by reedacartwright** [dib-lab/khmer#1311]
The documentation currently lists "http://dx.doi.org/10.12688/f1000research.6924.1" as the DOI to the latest paper.  This DOI is currently resolving as "DOI not found."

**Comment by ctb** [comment]
On Sun, Sep 20, 2015 at 09:07:00PM -0700, Reed A. Cartwright wrote:
> The documentation currently lists "http://dx.doi.org/10.12688/f1000research.6924.1" as the DOI to the latest paper.  This DOI is currently resolving as "DOI not found."

Hi Reed,

the DOI is reserved for the forthcoming paper, which has not yet made it
out from F1000 Research

thx,
--titus

**Comment by reedacartwright** [comment]
Thanks, Titus,
I'm undergoing my third-year review this year, and I'm trying to update my CV.

**Comment by ctb** [comment]
The paper is finally available in non-peer-reviewed form: http://f1000research.com/articles/4-900/v1. Perhaps the DOI will resolve correctly soon :)

**Comment by ctb** [comment]
DOI working!
