### ISSUE TITLE
unpaired read dataset generated when running collect-reads

### ISSUE THREAD

**Issue by hyphaltip** [dib-lab/khmer#1323]
Running (master 53484edfaa5ff0f7c088e084b00f528d781d4c10 )
./khmer/sandbox/collect-reads.py -M 32e9 -C 100 reads-fq-bigmem.kh reads.merged.fq.gz -o reads-fq-bigmem.100x.fq

I always get a /1 pair but not a /2 for the last read set output -- I can trim it off manually after everything but I assume this is unintended behavior?

**Comment by ctb** [comment]
On Sun, Nov 01, 2015 at 02:16:14PM -0800, Jason Stajich wrote:
> Running (master 53484edfaa5ff0f7c088e084b00f528d781d4c10 )
> ./khmer/sandbox/collect-reads.py -M 32e9 -C 100 reads-fq-bigmem.kh reads.merged.fq.gz -o reads-fq-bigmem.100x.fq
> 
> I always get a /1 pair but not a /2 for the last read set output -- I can trim it off manually after everything but I assume this is unintended behavior?

The script doesn't treat /1 or /2 specially, so I'm not sure why you'd get
a bias unless it was present in the data.  Does that make sense?
