### ISSUE TITLE
{Count,Node}Graph Compression

### ISSUE THREAD

**Issue by kdmurray91** [dib-lab/khmer#1325]
Hi all,

I'm raising a new issue to talk about compression of CountGraphs (and Nodegraphs, by extension). My tool [kwip](https://github.com/kdmurray91/kwip) heavily utilises countgraph IO, and you can really see the overhead of either, a), gzip decompression, or b), uncompressed IO. This lead me to implement #1018, which cuts down on this overhead significantly. However, that has languished a bit, and has lead me to think a bit more about this.

Given my use case, this is all about speed, and not really about disc usage (if yours is, just use gzip). That opens up more possibilities for lower compression ratio, ultra-fast compression algorithms like [blosc](http://www.blosc.org/) or [lz4](http://fastcompression.blogspot.no/p/lz4.html), or [zstd](https://github.com/Cyan4973/zstd) per #1018 (gzip-like compression, but much faster), or even snappy.

Now for the discussion:

- Does the project feel that it needs the option of this sort of compression?
- If so, how would you like it implemented? @mr-c made a good case for thinking of compression as an external process, that basically acts as a container around the plain old countgraph file format. i.e. any compression in khmer is purely a convenience/efficiency helper for calling gzip or bzip2 on the countgraph file. Thoughts?
- Which of the many algorithms do people think would be best? I like the idea of blosc, as it is specifically designed for large numeric matrices. And seems fairly trivial to bundle. But I don't think it fufuls the encapsulation wishes @mr-c had. And #1018 already is implemented which, out of sheer lazyness, is a plus for the zstd compression algorithm.

**Comment by ctb** [comment]
Hi @kdmurray91, I have very little useful to add :). I'm not personally wedded to the notion that it has to be an external process, although I think there are good reasons to keep the gzip compression working that way.  (Interesting side note - given streaming, it would be more efficient to pipe things to gzip/from gunzip than have it be implemented internally!)

Also see the RRR compression in #1074 - don't know if that would work for CMS, but might be worth taking a look.

**Comment by kdmurray91** [comment]
@ctb OK, cool. I definitely think that whatever is implemented here should complement rather than replace gzip or bzip. 

I also agree that the is no real need to have the external compression requirement for this use case. However, this raises a file-format issue, as it would be good to have a "compression" field to indicate any compression that has been applied internally, as opposed to in some external container format (e.g. gzip). There are numerous hacks that would allow this in a backwards-compatible way, including using a different file format ID for compressed files, as is implemented in #1018. 

So, to be a little more decisive, I'll let this fester for a week or so longer as an RFC. Then, depending on what others say, I'll do a review of #1018 and ensure it meets the project's standards before asking for review & merge.

To my mind the following are crucial requirements:

- [ ] fully backwards compatible
- [ ] uses a bundle-able compression algorithm (no license issues, not too many files)
- [ ] improves (compared to both gzip & uncompressed) overall round-trip time from RAM -> disk -> RAM (which is the use case I care about)
- [ ] Reasonable compression ratio (at least halves on disk size compared to uncompressed)

**Comment by mr-c** [comment]
Great plan. Kevin, will we be able to link dynamically to a separately
packaged library during packaging for Debian?

**Comment by kdmurray91** [comment]
@mr-c Given that zstd has been officially released, yes, I'll make a package for it too.

**Comment by ctb** [comment]
Sounds good!

**Comment by kdmurray91** [comment]
In the interest of having only one issue to forget about, I'm closing this. See the zstd PR (#1018) for further info.

Cheers,
K
