### ISSUE TITLE
khmer.hash_murmur3 returns 0 for sequences that are self complement

### ISSUE THREAD

**Issue by dkoslicki** [dib-lab/khmer#1353]
It appears that khmer.hash_murmur3 always returns 0 for sequences that are reverse complement to themselves.

Note:

```
import khmer
khmer.hash_murmur3('TATATATATATATATATATA')
khmer.hash_murmur3('TTTTGCAAAA')
khmer.hash_murmur3('GAAAATTTTC')
```

etc.

This may be due to something like line 179 of lib/kmer_hash.cc where a bitwise xor is performed on the hash of the sequence and its reverse complement.

**Comment by luizirber** [comment]
(in times like these I wish GitHub had /facepalm emojis...)

Yes, of course! I opened #1355 to work on it. As you can see the tests for mumur3 are very basic, thanks for pointing it out @dkoslicki!

**Comment by dkoslicki** [comment]
Happy to help!
