### ISSUE TITLE
`trim-low-abund.py ... --gzip -o -` fails on Python 3

### ISSUE THREAD

**Issue by ctb** [dib-lab/khmer#1363]
Witness:

```
% scripts/trim-low-abund.py data/100k-filtered.fa --gzip -o - | gunzip -c > /dev/null
...
created temporary directory ./tmp_6iiq1ovkhmer; use -T to change location
Traceback (most recent call last):
  File "scripts/trim-low-abund.py", line 530, in <module>
    main()
  File "scripts/trim-low-abund.py", line 403, in main
    trimfp = get_file_writer(outfp, args.gzip, args.bzip)
  File "/Users/t/dev/khmer/khmer/kfile.py", line 236, in get_file_writer
    ofile = gzip.GzipFile(fileobj=file_handle, mode='w')
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/gzip.py", line 192, in __init__
    self._write_gzip_header()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/gzip.py", line 220, in _write_gzip_header
    self.fileobj.write(b'\037\213')             # magic header
TypeError: write() argument must be str, not bytes
```

**Comment by ctb** [comment]
Similar issue elsewhere, may contain the relevant fix: https://github.com/tensorflow/tensorflow/issues/470

**Comment by ctb** [comment]
Note, works fine under Python 2.7.

**Comment by ctb** [comment]
See https://stackoverflow.com/questions/4374455/how-to-set-sys-stdout-encoding-in-python-3 for actual fixes.

**Comment by ctb** [comment]
Fixed in #11138 by commit 8cdf2edfc0419.

**Comment by ctb** [comment]
Note to @luizirber this probably needs expert review.

**Comment by ctb** [comment]
OK, this totally doesn't work. Working on it.

**Comment by luizirber** [comment]
We'll probably need something like this:
https://books.google.com/books?id=f7wGeA71_eUC&pg=PA163&lpg=PA163&dq=sys+stdout+detach&source=bl&ots=Xii20cj-Pl&sig=tyqjgQnUZfqdkaPMmLjHwskQ2-8&hl=en&sa=X&ved=0ahUKEwj4-aL9wNLMAhVP9mMKHSq4BUUQ6AEIVTAJ#v=onepage&q=sys%20stdout%20detach&f=false

I started rewriting `get_file_reader` as a context manager (so we can return `sys.stdout` to the original configuration), but it will require more changes in the code (wrap every usage of `get_file_reader` in a `with` statement, and some points in the code are convoluted to do that...)

**Comment by ctb** [comment]
OK. I think I may remove it from #1138 in the interests of getting that merged...

**Comment by luizirber** [comment]
:+1:

**Comment by ctb** [comment]
Working branch is #1367; has a test but no fix.

**Comment by camillescott** [comment]
I ran into a similar issue recently; it was fixed by changing mode of the file object. The culprit might be here: https://github.com/dib-lab/khmer/blob/master/scripts/trim-low-abund.py#L119

`wb` should probably just be `w`. Will test shortly.

**Comment by betatim** [comment]
Looking at this now

**Comment by betatim** [comment]
This looked like something quick to do related to the file mode shenanigans that we just solved for screed but apparently not.

gzip wants to write bytes (sensible) but the file handle it gets was opened with mode 'w', hence the error. The file object comes from somewhere inside argparse, but the type of the argparse argument is `type=argparse.FileType('wb')` and yet `parser.parse_args().output` is in 'w' mode only.

**Comment by betatim** [comment]
The proper solution will emerge from https://bugs.python.org/issue14156 one day.

For everyone else who needs something a bit sooner: workarounds.
