### ISSUE TITLE
Request for a c++ api example for new version.

### ISSUE THREAD

**Issue by hiraksarkar** [dib-lab/khmer#1364]
Hi, 
I am searching for a simple way (**in C++**) to build hash tables without specifying hash sizes, which would be C++ counter part of this,
ktable = khmer.new_ktable(6),
I understand that ktable is **removed** after version 1. In that case it would be great if there is something close to it (C++) in new versions. Thanks!

**Comment by ctb** [comment]
See #1365. You still have to specify the hash size but it can be computed as 4**k. It's fairly easy to fix up in the C++ interface if you end up using khmer; just poke us.

**Comment by ctb** [comment]
(We primarily use the C++ API via Python, but we are getting an increasing number of requests to clean it up. It can be a full priority until we have more developers, but more people => higher priority... :) cc @kdmurray91 @blahah.
