### ISSUE TITLE
khmer docs builds failing

### ISSUE THREAD

**Issue by ctb** [dib-lab/khmer#1391]
https://readthedocs.org/projects/khmer/builds/

ht @mr-c

**Comment by standage** [comment]
This isn't related to the oxli.org domain renewal is it?

**Comment by ctb** [comment]
No, it looks like ci.oxli.org itself is down; this is where @mr-c was
hosting his special sphinxcontrib module, I guess?

To get it working again, we need to adjust the install of:

sphinxcontrib-autoprogram==0.1.1-khmerdev-20140331

**Comment by mr-c** [comment]
I believe all the khmer specific changes were upstreamed in
sphinxcontrib-autoprogram

On Mon, Jun 27, 2016 at 1:24 PM, C. Titus Brown <notifications@github.com>
wrote:

> No, it looks like ci.oxli.org itself is down; this is where @mr-c was
> hosting his special sphinxcontrib module, I guess?
>
> To get it working again, we need to adjust the install of:
>
> sphinxcontrib-autoprogram==0.1.1-khmerdev-20140331
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/dib-lab/khmer/issues/1391#issuecomment-228813893>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ABROCM22_E80DklBEj0HocsXqRXHZ0-qks5qQAdGgaJpZM4I-WNv>
> .
>



-- 
Michael R. Crusoe
Community Engineer & Co-founder
Common Workflow Language project
https://impactstory.org/u/0000-0002-2961-9670
michael.crusoe@gmail.com
+32 (0) 2 808 25 58
+1 480 627 9108

**Comment by ctb** [comment]
cool, then it should just be a matter of fixing up the requirements!

(See

https://readthedocs.org/projects/khmer/builds/4143093/

for the specific details of the build failure.)

**Comment by ctb** [comment]
looks like it, @mr-c - https://bitbucket.org/birkenfeld/sphinx-contrib/src/4f83b4da94182a4145b2e1814766be610c19953c/autoprogram/sphinxcontrib/autoprogram.py?fileviewer=file-view-default
