### ISSUE TITLE
k-mer abundance histogram on GAGE data set

### ISSUE THREAD

**Issue by standage** [dib-lab/khmer#1398]
I'm reviewing a new k-mer counting tool and doing some accuracy assessments. The paper benchmarks on [GAGE](http://gage.cbcb.umd.edu/data/index.html) data, and I figured that would be an easy place to start.

I began by computing abundance histograms using exact algorithms from Jellyfish and Tallymer.

```
wget http://gage.cbcb.umd.edu/data/Staphylococcus_aureus/Data.original/frag_1.fastq.gz
gunzip frag_1.fastq.gz

jellyfish count -m 27 -s 100M -o frag_1-jelly-k27 -t 4 frag_1.fastq
jellyfish histo -l 1 -h 1000 -i 1 -t 4 -o frag_1-jelly-k27.hist frag_1-jelly-k27

gt suffixerator -dna -pl -tis -suf -lcp -db frag_1.fastq -indexname frag_1-tally-k27
gt tallymer mkindex -esa frag_1-tally-k27 -mersize 27 -maxocc 1000 > frag_1-tally-k27.hist 2> frag_1-tally-k27.log
```

Reassuringly, these give the same exact results.

```
diff -q <(perl -ne 'm/^\d/ and print' < frag_1-tally-k27.hist) frag_1-jelly-k27.hist
```

I then thought I'd do a sanity check with khmer.

```
abundance-dist-single.py -k 27 -M 3e9 --threads 4 frag_1.fastq khmer-k27.hist
```

I was surprised when I compared these results.

```
$ head -n 10 jelly-k27.hist khmer-k27.hist
==> jelly-k27.hist <==
1 17957557
2 930052
3 882356
4 799105
5 661358
6 514453
7 386974
8 281579
9 203872
10 144937

==> khmer-k27.hist <==
abundance,count,cumulative,cumulative_fraction
0,0,0,0.0
1,15988001,15988001,0.841
2,261824,16249825,0.855
3,188270,16438095,0.865
4,234402,16672497,0.877
5,268066,16940563,0.891
6,277962,17218525,0.906
7,265586,17484111,0.92
8,239235,17723346,0.932
```

I expected that the results would be slightly different, since khmer isn't using an exact algorithm. But I expected these differences to be small and, as described in [this paper](http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0101271), to be over-estimates rather than under-estimates.

I'm not convinced I haven't made a mistake somewhere? Did I do something wrong? Or am I missing something?

**Comment by ctb** [comment]
very puzzling. no immediate idea. note the Zhang paper has all the code
online in github, might take a quick look at it.

**Comment by standage** [comment]
![jelly-vs-khmer](https://cloud.githubusercontent.com/assets/566823/16498219/e9e53a5e-3eb7-11e6-8dd3-af88b53f6c07.png)

**Comment by ctb** [comment]
Ns. ISTR that Jellyfish and khmer handle Ns differently.

**Comment by standage** [comment]
Tried converting all Ns to As, and checked for lower case characters (there were none). Still get this. :(

![jelly-vs-khmer-n2a](https://cloud.githubusercontent.com/assets/566823/16500447/d5ff34e0-3ec1-11e6-8e11-e81eaeb52915.png)

**Comment by standage** [comment]
Thanks for the reminder about the paper's code. Jellyfish doesn't count k-mers on both strands by default. Adding the `-C` flag to `jellyfish count`, as in the Zhang paper, gives this.

![jelly-vs-khmer-n2a-bothstrands](https://cloud.githubusercontent.com/assets/566823/16501030/9c37be50-3ec4-11e6-866b-097327dfc336.png)

**Comment by ctb** [comment]
great, thx for chasing down!
