### ISSUE TITLE
Weird memory usage in abundance-dist-single.py

### ISSUE THREAD

**Issue by ctb** [dib-lab/khmer#1408]
Using the command:

```
abundance-dist-single.py -M 6e9 -b 7086_S82_L007.abundtrim.fq.gz 7086_S82_L007.abundtrim.fq.gz.hist -k 21 -s
```

I'm seeing 10 GB+ of RAM being used (see screenshot from top). More than 6 GB was requested and failed previously; this is on a 15 GB of RAM computer.

<img width="714" alt="screen shot 2016-07-18 at 9 53 18 am" src="https://cloud.githubusercontent.com/assets/51016/16916962/8b32a748-4ccd-11e6-98ff-a0ebf2c9678a.png">

**Comment by standage** [comment]
We should re-check this before the 2.1 release.

**Comment by betatim** [comment]
Can reproduce this.

`/scripts/abundance-dist-single.py -x 1e8 -b ecoli_ref-5m.fastq somehisto.hist -k 21 -s` uses 0.4GB and prints 0.4GB as its usage.

`./scripts/abundance-dist-single.py -M 4e8 -b ecoli_ref-5m.fastq somehisto.hist -k 21 -s` uses 0.8GB and prints 0.4GB as its usage.

**Comment by betatim** [comment]
(working on this)

**Comment by standage** [comment]
Smells a lot like #1549.

**Comment by betatim** [comment]
In this particular script we create a `Nodegraph` and a `Countgraph`. With the `-M 4e8` option both of those size themselves to be about ~400MB, hence we use ~800MB. In the `-x 1e8` case we make a 400MB `Countgraph` and a `Nodegraph` with 1e8 buckets, which doesn't add to the memory usage. PR incoming.
