### ISSUE TITLE
Move to CI-as-a-service

### ISSUE THREAD

**Issue by betatim** [dib-lab/khmer#1419]
Investigate moving from ci.oxli.org to travis/circleci/your-favourite-ci-as-a-service.

How much of the current tests can be run within the time limit? How likely is it more resource intensive tests will happen soon? Would they still work?

OSX and linux support?

**Comment by standage** [comment]
I'm familiar with travis, and I don't anticipate any issues with migrating that direction

- Looks like there's [OS X support](https://docs.travis-ci.com/user/osx-ci-environment/).
- [Timing shouldn't be a problem](https://docs.travis-ci.com/user/customizing-the-build/#Build-Timeouts): we have 50 minutes, as long as no command goes 10 minutes without producing output. This far exceeds our current usage.
- If we introduce more resource intensive tests, these could be run manually in preparaton for cutting a new release.

**Comment by betatim** [comment]
I was wrong about osx and travis. Doesn't cost anything.

**Comment by betatim** [comment]
Starting work on this.
