### ISSUE TITLE
py.test yield tests deprecated

### ISSUE THREAD

**Issue by standage** [dib-lab/khmer#1423]
I just upgraded to py.test 3.0.1, and I'm getting 69 copies of the following message after a (successful) `make test` invocation.

```
WC1 /Users/standage/Software/khmer-rcs/tests/test_scripts.py yield tests are deprecated, and scheduled to be removed in pytest 4.0
```

This probably isn't urgent, but something we should look into.

**Comment by betatim** [comment]
[Parametrized tests](http://doc.pytest.org/en/latest/parametrize.html#pytest-mark-parametrize-parametrizing-test-functions) seem to be the answer.
