### ISSUE TITLE
Dev instructions do not include "enchant" C library

### ISSUE THREAD

**Issue by standage** [dib-lab/khmer#1424]
Getting a clean Ubuntu environment setup for khmer dev/testing following [these instructions](https://khmer.readthedocs.io/en/v2.0/dev/getting-started.html), I got some warning messages saying that the enchant C library was not installed. We need to confirm the enchant package name for all of the package managers listed as examples and update this documentation.

**Comment by betatim** [comment]
[Arch linux uses `enchant`](https://www.archlinux.org/packages/?sort=&q=enchant&maintainer=&flagged=)

[RHEL6 seems to use `enchant`](http://stackoverflow.com/questions/36599004/problems-with-pyenchant-centos-el-capitan) as well.

**Comment by ctb** [comment]
This may be a bit OT, but I would like to think about narrowing our explicit
support documentation to RedHat and Ubuntu (and Mac OS X)  Realistically most
modern Linux installs run one or the other, AFAICT, and we have access to
both; beyond that we end up supporting esoterica.

**Comment by standage** [comment]
I'm +1 on dropping Arch linux instructions. Merge conflict resolution coming momentarily.
