### ISSUE TITLE
gcovr reported coverage changes from 3.2->3.3

### ISSUE THREAD

**Issue by betatim** [dib-lab/khmer#1429]
We observe some changes in coverage reported by `gcovr` when switching from 3.2 to 3.3.

See the discussion in #1418 and gcovr/gcovr#140.

This issue is to track the discussion and come to a conclusion.

**Comment by ctb** [comment]
So... closeable?

**Comment by betatim** [comment]
Yes. There doesn't seem to be a better conclusion than "it changed".
