### ISSUE TITLE
Simple benchmarking for the hash function

### ISSUE THREAD

**Issue by ctb** [dib-lab/khmer#1436]
Here's a simple benchmarking script that just creates hashes for a bunch of k-mers in a string:

https://gist.github.com/ctb/ce69abe77a40e4936f42652dfd41cb38

On master currently, it reports 0.17234091000136686.

On the deoptimized version in #1432, it reports 15.948195557000872.  So about a factor of 100x, which seems reasonable.

On the re-optimized version in #1437, it reports 0.17987623100634664, so back in business.

**Comment by ctb** [comment]
I think @betatim's got this.

**Comment by betatim** [comment]
What do you think of making this something that lives in `tests/` so that future-us can find it again? I wouldn't run it on travis and the like as there is probably too much variation.

**Comment by ctb** [comment]
On Tue, Oct 04, 2016 at 06:58:59AM -0700, Tim Head wrote:
> What do you think of making this something that lives in `tests/` so that future-us can find it again? I wouldn't run it on travis and the like as there is probably too much variation.

What about `benchmarks/`?

`tests/` is really for stuff that is run very frequently.
