### ISSUE TITLE
ChangeLog thoughts - why do we have it?

### ISSUE THREAD

**Issue by ctb** [dib-lab/khmer#1457]
Discussion from Sep 26 hangout --
- most people don't use or like the ChangeLog;
- CTB uses the ChangeLog to track down files that changed and may have broken something, but now that he knows how to use git bisect he doesn't do that any more;
- LI points out that it's the Debian format and may be useful for Debian releases;
- ChangeLog is useful for API breakage and tracking, but we don't have any.

Other issues:
- the current ChangeLog format breaks every merge without special tooling;
- the format itself is not nec standard (at least in CTB's emacs)

Should we ditch the ChangeLog?

Should we tool up and make it easy to regenerate the ChangeLog from the git commits?

Is there a way to autogenerate it from GitHub PRs for each release?

**Comment by betatim** [comment]
https://github.com/skywinder/github-changelog-generator is one (the most popular?) script to generate a Changelog from issues and PRs. Not used it myself. Could be integrated in travis if we think that is useful.

Personal opinion: a `whats_new.md` or release notes are what I look at most. Changelogs tend to feel like `git log`.

**Comment by standage** [comment]
Auto-generating a change log from commits issues, and/or PRs would require a bit more structure in corresponding messages. I'm -1 on this.

I think we're just fine dropping the change log, and that we're honoring any obligations we have to users/developers/packagers by adhering to semantic versioning and providing curated release notes.

**Comment by ctb** [comment]
TANSTAAFL - we ditched on cleaning up our merges (for good reasons), but
as a result many of our git commit messages are not that useful :).

IMO, it would be useful to have a list of PRs that are delta between each
release, and maybe this could be autogenerated and stuck in a developer-facing
docment.

**Comment by betatim** [comment]
> IMO, it would be useful to have a list of PRs that are delta between each
release, and maybe this could be autogenerated and stuck in a developer-facing
docment.

Looks like https://skywinder.github.io/github-changelog-generator/#params can do this. You'd turn off everything but PRs

Opinions on doing some of the curating as we go along already? I am thinking of something [like this](https://github.com/scikit-learn/scikit-learn/blob/master/doc/whats_new.rst) to which people tend to add a line when they do a "big thing". There must also be some hand crafting by the maintainers as I don't remember ever adding myself to it, but my name appears. The main point here is that you try and keep it semi up to date as you go along.
