### ISSUE TITLE
screed.Record(..., quality=None) should not set 'quality'

### ISSUE THREAD

**Issue by ctb** [dib-lab/khmer#1468]
Right now, you can't pass 'None' in with 'record' in order to create a Record without a quality entry. Should be able to.

**Comment by luizirber** [comment]
When you create a new Record like this:
```python
>>> screed.Record(name="test", sequence="ACGT", quality=None)
```
the result should be:
1. `{'name': 'test', 'sequence': 'ACGT', 'quality': None}`
2. `{'name': 'test', 'sequence': 'ACGT', 'quality': ""}`
3. `{'name': 'test', 'sequence': 'ACGT'}`

`1` is the current result, `2` is consistent with `khmer.ReadParser`.

**Comment by ctb** [comment]
I think #3 personally.  We use hasattr(r, 'quality') throughout the current
codebase.

**Comment by luizirber** [comment]
Then we have a conflict with https://github.com/dib-lab/khmer/issues/1484, I had the impression we should keep an empty `quality` attribute?

**Comment by ctb** [comment]
Well, umm, I think (3) personally. Which fits with a lot of existing Python code. *shrug* It's up for discussion.

**Comment by luizirber** [comment]
I agree with `3`, but we need to discuss how similar we want both `screed.Record` and `khmer.Read` to be, and if we should then remove the `quality` attribute from `khmer.Read` if it doesn't have quality.

**Comment by ctb** [comment]
On Thu, Oct 06, 2016 at 05:36:04PM -0700, Luiz Irber wrote:
> I agree with `3`, but we need to discuss how similar we want both `screed.Record` and `khmer.Read` to be, and if we should then remove the `quality` attribute from `khmer.Read` if it doesn't have quality.

Yes, see #769.  I personally think that the Python code is more likely to
reflect good syntax/use because it's easier to change, so would go with
screed's approach. But then again I've had more of a hand in screed's approach,
so that's probably to be expected....

Are there any drawbacks to the approach?

**Comment by betatim** [comment]
I think we can make `khmer.ReadParser` behave like option 3. I'd start with adding https://docs.python.org/3/c-api/typeobj.html#c.PyTypeObject.tp_getattro to the `Read` type that checks if the stored string is "" or not to decide.

**Comment by ctb** [comment]
This already works, c.f. #1559.
