### ISSUE TITLE
Refactor test code to use load_nodegraph/load_countgraph

### ISSUE THREAD

**Issue by ctb** [dib-lab/khmer#1474]
(Update of #445)

In test_countgraph.py and test_nodegraph.py, a bunch of tests first create the object and then use obj.load(...) to load from a file.  These should be replaced with the newer library calls `khmer.load_nodegraph(...)` and `khmer.load_countgraph(...)`.

**Comment by shannonekj** [comment]
Is this still open? If so, I would like to work on it

**Comment by standage** [comment]
Hack away!

**Comment by standage** [comment]
Fixed in #1510.
