### ISSUE TITLE
Go through issues for milestone 2.0 before and reassign/update/close.

### ISSUE THREAD

**Issue by ctb** [dib-lab/khmer#1475]
We should close off milestones that we've already released :)

Might also want to take a closer look at milestone 2.0+.

**Comment by betatim** [comment]
Can we close https://github.com/dib-lab/khmer/milestone/11? I like virtualenvs/conda so I am -0 on system packaging stuff. Do people still use them/rely on them to get stuff installed?

**Comment by standage** [comment]
As of our last discussion, we agreed that:

1. we don't want to explicitly provide system packaging
2. we don't want to actively hinder anybody with an interest in implementing system packaging for us

With that in mind, I'd say there's no need to close the issue itself, but I'm on board with unassigning/reassigning and closing the 2.0 milestone.

**Comment by standage** [comment]
Just closed the 2.0 milestone.

**Comment by ctb** [comment]
:+1:
