### ISSUE TITLE
Screed 1.0 Release

### ISSUE THREAD

**Issue by luizirber** [dib-lab/khmer#1478]
- There is a [milestone](https://github.com/dib-lab/khmer/milestone/15) for the Screed 1.0 release, do we want to add more issues?
  - [All screed issues](https://github.com/dib-lab/khmer/issues?q=is%3Aopen+is%3Aissue+label%3Ascreed)
- Need to be merged:
  - [x] [Fix operator comparison](https://github.com/dib-lab/screed/pull/48)
  - [x] [Build improvements](https://github.com/dib-lab/screed/pull/49)

Blockers (need discussion):
- `screed.Record` and `khmer.Read` attributes: they are inconsistent now, how similar should they be (and which one is the reference?) - See https://github.com/dib-lab/khmer/issues/1484#issuecomment-252086265 and https://github.com/dib-lab/khmer/issues/1468#issuecomment-252090257 for examples)

cc @ctb @standage @betatim

**Comment by ctb** [comment]
Issues added to milestone; I think that's most of 'em.

**Comment by ctb** [comment]
We should also link to this blog post in the documentation: http://ivory.idyll.org/blog/storing-and-retrieving-sequences.html

**Comment by betatim** [comment]
Just closed #1484

**Comment by standage** [comment]
1.0 just released!
