### ISSUE TITLE
we should add FASTA and FASTQ string output on screed records

### ISSUE THREAD

**Issue by ctb** [dib-lab/khmer#1481]
basically, the equivalent of write_record from khmer.utils

**Comment by standage** [comment]
Relevant: `ToFasta` and `ToFastq` functions in `screed/conversion.py` module. These are tooled to operate on DBs and not records, so we'll have to refactor so we have Fastx output implemented in a single place.

**Comment by ctb** [comment]
On Fri, Oct 07, 2016 at 11:34:45AM -0700, Daniel Standage wrote:
> Relevant: `ToFasta` and `ToFastq` functions in `screed/conversion.py` module. These are tooled to operate on DBs and not records, so we'll have to refactor so we have Fastx output implemented in a single place.

It's totally ok to move or rename these; very little of screed apart from
screed.open and Record are used anywhere.

**Comment by standage** [comment]
And there's also `screed.fasta.FASTA_Writer` and `screed.fastq.FASTQ_Writer`, which inherit from `screed.screedRecord._Writer`.

:-/

**Comment by standage** [comment]
The `_Writer` class handles compressed output, which might be nice to keep around, even if khmer doesn't use it directly.

**Comment by ctb** [comment]
I don't think anything uses these.
