### ISSUE TITLE
how do you create screed DBs programatically?

### ISSUE THREAD

**Issue by ctb** [dib-lab/khmer#1482]
there should be a simple API that doesn't require running 'python -m screed.fqdbm'.  Also, we should make it so that there's a single command that creates the database from whatever (fq/fa etc.)

**Comment by luizirber** [comment]
The simple API in this case is `read_fasta_sequences` or `read_fastq_sequences`, no?

**Comment by ctb** [comment]
with 'screed.open' sniffing functionality we no longer need to specify file
type.

**Comment by ctb** [comment]
Any objections to the command line API:

```
python -m screed
```

and the Python API:

```
screed.makedb(filename)
```
?

**Comment by standage** [comment]
> python -m screed

As in `python -m screed myreads.fq`?

**Comment by ctb** [comment]
On Mon, Dec 19, 2016 at 12:30:40PM -0800, Daniel Standage wrote:
> > python -m screed
> 
> As in `python -m screed myreads.fq`?

yep

**Comment by standage** [comment]
I like

**Comment by luizirber** [comment]
Agree with Python API, but `python -m screed` might be confusing for other functionality in the module (like `dump_to_fast*`)

**Comment by luizirber** [comment]
About `screed.makedb`: name it `screed.make_db` instead, to be consistent with `create_db`?

**Comment by luizirber** [comment]
Fixed by dib-lab/screed#55
