### ISSUE TITLE
Add a demo script showing exact counting via Python API

### ISSUE THREAD

**Issue by ctb** [dib-lab/khmer#1486]
```
#! /usr/bin/env python       
# count-exact.py: demonstration of exact k-mer counting                                              
import khmer

# note: size 4**6 allows exact counting
# also note: forward and reverse complement will be collapsed.
cg = khmer.Countgraph(6, 4**6, 1)

cg.count('ATGGCA')
cg.count('ATGGCA')
cg.count('ACATGG')
cg.count('AAAAAA')
cg.count('TTTTTT') # this will be counted towards AAAAAA

for i in range(0, 4**6):
    if cg.get(i):
        print(cg.reverse_hash(i), cg.get(i))
```

**Comment by standage** [comment]
As is this script reports a single false positive: GGGGGT with abundance 2. Changing the size of the countgraph doesn't help: it simply reports a different false positive k-mer. Only by increasing the number of tables do we eliminate the false positive.

Swapping the countgraph for a counttable (as is used in the C++ API example) eliminates the false positive.

A bug in the countgraph implementation perhaps?
