### ISSUE TITLE
Split _khmer.cc up using #includes

### ISSUE THREAD

**Issue by ctb** [dib-lab/khmer#1497]
_khmer.cc is getting increasingly unwieldy. I found myself dreaming of cython this morning... but, in the meantime, what do people think about splitting it up into multiple different source files that are all included in _khmer.cc?

@luizirber @camillescott @betatim @standage

**Comment by standage** [comment]
This could make it much more digestible. A while back I even contemplated trying this myself, but couldn't ever convince myself to take the plunge. On the other hand, I really like the idea of Cython, but only have a superficial understanding of the trade-offs between Cython's concise syntax and CPython's flexibility.

**Comment by betatim** [comment]
I like it. Something like having one file for each type would be nice.
Off the top of my head I can't think of any drawbacks...

**Comment by ctb** [comment]
Started in #1504, will likely be continued until mass Cythonization happens in which case all is moot.
