### ISSUE TITLE
Implement k-mer Hash Caching

### ISSUE THREAD

**Issue by emcd** [dib-lab/khmer#15]
ctb had voidptr work on this at one point. Based on skimming her code, I do not think that we would want to spend too much time trying to integrate her implementation into the existing code base. However, this aspect of the software's performance is very important and implementing hash caching is potentially a huge win for us. A natural point to consider implementing this is during a redesign/reimplementation of the Bloom filter.

Ideally, we should try to finish this before the POSA book is published, since we alluded to working on it.

**Comment by ctb** [comment]
I think the original idea here is one that is referenced in https://github.com/dib-lab/khmer/pull/1553#issuecomment-266811926 -
```
You could keep a cache
of things to insert into the bloom filters, tho, organized by location in
filter, and then flush from there periodically.
```
Our tentative decision there is that other data structures have come along that promise better cache locality, such as cuckoo filters, so I will close this.
