### ISSUE TITLE
Check examples and lib/Makefile regularly

### ISSUE THREAD

**Issue by ctb** [dib-lab/khmer#1514]
add examples/c++-api and lib/Makefile to our continuous integration, maybe?

(the former uses the latter, note)

**Comment by betatim** [comment]
What is `lib/Makefile` used for? been wondering that for a while but never asked...

**Comment by ctb** [comment]
On Thu, Nov 17, 2016 at 04:25:31AM -0800, Tim Head wrote:
> What is `lib/Makefile` used for? been wondering that for a while but never asked...

building liboxli for people who want to use the C++ non-API.

**Comment by standage** [comment]
See #1364. We could easily add a few simple examples to test the most commonly used components.
