### ISSUE TITLE
Migrate screed and issue tracking

### ISSUE THREAD

**Issue by standage** [dib-lab/khmer#1521]
The current structure of the screed repos is full of vestiges. The "main" repository is dib-lab/screed, but this is a fork of ctb/screed which AFAICS isn't touched anymore. As a result, we can't track issues in dib-lab/screed: perhaps this is why screed issues are tracked in the khmer repo?

I propose the following.

- Make dib-lab/screed the primary repo. <small>I don't know if it would be better to update ctb/screed and then migrate to dib-lab/screed, or if there's a different/better way. I've migrated personal repos to group repos before, and it's pretty painless.</small>
- Use dib-lab/screed to keep track of (future) screed issues.

**Comment by ctb** [comment]
> - Make dib-lab/screed the primary repo. <small>I don't know if it would be better to update ctb/screed and then migrate to dib-lab/screed, or if there's a different/better way. I've migrated personal repos to group repos before, and it's pretty painless.</small>

+1

> - Use dib-lab/screed to keep track of (future) screed issues.

-0. by far the primary use of screed is in khmer, and the issues are
often linked.  (that's why we track screed issues in khmer.)

when screed reaches 1.0 we can revisit, but I don't expect screed to
evolve much independently of khmer.

**Comment by ctb** [comment]
I think I need to submit a GitHub support request to ask them to make dib-lab/screed the "one true parent" of all screed forks. Sound good?

**Comment by standage** [comment]
👍

**Comment by ctb** [comment]
Submitted request.

**Comment by ctb** [comment]
@standage they said it's all good - can you confirm? I'm going to go have lunch instead :)

**Comment by standage** [comment]
Rejoice, for it is done!
