### ISSUE TITLE
Duplicate filenames with diginorm script

### ISSUE THREAD

**Issue by standage** [dib-lab/khmer#1532]
The `normalize-by-median.py` script complains if two input files have the same basename. Consequently two different files such as `dir1/reads.fastq` and `dir2/reads.fastq` cannot be handled by the same call to `normalize-by-median.py`.

This came up in testing (cc @NBKingsley), but it was easy to address on the testing side. I'm guessing the reason this isn't currently supported on the script side is the requirement for diginorm to make temp files based on file basenames. Would this be a straightforward fix, and is it worth our time pursuing?

**Comment by ctb** [comment]
On Wed, Nov 16, 2016 at 12:05:00PM -0800, Daniel Standage wrote:
> The `normalize-by-median.py` script complains if two input files have the same basename. Consequently two different files such as `dir1/reads.fastq` and `dir2/reads.fastq` cannot be handled by the same call to `normalize-by-median.py`.
> 
> This came up in testing (cc @NBKingsley), but it was easy to address on the testing side. I'm guessing the reason this isn't currently supported on the script side is the requirement for diginorm to make temp files based on file basenames. Would this be a straightforward fix, and is it worth our time pursuing?

The default output file names are generated from the input files, which
is part of the problem. I don't personally view it as a big concern.
But, you could relax that constraint when a -o is specified, for example.

**Comment by standage** [comment]
👍
