### ISSUE TITLE
Flesh out khmer public info re libraries.io

### ISSUE THREAD

**Issue by ctb** [dib-lab/khmer#1535]
At https://libraries.io/pypi/khmer I note that it misses a lot of things. I wonder why?

**Comment by betatim** [comment]
Not sure how to influence what is displayed. For example https://libraries.io/pypi/scikit-learn links to the GitHub repository but the khmer page doesn't nor does the scikit-optimize page on libraries.io.

Was expecting to find a magic link to the sklearn github in their `setup.py` but that isn't where libraries.io gets it from.

**Comment by betatim** [comment]
Seems like the way to go is to ask via twitter: https://twitter.com/teabass/status/855384812202459136 :-/

**Comment by betatim** [comment]
check out https://libraries.io/pypi/khmer I used my considerable twitter influencing skills :)
