### ISSUE TITLE
HLLCounter() objects evaluate to False

### ISSUE THREAD

**Issue by ctb** [dib-lab/khmer#1543]
```
hll = khmer.HLLCounter()
if not hll: print('hll is False')
```

Presumably this is because `len` is not implemented; I think `len` should probably be the same as `estimate_cardinality()`. Thoughts?

**Comment by standage** [comment]
Seems like this should be a simple fix we can squeeze in with 2.1.

**Comment by betatim** [comment]
This got fixed already in b4390769
