### ISSUE TITLE
Continued Travis OSX outage

### ISSUE THREAD

**Issue by betatim** [dib-lab/khmer#1550]
[Travis OSX builds are unusable](https://www.traviscistatus.com/incidents/nq0sf0srvx8s) and have been for a while. This effects us as we declared the OSX build as the"authority" on coverage. Currently all OSX builds are halted, do we think this is going to get cleared up any time soon or should we modify our travis setup to make the linux build the authority (might cause intermittent weirdness for coverage reports) and mark the OSX build as "can fail".

(Right now we aren't accumulating (at tremendous speed) a backlog of PRs that are ready to merge and not getting merged only because of travis. So we can wait&see for a bit longer.)

**Comment by ctb** [comment]
Why would using linux the authority for builds cause intermittent weirdness
on coverage reports?

**Comment by betatim** [comment]
Not sure TBH. Might be that it was just `make format` that I couldn't get to behave exactly the same on the two OSes.
