### ISSUE TITLE
Figure out correct instructions for turning off RC collapsing

### ISSUE THREAD

**Issue by ctb** [dib-lab/khmer#1552]
See http://lists.idyll.org/pipermail/khmer/2016-December/000775.html for where NO_UNIQUE_RC hack doesn't work.

**Comment by standage** [comment]
The proper long-term fix is a user-selectable strand-specific hash function, but (if I understand correctly) you used to be able to disable reverse complement collapsing using C++ #defines?

**Comment by betatim** [comment]
From the email it sounds like what doesn't work is the forwarding/setting of `NO_UNIQUE_RC` from" outside. If you do what the preprocessor should do by hand it still works.

**Comment by betatim** [comment]
The solution seems to be to edit `setup.cfg`

```diff
--- a/setup.cfg
+++ b/setup.cfg
@@ -1,6 +1,6 @@
 [build_ext]
-define = SEQAN_HAS_BZIP2,SEQAN_HAS_ZLIB
-undef = NO_UNIQUE_RC
+define = SEQAN_HAS_BZIP2,SEQAN_HAS_ZLIB,NO_UNIQUE_RC
+#undef = NO_UNIQUE_RC
```

which suggests that [this bit of Makefile](https://github.com/dib-lab/khmer/blob/master/Makefile#L52-L53) doesn't actually get used?

**Comment by betatim** [comment]
Ah, except for `cppcheck`. Any ideas on how we can get rid of this duplication?

**Comment by standage** [comment]
This was closed automatically by #1681, but that PR didn't actually solve this issue did it?

**Comment by betatim** [comment]
The comment in the `Makefile` should point you to the right place, and if you edit `setup.cfg` the #define works for compiling khmer itself. But I didn't check what happens for the cpp-demo which  use `lib/Makefile`. The way I understood the linked email the original question was about changing NO_UNIQUE_RC  for the shared library. The original poster was editing `lib/Makefile` which is (I think) the wrong place to be editing. Which makes me wonder why NO_UNIQUE_RC  features there at all :-/

**Comment by standage** [comment]
My mistake, I didn't read the backstory in enough detail.
