### ISSUE TITLE
Normalize copyright/license notices for screed

### ISSUE THREAD

**Issue by standage** [dib-lab/khmer#1562]
This is pretty inconsistent throughout the codebase, even in `screed/*.py`. Some files have a line or two at the top claiming copyright, and many have none. There may be places in the code with copyright and license information. We should normalize all of this. A few things to consider, with my biases throw in for good measure.

- Should we place a copyright notice at the top of each code file?
    - I suggest yes, adding UC 2016 as the first claim of copyright for files missing the notice.
- Should we declare a range of copyright years?
    - I suggest no, this is unnecessary. For files with 2008-2012 MSU, I suggest trimming to 2008. The initial copyright claim is all that's important.
- Should we place a license notice at the top of each code file?
    - I'm -0 on this. I'm not opposed to this, but since it's not already there I'm not eager to add it in without a compelling reason.

Thoughts? @luizirber @ctb @betatim

**Comment by ctb** [comment]
On Tue, Dec 20, 2016 at 01:17:14PM -0800, Daniel Standage wrote:
> This is pretty inconsistent throughout the codebase, even in `screed/*.py`. Some files have a line or two at the top claiming copyright, and many have none. There may be places in the code with copyright and license information. We should normalize all of this. A few things to consider, with my biases throw in for good measure.
> 
> - Should we place a copyright notice at the top of each code file?
>     - I suggest yes, adding UC 2016 as the first claim of copyright for files missing the notice.

sure

> - Should we declare a range of copyright years?
>     - I suggest no, this is unnecessary. For files with 2008-2012 MSU, I suggest trimming to 2008. The initial copyright claim is all that's important.

agree

> - Should we place a license notice at the top of each code file?
>     - I'm -0 on this. I'm not opposed to this, but since it's not already there I'm not eager to add it in without a compelling reason.

agree not

--t

**Comment by standage** [comment]
Closed by https://github.com/dib-lab/screed/pull/57.
