### ISSUE TITLE
as part of PR checklist, should we ask new authors to supply their ORCID?

### ISSUE THREAD

**Issue by ctb** [dib-lab/khmer#1564]
may be overkill, but worth a thought for all our software projects.

**Comment by standage** [comment]
Perhaps add a `CONTRIBUTORS` file and add something like this to the PR checklist:

```
- [ ] If you would like to be included in publications describing khmer,
      is your name/email/ORCID ID included in `CONTRIBUTORS`?
```

**Comment by betatim** [comment]
How often does a new contributor come along? If it is rarely I would be -0 on having an extra line in the PR template that we need to delete/ignore on every PR made by a not first timer (long checklists full of "noise" are tempting to ignore completely...). We could add it to the "First contrib to khmer" docs though. Together with a link to "create ORCID ID" and a brief explanation why this would immensely help the maintainers out.

**Comment by ctb** [comment]
I like your suggestion, @betatim.

**Comment by standage** [comment]
Yeah, now that you mention I think Michael had a first-time contributor message once someone's first PR was merged. If that's not already in the docs we could add it.

**Comment by standage** [comment]
We should put this in the developers documentation...or create a new section for maintainer tasks/SOPs.
