### ISSUE TITLE
Implement a new 'consume' method that only stores a fraction of the observed k-mers

### ISSUE THREAD

**Issue by standage** [dib-lab/khmer#1570]
I'm proposing a new method for the (count|node)(table|graph) classes that will deterministically consume only a fraction of the k-mers observed in the reads processed. The basic idea is to use some property of the k-mer's hashed value to split it into multiple (roughly equally sized) bins, so that those bins can be analyzed independently with much lower memory requirements. The simplest approach would be to just split up the hashed values using a modulus, but this is expensive to compute. An alternative approach would be to split on the first few or last few nucleotides (which depending on the hash function used might require discarding k-mers before hashes are computed), but some prefixes/suffixes are much more abundant than others (for example, A-rich sequences in human). It would probably be best to split into 2^n bins by looking at the value encoded in the n least significant bits of the hashed k-mer.

I would suggest a Python interface like this.

```python
cg = khmer.Countgraph(31, 1e9, 4)
# consume only k-mers with 0011 as their last 4 bits
cg.consume_fasta_bitsplit('reads.fq', 16, 3)
```

**Comment by ctb** [comment]
Note, this will only be of use for "good" hash functions (not our current
default).

**Comment by standage** [comment]
Yes, the current 2-bit encoding will be biased by sequence content.

**Comment by standage** [comment]
Ok, this will be some fun engineering. Calling `Hashtable::consume_fasta` invokes the following call stack.

```
Hashtable::consume_fasta -->
    Hashtable::check_and_process_read -->
        Hashtable::check_and_normalize_read -->
            Hashtable::consume_string
```

So one question is whether it's best to duplicate these functions for the proposed behavior, or to extend the existing functions (with default parameters to preserve backwards compatibility), or some other strategy.

**Comment by standage** [comment]
The `consume_string` function is where all the proposed action would be happening, but how to get the parameters to that function?
