### ISSUE TITLE
Minimum GCC requirements should be documented

### ISSUE THREAD

**Issue by ctb** [dib-lab/khmer#1574]
See: https://github.com/dib-lab/sourmash/issues/98#issuecomment-272892910

**Comment by betatim** [comment]
As I don't know the explicit minimum version, here an overview of what I found:

On travis linux we use gcc-4.8.4, https://gcc.gnu.org/projects/cxx-status.html#cxx11 says that 4.8.1 was the first version to fully support c++11. AFAIK we don't use any nasty hacks, just c++11.

**Comment by standage** [comment]
Fixed in #1600.
