### ISSUE TITLE
Code obfuscation ?

### ISSUE THREAD

**Issue by lgautier** [dib-lab/khmer#1577]
Just writing it down for the next code cleanup. Three lines are in `openscreed.py` require quite a bit of attention from a reader of the code:

https://github.com/dib-lab/screed/blob/master/screed/openscreed.py#L116

```python
_open = open
open = Open
open_reader = open
```

**Comment by luizirber** [comment]
That's backward compatibility, I guess we could clean it up for 1.0...

**Comment by ctb** [comment]
See dib-lab/screed#65.

**Comment by ctb** [comment]
Fixed in latest master for screed.

**Comment by lgautier** [comment]
Thanks on behalf of future readers of that portion of the code. ;-)
