### ISSUE TITLE
merge-partitions.py terminates with 'std::ios_base::failure'

### ISSUE THREAD

**Issue by jvollme** [dib-lab/khmer#1580]
Hi,
I am trying to apply your partitioning workflow to a large and complex read dataset. 
I started by building the graph with "load-graph.py" using forward and reverse reads in seperate files:

`load-graph.py -k 32 -N 4 -x 128e9 -T 4 trimmed_paired_loadedgraph ../../trimming/151014/TRIMMED_paired_JP02-MFM_CTTGTA_L008_R1_001.fastq.gz ../../trimming/151014/TRIMMED_paired_JP02-MFM_CTTGTA_L008_R2_001.fastq.gz`
This completed without errors. Then I partitioned the graph with partition-graph.py:
`partition-graph.py -s 1e5 -T 8 trimmed_paired_loadedgraph`
This also completed without errors and resulted in 1880 ".pmap"-files
However, when I try to run "merge-partitions.py", I keep getting this error message:
```
>>merge-partitions.py trimmed_paired_loadedgraph
|| This is the script merge-partitions.py in khmer.
|| You are running khmer version 2.0
|| You are also using screed version 0.9
||
|| If you use this script in a publication, please cite EACH of the following:
||
||   * MR Crusoe et al., 2015. http://dx.doi.org/10.12688/f1000research.6924.1
||   * J Pell et al., http://dx.doi.org/10.1073/pnas.1121464109
||
|| Please see http://khmer.readthedocs.org/en/latest/citations.html for details.

loading 1880 pmap files (first one: trimmed_paired_loadedgraph.subset.57.pmap)
merging trimmed_paired_loadedgraph.subset.57.pmap
terminate called after throwing an instance of 'std::ios_base::failure'
  what():  basic_ios::clear
/var/spool/slurm/slurmd/job349222/slurm_script: line 6: 46222 Aborted
```
What am I doing wrong here?

**Comment by betatim** [comment]
Can reproduce this with:
```
load-graph.py -k 23 -N 4 -x 12e7 graph tests/test-data/random-20-a.fa; partition-graph.py -s 1e1 graph;merge-partitions.py -k 23 graph
```
with khmer2.0. On `master` the same command works for k=23 but breaks with k>23. Different looking error message:
```
Traceback (most recent call last):
  File "/home/thead/anaconda/bin/merge-partitions.py", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/thead/git/dib/khmer/scripts/merge-partitions.py", line 111, in <module>
    main()
  File "/home/thead/git/dib/khmer/scripts/merge-partitions.py", line 99, in main
    nodegraph.merge_subset_from_disk(pmap_file)
OSError: Unknown error reading data from: graph.subset.0.pmap
```
I will take a look.

**Comment by betatim** [comment]
@jvollme could you share one of the pmap files with me?

**Comment by betatim** [comment]
With the command above I end up with pmap files that are 18bytes large, which means they are empty. Seems like loading those back in crashes. Would be god to confirm if this is the source of your problem as well. `ls -hals *pmap` to see the size of your files.

**Comment by jvollme** [comment]
I've uploaded a list of the pmap filesizes here: [pmap_filesizes.txt](https://github.com/dib-lab/khmer/files/723814/pmap_filesizes.txt)
They are all >1MB, so there do not appear to be any empty files.

Since the script _seems_ to abort at "trimmed_paired_loadedgraph.subset.57.pmap", I've also uploaded this file, as well as an additional one. However, since these filetypes are not supported by GitHub, I've uploaded them via these Dropbox downloadlinks:

[trimmed_paired_loadedgraph.subset.0.pmap](https://www.dropbox.com/s/hxfa7cln0r8z2y5/trimmed_paired_loadedgraph.subset.0.pmap?dl=0)
[trimmed_paired_loadedgraph.subset.57.pmap](https://www.dropbox.com/s/2qqcuyow24havuc/trimmed_paired_loadedgraph.subset.57.pmap?dl=0)

**Comment by betatim** [comment]
With khmer2.0 I also get an error when merging these two pmaps. However with `master` the files get merged.

Could you try on your end with khmer `master` as well?

**Comment by jvollme** [comment]
Ok, but could you help me how to best change to master?
I originally installed the khmer-suite under my virtualenv using `pip install khmer`.
Will `pip install --upgrade khmer` upgrade it to the current master? Or isn't that an official release yet?

**Comment by betatim** [comment]
Create a new virtualenv so we don't break anything in your existing setup. Once you have the new virtualenv and have activated it, `cd` to a directory that doesn't already contain a `khmer` subdirectory and:
```
$ git clone https://github.com/dib-lab/khmer
$ cd khmer
$ make install
$ cd somewhere/else
$ python # try: import khmer
```
Let me know if that works.

**Comment by jvollme** [comment]
Sorry for my late reply, 
using the current master-branch seems to work now, thanks. pmap-files are currently being merged. Does this mean you'll be doing a new release soon?

**Comment by betatim** [comment]
Jupp, v2.1 is pretty close to being ready.

**Comment by jvollme** [comment]
The merging step has completed without error now, so the master-branch is definitively working.
Thanks!
