### ISSUE TITLE
Clean up `check_space`

### ISSUE THREAD

**Issue by standage** [dib-lab/khmer#1585]
In #1549, the `check_space_for_graph` function was cleaned up a bit. The `check_space` function should be cleaned up in a similar way.

**Comment by souravsingh** [comment]
@standage I am interested in working on this. We have to clean up the print statements from the function, correct?

**Comment by ctb** [comment]
yes, @souravsingh - thx!

**Comment by standage** [comment]
Fixed in #1813.
