### ISSUE TITLE
How to best apply the partitioning pipeline to a mixture of paired & unpaired reads

### ISSUE THREAD

**Issue by jvollme** [dib-lab/khmer#1588]
Hi,
I'm not sure how exactly the scripts of the partitioning-workflow treat read-pairs. It seems that arguments ,which specify how read-pairs should be treated, only exist for the normalization-workflows?

e.g. load-graph.py (the first step of the partitioning workflow) accepts one or multiple input files. If I use multiple input files, will the script automatically assume paired-end reads in separate files (forward reads in the first, reverse reads in the second file)? Will it automatically assume interleaved reads if i only supply one input file?

What would happen if i used a mixture of paired and unpaired files as input, and in which form should i best do that? (after quality trimming I have left-over "orphaned" reads, which have "lost" their respective partner. Also for some libraries, the insert size was rather small so that the read-pairs overlapped, enabling me to merge them into longer unpaired reads before assembly). 

In which form will the partitioned reads be output? Automatically Interleaved? Or possibly first all forward reads and then all reverse reads (requiring another processing step before assembly of paired reads)?

**Comment by ctb** [comment]
Hi John,

partition is somewhat deprecated.  The code is still useful but for high
coverage data sets it just doesn't work very well -- see:

http://ivory.idyll.org/blog/2016-partitioning-no-more.html

so I can answer your questions for posterity but I wouldn't recommend using
it :)

The basic problem is that partitioning is unaware of read pairing.

On Tue, Jan 24, 2017 at 02:55:58AM -0800, JohnVollmers wrote:
> Hi,
> I'm not sure how exactly the scripts of the partitioning-workflow treat read-pairs. It seems that arguments which specify how read-pairs should be treated only exist for the normalization-workflows?

Thta's right.

> e.g. load-graph.py (the first step of the partitioning workflow) accepts one or multiple input files. If I use multiple input files, will the script automatically assume paired-end reads in separate files (forward reads in the first, reverse reads in the second file)? Will it automatically assume interleaved reads if i only supply one input file?

Paired reads are not taken into account in partitioning.

> In which form will the partitioned reads be output? Automatically Interleaved? Or possibly first all forward reads and then all reverse reads (requiring another processing step before assembly of paired reads)?

The partitioned reads will be output in the order they're input, split amongst
files by partitions.

**Comment by jvollme** [comment]
ok thanks. Actually the fact that the partitioning is not read-pair aware should not be that much of a problem. I can recover the pairs and orphans from the respective partitions later. It's just good to know.
 
I am aware that Titus brown does not generally recommend diginorm and partitioning for metagenomes anymore, but I'm pretty sure it will prove to be very useful for my task (however, without diginorm).

I am targeting a very low abundant genome from a highly complex and low coverage dataset and have high hopes in a custom workflow which includes the khmer partitioning step as one of multiple components.

**Comment by ctb** [comment]
cool! let us know how it goes! (I'm Titus, BTW.)
