### ISSUE TITLE
Digital normalization on technical replicates

### ISSUE THREAD

**Issue by domenico-simone** [dib-lab/khmer#1594]
Hello,

I would like to perform digital normalization for a huge metatranscriptome dataset (2x125bp). Indeed I have two technical replicates (that I usually co-assemble since they come from the same biological replicate) which were "separated" after the library preparation. Would you recommend to pool the technical replicates before performing the diginorm or after?

Thanks,
Domenico

**Comment by ctb** [comment]
Before! Diginorm together everything that you will assemble together.

best,
--titus

**Comment by domenico-simone** [comment]
Hi Titus,

thanks for your reply. Do you have any best practice to suggest for this kind of dataset?

Thanks,
Domenico

**Comment by ctb** [comment]
Mmmh... a few different people have done things with metatranscriptomes,
and as far as I can tell there's nothing special to be done.  My suggestion
is actually to just use megahit (without using khmer); I believe that's
what JGI is using these days, and at least on metagenomes, megahit performs
superbly.

http://ivory.idyll.org/blog/2014-how-good-is-megahit.html#comment-1796370402

**Comment by domenico-simone** [comment]
Thanks Titus, I'll give a shot to MEGAHIT as well to see how they compare.

Best,
Domenico
