### ISSUE TITLE
normalize-by-median.py bad result

### ISSUE THREAD

**Issue by domenico-simone** [dib-lab/khmer#1606]
Hello,

I've been trying `normalize-by-median.py` with a metatranscriptomic dataset with both PE and SE reads. PE reads are 2 x 35,874,838, with length ranging from 100 to 126. SE reads are 41364126, with length ranging from 100 to ~200 (they include also merged PE reads). Checking with the tutorial at http://ged.msu.edu/angus/diginorm-2012/tutorial.html, I run the following command line with the following k values: 20, 24, 28, 32 (I tried to further increase but I got an error). 

```
normalize-by-median.py \
-k ${k} \
-N 4 \
-C 20 \
-p \
-u sample_SE.fastq \
-s sample.C20_k20_N4_test.ct \
-R sample.C20_k20_N4_report \
sample_PE.fastq
```

All the runs actually fail, with a message like this:

```
... in file sample_SE.fastq
... kept 330 of 41200000 or  0%
... in file sample_SE.fastq
... kept 332 of 41300000 or  0%
... in file sample_SE.fastq
DONE with sample_SE.fastq; kept 333 of 41364126 or  0%
output in sample_SE.fastq.keep
**
** ERROR: the graph structure is too small for 
this data set.  Increase k-mer presence table 
size/num of tables.
** Do not use these results!!
**
slurmstepd: error: Exceeded step memory limit at some point.
```

I see there is an extremely low number of reads kept, but it's not clear to me if the problem is due either to the warning about the graph structure or the memory limit. For each run I am using 8gb of memory (which is the core size available), I have also the option to get bigger cores but, based on the documentation and the tutorials, 8gb seems quite reasonable to me. What could be a workaround to this problem?

Thanks

Regards,
Domenico

**Comment by ctb** [comment]
Hi! More in a bit but you do not seem to be specifying a table size (-x) so it is probably using only a tiny amount of memory. Try removing the -N and adding -M 6e9 to use 6GB of memory.

--
Titus Brown, ctbrown@ucdavis.edu



--
Titus Brown, ctbrown@ucdavis.edu

**Comment by domenico-simone** [comment]
Hi,

thanks for the suggestion, indeed I couldn't setup that option because the khmer system-wide installation of the cluster I'm working on was version 1.4 (with neither -x nor -M options available).
However, I managed to get a new installation and run the script again with -M 6e9. This time I don't get the error about the graph structure (with a range of 6-20% of reads recovered), but still I get the error: `slurmstepd: error: Exceeded step memory limit at some point.`. I tried to set -M to 7.8e9 to try just a little below the maximum, but I get the same results with the same error.

I'm trying on my side to get from the cluster assistance deeper info about when the step memory was exceeded. Meanwhile, is there anything else I could try to sort this out?

Thanks,

Domenico

**Comment by ctb** [comment]
Hi Domenico,

-x was available since 1.0, so it should be there, although it seems
you've gotten past that :)

I did a bit of googling and found this --

https://github.com/chaos/slurm/issues/54

which fits what I think should be happening, which is that you're not
actually going over the memory limit.  So your results are probably
fine (or at least if you get to DONE then the script has not exited
badly!)  So I would just ignore it!

**Comment by domenico-simone** [comment]
Hi Titus,

> -x was available since 1.0, so it should be there, although it seems you've gotten past that :) 

whoops yes, my fault, sorry!

> So your results are probably fine (or at least if you get to DONE then the script has not exited badly!) So I would just ignore it!

I'm really happy for this suggestion :) As a remark, I would just point out that when I got the the error about the graph structure in my previous runs, I still got the DONE messages for both the PE and SE files.

Thanks

Domenico

**Comment by ctb** [comment]
On Tue, Feb 07, 2017 at 04:20:52PM -0800, Domenico Simone wrote:
> Hi Titus,
> 
> > -x was available since 1.0, so it should be there, although it seems you've gotten past that :) 
> 
> whoops yes, my fault, sorry!
> 
> > So your results are probably fine (or at least if you get to DONE then the script has not exited badly!) So I would just ignore it!
> 
> I'm really happy for this suggestion :) As a remark, I would just point out that when I got the the error about the graph structure in my previous runs, I still got the DONE messages for both the PE and SE files.

Good point... the error message from khmer did say something, but we could
remove the DONE...

Best of luck with your metatranscriptome!

**Comment by domenico-simone** [comment]
Hi Titus,

I got a reply from the cluster support. They said not to worry about the slurmstepd error message if both ExitCode and DerivedExitCodes of the jobs are 0. Should this be useful, here's a link they gave me as reference:

https://bugs.schedmd.com/show_bug.cgi?id=3214

Best,

Domenico

**Comment by ctb** [comment]
thank you!
