### ISSUE TITLE
Look into stale object files/header files

### ISSUE THREAD

**Issue by ctb** [dib-lab/khmer#1611]
@standage may have run into a problem with stale object files running an old version of a hash function.  We're not sure exactly what happened, but things to check --

* does `make clean` correctly remove all .o and .so files?
* does changing any header file result in recompilation of everything (as it seems), or are there new header files that have not been properly entered into setup.py?
* it seems unlikely that a virtualenv snafu could have led to this, but there are situations where multiple different installs can yield surprising imports based on how virtualenv installs stuff.
* it seems like setup.py installs stuff in the virtualenv even when we don't run `make install`. Is this intentional?

Perhaps we should create a debugging checklist with some sanity checks for when you think you might be going crazy:

* remove all installed khmer packages from your virtualenv;
* run tests on installed version (do we have docs for this?)

etc

**Comment by betatim** [comment]
After `make && make clean`:
```
$ find . -name "*.so"
$ find . -name "*.o"
```

not sure how to test the recompile on header change thing. If someone knows go ahead.
