### ISSUE TITLE
Make pytest work for pip installs

### ISSUE THREAD

**Issue by standage** [dib-lab/khmer#1646]
#1403 notes that we need to update our release checklist with respect to the nosetests/pytest replacement. We also need to update the install docs. More importantly, things don't currently seem to work properly, so additional configuration may be required.

```
$ pip install git+https://github.com/dib-lab/khmer.git
...
blah blah blah
...
$ pytest --pyargs khmer -m 'not known_failing and not jenkins and not huge and not linux'
=========================================================== test session starts ============================================================
platform darwin -- Python 3.5.2, pytest-3.0.4, py-1.4.31, pluggy-0.4.0
rootdir: /Users/standage, inifile:
plugins: cov-2.4.0
collected 0 items 

======================================================= no tests ran in 0.01 seconds =======================================================
$
```

**Comment by standage** [comment]
Replacing `khmer` with `khmer.tests` results in the following error.

```
ERROR: file or package not found: khmer.tests
```

**Comment by betatim** [comment]
For me `pip install git+https:/.....` in a new env leads to:
```
$ pytest -s --pyargs khmer -m 'not known_failing and not jenkins and not huge and not linux'                                                    (khmer-rc)
=================================================================== test session starts ===================================================================
platform linux -- Python 3.5.3, pytest-3.0.6, py-1.4.32, pluggy-0.4.0
rootdir: /tmp, inifile: 
collected 1255 items / 1 errors 

========================================================================= ERRORS ==========================================================================
____________________________________________________________________ ERROR collecting  ____________________________________________________________________
Using pytest.skip outside of a test is not allowed. If you are trying to decorate a test function, use the @pytest.mark.skip or @pytest.mark.skipif decorators instead.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
=================================================================== 25 tests deselected ===================================================================
========================================================= 25 deselected, 1 error in 0.64 seconds ==========================================================
```

**Comment by betatim** [comment]
If I create a fresh environment, clone master myself, `make install`, change directories to somewhere outside the repository then:
```
$ pytest --pyargs khmer.tests.test_sandbox_scripts -m 'not known_failing and not jenkins and not huge and not linux' 
```
runs but gives lots of failed tests because `runscript()` gets confused by the lower level that raises a `Skipped` exception.

**Comment by betatim** [comment]
Checking out #1649 via `pip install git+https://github.com/dib-lab/khmer.git@fix/sandbox-script-testing ` and then running the above `pytest` command in a fresh conda environment works for me now.

**Comment by betatim** [comment]
Was about to close this but tried to use it as part of going through the checklist and didn't work. 😕  Tim.

**Comment by betatim** [comment]
Seems like `pip install -e git+https://github.com/dib-lab/khmer.git` leads to `pytest --pyargs khmer -m 'not known_failing'` not finding the tests. Where as for `pip install git+https://github.com/dib-lab/khmer.git` it works.

**Comment by standage** [comment]
> Seems like pip install -e git+https://github.com/dib-lab/khmer.git leads to pytest --pyargs khmer -m 'not known_failing' not finding the tests

Do you consider this a blocker? Is this a common use case?

**Comment by betatim** [comment]
> Do you consider this a blocker? Is this a common use case?

I don't think so to both. Mostly just confused as to why the difference in behaviours.

However we never tell anyone to do this, and even if they do, they get the source code as part of running this command, so can `cd` there and run tests from there.

**Comment by betatim** [comment]
From my side the thing left to check is that your original report now no longer leads to no tests being run. Then we can close this.

**Comment by standage** [comment]
Works for py2 and py3 virtualenvs on my Macbook. Woot!
