### ISSUE TITLE
Should SmallCounttable behave like Counttable?

### ISSUE THREAD

**Issue by ctb** [dib-lab/khmer#1659]
Right now, SmallCounttable uses the k<32 / fully reversible hash function.  I think for name consistency it should behave like a Counttable (using murmurhash). Thoughts?

If desired, this could be done by copy/pasting the hashing code from Counttable, OR by deriving SmallCounttable from Counttable instead of from Hashtable.

**Comment by betatim** [comment]
From a technician POV I have no opinion on k<32 / irreversible. Does science have a preference? Otherwise let's switch.

**Comment by standage** [comment]
I agree the change makes sense from an internal consistency perspective.
