### ISSUE TITLE
command usage descriptions

### ISSUE THREAD

**Issue by kloetzl** [dib-lab/khmer#1676]
Going through the `--help` messages for the [zsh completion](https://github.com/kloetzl/biozsh/commit/1567b15e1d9f54c73f6ba98367f3e74077a6a487) I found a number of small issues.

* `abundance-dist-single`: `-f` and `-s` have the same description.
* `abundance-dist-single`: `--savegraph` has an empty default
* `do-partition`: `--keep-subsets` has two defaults.
* various: `--max-memory-usage` states that is is used for “maximum amount of memory to use for data structure”. The default is “None”, which can be read as “no memory”. A better description would be “unlimited”.
* In some cases the short option is given first, in others the long version. See `khmer extract-paired-reads --help` for `-d` and `-p`, resp.
* Some descriptions end with a full stop, others don't.
* `normalize-by-median`: `-q, -R, --report-frequency` are missing a description
* `normalize-by-median`: `-C` s/numer/number/
* `normalize-by-median`: `--force_single` is one of the very few option with an underscore
* `readstats` and `trim-low-abund` are missing multiple argument descriptions

Btw, can short options be stacked? May arguments to long options be given with a `=`?

**Comment by ctb** [comment]
wow, thank you!

On Tue, Apr 18, 2017 at 05:59:10AM -0700, Fabian Klötzl wrote:
> Btw, can short options be stacked? May arguments to long options be given with a `=`?

Yes; we use the argparse module in Python :)

**Comment by standage** [comment]
> `abundance-dist-single`: `-f` and `-s` have the same description.

True. We need to clarify that `-f` corresponds to `--savegraph` and `-s` corresponds to the output histogram file.

**Comment by standage** [comment]
> `abundance-dist-single`: `--savegraph` has an empty default

The empty default (at the code level) is intended: by default, the script does not save the graph. I agree that how this is reflected in the usage statement is sub-optimal though.

**Comment by standage** [comment]
> various: `--max-memory-usage` states that is is used for “maximum amount of memory to use for data structure”. The default is “None”, which can be read as “no memory”. A better description would be “unlimited”.

The `None` refers to the fact that, by default, this parameter is not set. There is no "unlimited" memory mode, the memory consumption is always the product of the `-N` and `-x` flags. The default for `-x` is deliberately small, and the `--max-memory-usage` flag is simply a convenience shortcut for setting `-x`. The [khmer user docs](http://khmer.readthedocs.io/en/v2.0/user/choosing-table-sizes.html) are pretty thorough in discussing memory settings.

Given all this, any suggestions about how the usage statement for this option could be clearer?

**Comment by standage** [comment]
> In some cases the short option is given first, in others the long version. See `khmer extract-paired-reads --help` for `-d` and `-p`, resp.

My impression is that this is for convenience and reflects legacy usage. Not really a *correctness* concern as much as a *style and consistency* concern. Does this make things like zsh completion difficult or impossible?

**Comment by standage** [comment]
Sorry for filling up your inbox with piecemeal responses. Thanks for your report, and we'll update this thread as we address the various issues here. Thanks!

**Comment by kloetzl** [comment]
> Given all this, any suggestions about how the usage statement for this option could be clearer?

Maybe “auto” reflects the default behaviours better than “none”?

> Not really a correctness concern as much as a style and consistency concern.

No, this is mainly stylistic, but might make scanning the list of arguments easier. Personally, I prefer if argument lists are also sorted, but even standard tools like grep don't do that.

**Comment by kloetzl** [comment]
Thanks for fixing this pile of small issues! 👍
