### ISSUE TITLE
integrating single and paired ends in normalize-by-median.py

### ISSUE THREAD

**Issue by bubblegirl** [dib-lab/khmer#1686]
Hi there,

I've had no luck integrating the single end reads with the paired end ones using this step. I'm running khmer 2.0. As per the documentation, pe is run first:

`normalize-by-median.py --paired -ksize 20 --cutoff 20 -n_tables 4 \
  --min-tablesize 3e8 --savetable normC20k20.ct \
  ../filtered-pairs/*.pe.qc.fq.gz`

and then se is integrated:
`normalize-by-median.py --cutoff 20 --loadtable normC20k20.ct \
  --savetable normC20k20.ct ../filtered-pairs/*.se.qc.fq.gz`

The problem with this is that `--savetable normC20k20.ct` brings up an error of unrecognised option.

I've tried the `-u` option in the diginorm script in  Lisa Cohen's MMETSP pipeline, but that was unsuccessful too. 

I've been headbutting this for a couple of days but nothing so far. Help would be much appreciated.

**Comment by ctb** [comment]
Hi @bubblegirl, sorry to hear about the problems!

--savetable should be there in khmer 2.0 and forward - what does
"normalize-by-median.py -h" report?

best,
--titus

**Comment by luizirber** [comment]
I think it should be --ksize and --n_tables, --savetable is correct

**Comment by bubblegirl** [comment]
Hi @ctb and @luizirber, 

Thanks for the lightening swift response! --ksize got rid of that error.
"normalize-by-median.py -h" reports:
usage: normalize-by-median.py [-h] [--version] [--ksize KSIZE]
                              [--n_tables N_TABLES] [-U UNIQUE_KMERS]
                              [--fp-rate FP_RATE]
                              [--max-tablesize MAX_TABLESIZE | -M MAX_MEMORY_USAGE]
                              [-q] [-C CUTOFF] [-p] [--force_single]
                              [-u unpaired_reads_filename] [-s filename]
                              [-R report_filename]
                              [--report-frequency report_frequency] [-f]
                              [-o filename] [-l filename] [--gzip | --bzip]
                              input_sequence_filename
                              [input_sequence_filename ...]

For running `normalize-by-median.py --paired -ksize 20 --cutoff 20 -n_tables 4 --min-tablesize 3e8 --savetable normC20k20.ct *.pe.fq.gz` I get the following errors:

`normalize-by-median.py: error: unrecognized arguments: -n_tables --min-tablesize 3e8 --savetable normC20k20.ct THECA_Thecadinium-kofoidii_L001.pe.fq.gz`

So somehow it's not recognising the first input file THECA_Thecadinium-kofoidii_L001.pe.fq.gz either. Though when I run `normalize-by-median.py -k 20 -M 6e9 -C 20 -p *.pe.fq.gz` it works just fine.

**Comment by ctb** [comment]
try:

--n_tables

and

--max-tablesize

:)

best,
--titus

**Comment by bubblegirl** [comment]
Thanks Titus! That made `--n_tables` and `--max-tablesize` pass. 

Though still getting the error `normalize-by-median.py: error: unrecognized arguments: --savetable`

**Comment by ctb** [comment]
You can use '-s' instead of --savetable  Not sure why that's not working, will
look into it.

**Comment by ctb** [comment]
Hi @bubblegirl I don't think you're running khmer 2.0 - my help message is much longer than yours!

I would suggest upgrading yourself to at least 2.0; `pip install -U khmer` should do that. Or, perhaps install directly from master, via

```
pip install pip install https://github.com/dib-lab/khmer/archive/master.zip
```

Where are you getting the command lines to normalize-by-median.py from?

----

And, to actually answer your question ;) -- yep! `-u` will load the single reads after all the other data has been loaded.

**Comment by bubblegirl** [comment]
Thanks, that works. By the by, --loadtable doesn't work either but -l does.

Cheers.

**Comment by ctb** [comment]
OK, finally looked at the code -- it's been `loadgraph` and `savegraph` since
2.0, I believe.

best,
--titus

**Comment by bubblegirl** [comment]
Whoa Titus, my apologies - my message did not send. Definitely running 2.0. `-s` and `-l` have worked like a charm. `-u` on the other hand did not, so I've split the process as per the tutorial.

Again, thanks for swift help!

**Comment by ctb** [comment]
welcome - and please don't hesitate to ask as we screw you up in the future :)
