### ISSUE TITLE
Reseting counts to 0 functions for Counttable and Nodetable

### ISSUE THREAD

**Issue by jiarong** [dib-lab/khmer#1691]
I have a use case that needs to have a Nodetable for each sequence file for tens of sequence files. Resetting and reuse the same Nodetable could save a lot of memory.

**Comment by standage** [comment]
Does this work?

```python
table = khmer._Counttable(table.ksize(), table.hashsizes())
```

**Comment by jiarong** [comment]
Yes, it works. Thanks :)
