### ISSUE TITLE
produce and distribute khmer via a RPM and a DEB package

### ISSUE THREAD

**Issue by mr-c** [dib-lab/khmer#170]
Should be doable via python setup.py bdist_rpm and the debian equivalent. Just needs doing, testing, and documenting.

**Comment by mr-c** [comment]
See https://github.com/ged-lab/khmer/issues/885#issuecomment-87619006

**Comment by mr-c** [comment]
Debian package was long ago released for v2.0: https://packages.debian.org/search?keywords=khmer

**Comment by heuermh** [comment]
Thanks, @mr-c!

**Comment by ctb** [comment]
I'm closing this as out of scope for our current efforts. If there are things that block others from making packages, then let's file specific issues.
