### ISSUE TITLE
Unclosed files in tests

### ISSUE THREAD

**Issue by betatim** [dib-lab/khmer#1711]
In a brand new conda env, after installing master, there are a lot of warnings like this during `make test`:
```
tests/test_tabletype.py::test_consume_seqfile[Nodegraph]
  /private/tmp/ttt/khmer/tests/test_tabletype.py:362: ResourceWarning: unclosed file <_io.BufferedReader name='/private/tmp/ttt/khmer/tests/test-data/test-fastq-reads.fq'>
    for record in screed.open(utils.get_test_data('test-fastq-reads.fq')):
```

with `platform darwin -- Python 3.6.1, pytest-3.1.0, py-1.4.33, pluggy-0.4.0`

**Comment by ctb** [comment]
yes, I hates 'em. can we disables 'em?

**Comment by betatim** [comment]
How about closing the files instead? 😁 I was hoping we could find some context manager magic that takes care of this for us.

**Comment by ctb** [comment]
On Fri, May 26, 2017 at 05:54:32AM -0700, Tim Head wrote:
> How about closing the files instead? ???? I was hoping we could find some context manager magic that takes care of this for us.

I went through this in spacegraphcats and had to add either two lines
or another nested block in about a dozen places. In a small codebase.

It's just silly. Who cares if you don't close a file in a test?  this has
caused us virtually no problems, ever, at least in my experience with khmer.

-0 on caring about this, -1 on prioritizing it, +1 for turning them
off by default.
