### ISSUE TITLE
examples/stamps/do.sh: error: unrecognized arguments: --savetable stamps-dn.ct

### ISSUE THREAD

**Issue by sjackman** [dib-lab/khmer#1725]
It looks as though `--savetable` should be either `-s` or `--savegraph`.
See https://github.com/dib-lab/khmer/blob/stable/examples/stamps/do.sh#L43
and https://github.com/dib-lab/khmer/blob/stable/examples/stamps/do.sh#L60

**Comment by standage** [comment]
Curious. I was unable to reproduce this, and none of tag `v2.1.1`, branch `maint/2.1`, or branch `master` have `--savetable` in `examples/stamps/do.sh`. Are you sure there's not a conflict with an older version of khmer installed system-wide?

**Comment by standage** [comment]
Ooops, looks like we have a `stable` tag that is, uh, not stable. :-/

This explains some weird behavior we've been seeing with our doc builds recently.

**Comment by standage** [comment]
Stable tag was removed.
