### ISSUE TITLE
A tag labeled "stable"

### ISSUE THREAD

**Issue by standage** [dib-lab/khmer#1728]
It looks like @mr-c created a tag labeled `stable` right around release 2.0. This explains why ReadTheDocs has not been auto-updating to the latest release after we set the default to `stable`. It's trying to build the `stable` tag, not the actual latest stable.

I assume this tag is not critical for anything? It's certainly not conventional to maintain a `stable` tag  long term in my experience. Am I correct in assuming this was intended to have a short shelf life and that we are free to delete the tag?

**Comment by ctb** [comment]
I think maybe it was created in my ignorance of the RTD mechanism, in fact.
And then we forgot about it! Yes, please go ahead and delete it.

**Comment by standage** [comment]
Done!
