### ISSUE TITLE
[From_CTB] ktable.get(wrong_length_string) gives core dump

### ISSUE THREAD

**Issue by RamRS** [dib-lab/khmer#174]
Transferring https://github.com/ctb/khmer/issues/14 opened on 13-Sep-2012 (0 comments)

Example using latest khmer from github under 64bit Linux,

```
$ python
Python 2.7.3 (default, Sep 13 2012, 13:18:09) 
[GCC 4.4.6 20120305 (Red Hat 4.4.6-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import khmer
>>> ktable = khmer.new_ktable(6)
>>> ktable.consume("ATGAGAGACACAGGGAGAGACCCAATTAGAGAATTGGACC")
35
>>> ktable.get("ATGAGA")
1
>>> ktable.get("GATGAG")
0
>>> ktable.get("ATAGA")
python: ktable.cc:22: khmer::HashIntoType khmer::_hash(const char*, khmer::WordLength, khmer::HashIntoType&, khmer::HashIntoType&): Assertion `strlen(kmer) >= k' failed.
Aborted (core dumped)
```

I would expect the output to be zero, or perhaps a ValueError exception about the kmer length being wrong.

**Comment by peterjc** [comment]
I originally filed this as https://github.com/ctb/khmer/issues/14 on ctb/khmer, but seems that got lost in the GitHub repository move as the new issue 14 is unrelated.

**Comment by ctb** [comment]
thx @peterjc - do we need to do anything here?
