### ISSUE TITLE
Document QFCounttable constructor

### ISSUE THREAD

**Issue by standage** [dib-lab/khmer#1748]
The new `QFCounttable` constructor (thanks @betatim *et al.*!) is different from the constructor for [Count|Node][table|graph] objects, so we can't rely on similarity to intuit the `QFCounttable`'s behavior with respect to memory. The relationship between the arguments and memory usage for the Bloom filters is clear and documented: `bytes_used = num_buckets * num_tables / buckets_per_byte`.

What can we say about the memory usage of the `QFCounttable` based on the input parameters? Can we document this somewhere?

**Comment by betatim** [comment]
We also need this information to extend the various functions that deduce size information from user input "use X GB".
