### ISSUE TITLE
Ship manylinux1 wheel

### ISSUE THREAD

**Issue by mr-c** [dib-lab/khmer#1762]
Having a wheel is becoming a requirement: 

Example: pydoc.io is only building docs for projects in PyPI with a wheel:
http://blog.readthedocs.com/moss-final-report/

**Comment by betatim** [comment]
Good point. We started discussing wheels in #1628. I'd suggest closing this and keeping the discussion there.

**Comment by mr-c** [comment]
D'oh, my search skills failed me, thanks @betatim
