### ISSUE TITLE
Should `LinearAssembler::assemble` be able to take a hash value?

### ISSUE THREAD

**Issue by ctb** [dib-lab/khmer#1765]
I just debugged an issue where the behavior of `LinearAssembler.assemble()` changed -- I had previously been using hash values to seed assemblies of linear paths, but in recent versions of khmer master, `LinearAssembler` has changed to want either `Kmer` or DNA strings - and `assemble` now fails silently/returns nothing if it's not a Kmer and cannot be converted into a meaningful DNA string (e.g. `str(hash)` fails).

I don't think failing silently is a great idea :), but I'm also wondering if there's a good reason to require either `Kmer` or DNA strings here. Hash values are usable in many other functions on graphs and get automatically converted.

If we decide to allow hash values we should make sure to add that into the tests, too.

cc @camillescott

**Comment by camillescott** [comment]
Yeah, this is bad behavior. The big new Hashgraph PR has utility functions for handling this on Hashtable; I'll switch over the assemblers to use them.
