### ISSUE TITLE
Drop Python 2

### ISSUE THREAD

**Issue by camillescott** [dib-lab/khmer#1769]
Let's drop Python 2 support. 3 is the way of the future and the path of righteousness. 2 must `yield` to the coming asynchronous storm.

Things that will need to be done:
- Modify `setup.py`
- Modify travis build spec
- Update docs
- Something in doxyfile?

Should this be done before or after merging the Hashgraph stuff?

cc @luizirber @ctb

**Comment by betatim** [comment]
How about switching to "we don't try to break python2 but we might if we have to" mode for a while before removing it? It is tedious to support both but there seem to be a surprisingly large number of people out there who are stuck with legacy python (and post issues that a project doesn't run).

**Comment by betatim** [comment]
Closing as it already got merged.
