### ISSUE TITLE
[From CTB] what would it take to accept ambiguous nucleotides?

### ISSUE THREAD

**Issue by RamRS** [dib-lab/khmer#177]
Transferring ctb#9 opened on 23-Feb-2012 (3 comments)

Perhaps this was discussed during khmer's initial design, but i would like a version of khmer (khmer-rouge?) that would parse an "injected reference" containing the bi-ambiguous nucleotides R, W, Y, M, K, and S (http://www.vivo.colostate.edu/molkit/help.html)

So TTRCC kmer 4 is (TTGCC or TTACC): TTGC,TTAC,TGCC,TACC,GGCA,GCAA,GGTA,GTAA

Since these symbols would expand the number of distinct kmers found in exponentially, i think there could be some sane limit (e.g. one) to the number of ambiguous nucleotides the program would accept within a kmer window.

How difficult would this be to implement?

**Comment by ctb** [comment]
This is easy to add on top of khmer, but is not a general need. I'm going to close this as wontfix.
