### ISSUE TITLE
Screed DeprecationWarning (Python 3.9)

### ISSUE THREAD

**Issue by jvivian-atreca** [dib-lab/khmer#1903]
Hi, thanks for the great parsing tool. 

Just wanted to give a heads up about a `DeprecationWarning`:

```
screed/screedRecord.py:12: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
```

**Comment by luizirber** [comment]
Thanks @jvivian-atreca! It should have been fixed in https://github.com/dib-lab/screed/pull/80, I'll check again what's going on

**Comment by luizirber** [comment]
OK, fixed in https://github.com/dib-lab/screed/pull/82. I'm going to release `1.0.2` with the fix.

**Comment by luizirber** [comment]
`1.0.2` (and `1.0.3`, same code but fixes the PyPI formatting...) released. Should be in bioconda soon.
