### ISSUE TITLE
script for digital normalization of shotgun mategenomic data  

### ISSUE THREAD

**Issue by mars188** [dib-lab/khmer#1907]
Hello, 

I have shotgun metagenomic data that I want to digitally normalisz. I ran the following script:

normalize-by-median.py -p -k 20 -M 2e8 --savegraph mk.kh paired.fastq

At the end of analysis, I get the following message...
 ERROR: the graph structure is too small for
** this data set.  Increase data structure size
** with --max_memory_usage/-M.
** Do not use these results!!
** (estimated false positive rate of 1.000; max recommended 0.800)

I tried changing -M but still get the similar message. 

Please help me to solve this issue so I could get the false positive less than 0.800 or ideally 0.01.

Thanks

**Comment by ctb** [comment]
On Sat, Aug 22, 2020 at 06:49:27AM -0700, mars188 wrote:
> Hello, 
> 
> I have shotgun metagenomic data that I want to digitally normalisz. I ran the following script:
> 
> normalize-by-median.py -p -k 20 -M 2e8 --savegraph mk.kh paired.fastq
> 
> At the end of analysis, I get the following message...
>  ERROR: the graph structure is too small for
> ** this data set.  Increase data structure size
> ** with --max_memory_usage/-M.
> ** Do not use these results!!
> ** (estimated false positive rate of 1.000; max recommended 0.800)
> 
> I tried changing -M but still get the similar message. 
> 
> Please help me to solve this issue so I could get the false positive less than 0.800 or ideally 0.01.

Try -M 16e9 or bigger - you'll need access to 16 GB of RAM to do that, though :)

best,
--titus
-- 
C. Titus Brown, ctbrown@ucdavis.edu

**Comment by mars188** [comment]
Thank you so much for the quick response. I ran with this increased memory and got the following message at the end:



DONE with A4_paired.fastq; kept 22171502 of 22173834 or 100.0%
output in A4_paired.fastq.keep
Total number of unique k-mers: 1517679000
...saving to mk.kh
fp rate estimated to be 0.010

fp rate is perfect..... but it's keeping all the reads and not removing much. That should be ok?

**Comment by ctb** [comment]
On Sat, Aug 22, 2020 at 08:58:27AM -0700, mars188 wrote:
> Thank you so much for the quick response. I ran with this increased memory and got the following message at the end:
> 
> 
> 
> DONE with A4_paired.fastq; kept 22171502 of 22173834 or 100.0%
> output in A4_paired.fastq.keep
> Total number of unique k-mers: 1517679000
> ...saving to mk.kh
> fp rate estimated to be 0.010
> 
> fp rate is perfect..... but it's keeping all the reads and not removing much. That should be ok?

good question! it generally means that you have a lot of diversity and
relatively low coverage.

**Comment by mars188** [comment]
Ok yeah that makes sense. 

I am going to do three rounds of normalization. Let's see when I put -C 5 (coverage 5) in the last round, if it makes any difference.

**Comment by mars188** [comment]
Ok I ran three rounds of normalization... and here is the output message:

DONE with A4_paired.fastq.keep.abundfilt; kept 4977962 of 4995661 or 99.6%
output in A4_paired.fastq.keep.abundfilt.keep
Total number of unique k-mers: 128440142
fp rate estimated to be 0.000

It is still keeping 99.6% of reads even when I chose coverage 5 in the last round. It is true that my samples are very diverse but do you recommend going further low with coverage? like -C 1?

Thank you so much for helping me navigate through this.

**Comment by ctb** [comment]
On Sat, Aug 22, 2020 at 10:28:37AM -0700, mars188 wrote:
> Ok I ran three rounds of normalization... and here is the output message:
> 
> DONE with A4_paired.fastq.keep.abundfilt; kept 4977962 of 4995661 or 99.6%
> output in A4_paired.fastq.keep.abundfilt.keep
> Total number of unique k-mers: 128440142
> fp rate estimated to be 0.000
> 
> It is still keeping 99.6% of reads even when I chose coverage 5 in the last round. It is true that my samples are very diverse but do you recommend going further low with coverage? like -C 1?
> 
> Thank you so much for helping me navigate through this. 

the problem you will run into is that below a coverage of 5, nothing will
get assembled. I suspect your sample is too low coverage :(.

**Comment by mars188** [comment]
Thanks. I just used -C 5 i.e. coverage 5 and got good (reduced) number of reads to process. I used 3 steps (passes) for digital normalization. 

Cheers!

**Comment by ctb** [comment]
I'm glad!

I'll close this for now, but please feel free to ask any more questions you might have :)
