### ISSUE TITLE
Hi Ryan,

### ISSUE THREAD

**Issue by alirezaebiii** [dib-lab/khmer#1912]
Hi Ryan,

load-graph should not take that long. partition-graph ... is a different
story.

What are you trying to do and what process have you followed thus far?

best,
--titus

_Originally posted by @ctb in https://github.com/dib-lab/khmer/issues/1352#issuecomment-214775682_

**Comment by alirezaebiii** [comment]
#1817

**Comment by ctb** [comment]
hi, did you intend to open a new issue?

**Comment by ctb** [comment]
I'll close this for now -- please feel free to reopen as you have questions!
