### ISSUE TITLE
cppcheck is not reporting the many of the warnings which falls under style option/category

### ISSUE THREAD

**Issue by nkantesh** [dib-lab/khmer#1920]
Hi All,

Below listed warnings under style category/option are not getting reported by the cppcheck. I have tried even adding the 'all' option but still below warnings are not getting reported by the cppcheck.

1)unreadVariable
2)uninitMemberVar
3)passedByValue
4)uselessAssignmentPtrArg
5)redundantInitialization
6)redundantAssignment
7)variableScope
8)redundantCondition
9)exceptRethrowCopy
10)shadowVariable
11)shadowArgument
12)shadowVariable
13)knownConditionTrueFalse

--enable=all,style,performance,portability,missingInclude  this is how I have enabled the options.

cppcheck versions I have tried with are 1.7, 1.90 & 2.9 .
cpp_std we are using is c++20.

FYI: The above mentioned warnings were getting reported by the cppcheck ran for c++17 code.

Kindly check and let me know what I have to add or what changes to be done in order to get the above warnings

**Comment by ctb** [comment]
hi, if this is relevant to khmer, please let us know - closing for now.
