### ISSUE TITLE
unify scripts

### ISSUE THREAD

**Issue by camillescott** [dib-lab/khmer#234]
The thought occurred to me earlier that we really clutter up peoples' PATH with our installing so many scripts as separate files, among other things. argparse has a pretty easy to use subcommand capability which would let us integrate everything under one executable, and separate out out flags like -k, -x, and -N which are used in basically every script. A diginorm run might look like:

    khmer -k 20 -x 1e9 -N 4 normalize-by-median -C 10 <...>

Obviously nothing urgent, just might be nice for a 1.0 release.

**Comment by ctb** [comment]
On the roadmap ('oxli'), but deferred for now. Closing.
