### ISSUE TITLE
roadmap to 1.0

### ISSUE THREAD

**Issue by mr-c** [dib-lab/khmer#321]
The big feature for the version 1.0 release is a commitment to following Semantic Versioning (  http://semver.org/ ) where the API is the command line interface exposed by the scripts.

Therefore the only must-haves for a 1.0 release is documentation of this API and any remaining changes needed to make it more consistent.

As the 1.0 release is also a time-based release the remaining bug fixes and features can be incorporated if there is enough time. Otherwise they can wait for version 1.0.1 or version 1.1. We've done a great job at 'releas[ing] early'; I'd like to improve on 'releas[ing] often.'  http://en.wikipedia.org/wiki/Release_early,_release_often

Here are the required issues to close for 1.0:

~~Document and lock down the 1.0 API #16~~
~~scan through scripts/ and remove unused/unsupported scripts #118~~
~~Add documentation on how to tie into a particular tagged version #29~~
~~Update README to point to publications & citation info #49~~
~~Provide an updated list of papers and maybe blog posts, somewhere. #162~~ 
~~add documentation for sample-reads-randomly #192~~
doc/examples.txt needs updating #201 
doc/guide.txt needs editing #202
~~doc/blog-posts.txt hardlinks to ctb's github #203~~
document what happened to old scripts #206 
~~all scripts need to output their version #236~~
Add "when you shouldn't use diginorm" to our documentation #275 
~~environmental variables need documenting #303 
git clone of the khmer repo reqs > 0.5 GiB #245 
Add Torsten's rant into our docs re command line stuff #209
http://khmer.readthedocs.org/en/latest/ tracks the master branch, not releases #230
~~C++ code should be consistently formatted #261~~
Inconsistent and incomplete output filename handling #81

~~Bonus: Write a khmer citation handle paper => arXiv #72~~

Bugs that could be fixed in 1.0 but if not then added to doc/known-issues.txt:

https://github.com/ged-lab/khmer/issues?direction=asc&labels=bug&milestone=1&page=1&sort=created&state=open

**Comment by ctb** [comment]
Remaining components of this issue should be moved to a new issue :)

**Comment by mr-c** [comment]
Remaining components moved to #1091.
