### ISSUE TITLE
load-into-counting.py raises error while fp rate is >0.20

### ISSUE THREAD

**Issue by qingpeng** [dib-lab/khmer#343]
Will it be better to downgrade the error to a warning?
Firstly fp rate as 0.2 actually is not that high for some tasks, like digital norm. 
Also, raising error may also stop pipeline or qsub job on HPCC. 

The same for normalize-by-median.py 

I know experienced user can always adjust the threshold in the script which is also commented in the script. Just my two cents.

**Comment by ctb** [comment]
--force (#399) resolves this issue.
