### ISSUE TITLE
Choosing hash table size and numbers according to number of unique k-mers

### ISSUE THREAD

**Issue by qingpeng** [dib-lab/khmer#347]
A potential feature to consider:

Use HyperLogLog Counter to get number of unique k-mer quickly before actual counting.
With number of unique k-mers and available memory to use, optimal number/size of hash tables and minimum fp rate can be estimated.
With number of unique k-mers and expected fp rate, minimum size of memory to use and optimal number/size of hash tables can be estimated. 

This can be integrated into some pipeline/script and/or elaborated in documentation.

**Comment by ctb** [comment]
This could easily be integrated into #1050, actually. Hmm.

**Comment by ctb** [comment]
Fixed in #1106 etc.
