### ISSUE TITLE
Put in place guidelines around last-minute changes in releases

### ISSUE THREAD

**Issue by ctb** [dib-lab/khmer#372]
During the 1.0 release process, we made a number of fairly significant changes within the last 24-48 hours before release.  Some of these changes were neither tied to an issue, nor a pull request, nor reviewed, nor discussed. Acceptance testing saved our bacon here, discovering a number of problems, but some of the changes were rather arbitrary and not discussed in sufficient detail.  We should think about instituting a non-release manager freeze on features and merges, as well as a 2-man rule so that even last-minute changes (which are occasionally necessary) can undergo an informal review.

@mr-c, can you write up a few short sentences on this prior to 1.1? @luizirber and @ctb to review.

**Comment by ctb** [comment]
I think this needs to be documented, but I'm happy with the approach we've taken in the last few releases (more people who merge/nominal signoff by someone else, release manager has emergency merge privileges but they should be used sparingly).

**Comment by ctb** [comment]
@mr-c to formalize in documentation.

**Comment by betatim** [comment]
https://github.com/dib-lab/khmer/pull/1645/files#diff-15fef81155f347109f21f0684a9c5593R52 how does this look?

**Comment by betatim** [comment]
Added to release checklist in #1645
