### ISSUE TITLE
Add implementation of optimal hash size calculation to khmer.khmer_args

### ISSUE THREAD

**Issue by ctb** [dib-lab/khmer#390]
@qingpeng, can you take a first stab at adding a function into khmer to calculate the optimal H and Z parameters for a CountMin Sketch at a given fp rate for a given N?  Don't worry about argparse inclusion or anything -- just a function with some unit tests.

**Comment by proteasome** [comment]
@mr-c i'm interested in working on this

**Comment by ctb** [comment]
Added in #1106.

**Comment by ctb** [comment]
Fixed by #1126.
