### ISSUE TITLE
Deal with k-mers containing non-ACTG sensibly

### ISSUE THREAD

**Issue by ctb** [dib-lab/khmer#394]
In particular, what do we do with 'N's?  (See Aaron Liston e-mail to khmer@lists.idyll.org list, 30 Jan 2014).  This is a systemic flaw in khmer currently and needs to be addressed at a fairly fundamental level, perhaps in the hash function (which could simply be extended to deal with arbitrary ch, or ACTGactgNn, or...), but it needs to be thought through in terms of implications.  Yech.

Definitely a 3.0 kinda issue.

See also #370.

**Comment by ctb** [comment]
Conversation continued (with more specificity) in #1036. Closing this 'un; we're not handling IUPAC anytime soon :)

**Comment by mr-c** [comment]
Should we have a separate list of requested but ignored features?

**Comment by mr-c** [comment]
Or there could be a label we could apply 'not-planned'

**Comment by ctb** [comment]
Surely the search function can be used for this?

**Comment by mr-c** [comment]
Right, it would be https://github.com/dib-lab/khmer/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+label%3A%22not+planned%22+

**Comment by ctb** [comment]
-0
