### ISSUE TITLE
All scripts should output the sequence format they take in (FASTA/FASTA, FASTQ/FASTQ) by default

### ISSUE THREAD

**Issue by ctb** [dib-lab/khmer#46]
Several scripts don't (didn't) do this.  Fixing one by one.

**Comment by camillescott** [comment]
Note: the record object returned by readparser is slightly different than that returned by screed, in that it has the 'accuracy' attribute but keeps it empty for fasta, while screed simply omits the 'accuracy' attribute for fasta record objects. Related: #328

**Comment by mr-c** [comment]
One approach would be to override `__getattr__` either in a Python wrapper of the CPython implementation of the ReadParser reads or by providing a custom `tp_getattr` on the CPython side: https://docs.python.org/2.7/extending/newtypes.html#type-specific-attribute-management

**Comment by ctb** [comment]
See #769

**Comment by ctb** [comment]
All scripts/code now handles this properly; in particular, annotate_partitions is tested in `test_scripts.py:test_extract_partitions_fq()`. Closing.
