### ISSUE TITLE
normalize-by-median.py -o <filename> will always append new result to existing output file

### ISSUE THREAD

**Issue by qingpeng** [dib-lab/khmer#462]
This feature may be useful in certain circumstance(while loading saved hashtable for incrementing data more efficiently), but may be confusing. For example, kill a process and restart it, there will be problem if forgetting to remove old output file.

potential solution:
1. For every run, for single input file, always open an empty output file. for multiple input files, open an empty output file before processing the first input file, then appending result to that output file for other input files.

or,

2. leave this as it is but make documentation more clear about this.

**Comment by ctb** [comment]
The specific behavior in this issue can be dealt with by doing `-o - >> old_output_file`. Closing.
