### ISSUE TITLE
Upgrade screed development workflow.

### ISSUE THREAD

**Issue by ctb** [dib-lab/khmer#470]
Via @mr-c:

1) Jenkins autobuild/test
2) Jenkins PR builder
3) Documented release process
4) Release made & pushed

**Comment by ctb** [comment]
ping @bocajnotnef - where are we?

**Comment by bocajnotnef** [comment]
I think we're set here unless anyone has any new pain points on the subject. The lack of additional comments would indicate otherwise, so I'm closing this.

**Comment by ctb** [comment]
great thx
