### ISSUE TITLE
Allow k > 32 in khmer

### ISSUE THREAD

**Issue by ctb** [dib-lab/khmer#60]
There have been a number of requests to enable k > 32 in khmer code.  This should be relatively straightforward (@fishjord has a cyclic hash implementation in Java that he sent around) but has not so far been a priority.  This is an issue so that we can track such requests in the future and keep it somewhere on the list.

Note, we need to figure out how to deal with _revhash issues; there are a few places in the code where exact hashes are kept and converted from numbers back into strings.  Not a blocker, just a detail issue.

**Comment by mr-c** [comment]
See also https://twitter.com/beconstant/status/555750390323765248

**Comment by alexjironkin** [comment]
+1

**Comment by ctb** [comment]
Also see: https://twitter.com/ChristianHeimes/status/593007790861475840

**Comment by ctb** [comment]
Now enabled by #1511 and friends.
