### ISSUE TITLE
Bring screed up to date

### ISSUE THREAD

**Issue by ctb** [dib-lab/khmer#625]
- [x] change 'accuracy' to 'quality'
- [ ] cut new release
- [x] examine code coverage for obvious stuff
- [x] add ChangeLog

@mr-c anything else?

**Comment by ctb** [comment]
Hey @bocajnotnef are these checkboxes up to date?

**Comment by bocajnotnef** [comment]
They are now. Are we closing this?

**Comment by ctb** [comment]
What remains to be done on this from your perspective, @bocajnotnef?  I'll go through it @mr-c today, too.

**Comment by bocajnotnef** [comment]
AFAIK it should be good--I just noticed there were a few other issues
referencing this one that're still open.

**Comment by ctb** [comment]
...and? :)

**Comment by bocajnotnef** [comment]
Ah,
