### ISSUE TITLE
max kmer for single pass diginorm

### ISSUE THREAD

**Issue by macmanes** [dib-lab/khmer#636]
I'm trying to do a classroom experiment using smaller and larger values for k.It looks like kmer=31 is the largest possible size, but why is this so? Also, the error message for kmer sizes > 31 could be more clear. 

`normalize-by-median.py -p -x 15e8 -k 33 -C 50 --out khmer_normalized.fq interleaved.fq`

    || This is the script 'normalize-by-median.py' in khmer.
    || You are running khmer version 1.2-rc2-6-gc5dee21
    || You are also using screed version 0.7
    ||
    || If you use this script in a publication, please cite EACH of the following:
    ||
    ||   * MR Crusoe et al., 2014. doi: 10.6084/m9.figshare.979190
    ||   * CT Brown et al., arXiv:1203.4802 [q-bio.GN]
    ||
    || Please see http://khmer.readthedocs.org/en/latest/citations.html for details.
    PARAMETERS:
     - kmer size =    33 		(-k)
     - n tables =     4 		(-N)
     - min tablesize = 1.5e+09 	(-x)
    Estimated memory usage is 6e+09 bytes (n_tables x min_tablesize)
    --------
    making k-mer counting table
    terminate called after throwing an instance of 'khmer::khmer_exception'
      what():  Supplied kmer string doesn't match the underlying k-size.
    Aborted (core dumped)

**Comment by ctb** [comment]
ksize upgrade in #624; core issue is #60. Punted error message fix to #1094.
