### ISSUE TITLE
dealing with super-short reads

### ISSUE THREAD

**Issue by qingpeng** [dib-lab/khmer#640]
I came across this error when I tried to do error correction.

[qingpeng@dev-intel07 Error_Correction]$ /opt/software/Python/2.7.2--GCC-4.4.5/bin/python /mnt/home/qingpeng/Github/khmer/sandbox/correct-errors.py --ksize 20 --n_hashes 4 --hashsize 1e8 V1.UC-14.trimmed.fa.gz
making hashtable
created temporary directory ./tmpRveAd2khmer; use -T to change location
... 0 V1.UC-14.trimmed.fa.gz 0 0 0 1
terminate called after throwing an instance of 'khmer::khmer_exception'
  what():  Supplied kmer string doesn't match the underlying k-size.
Aborted (core dumped)

After further review, I think this may be due to short read in the file. (read length < k)

I used fastq_quality_filter to do the filtering, but it will return many short reads. (even with the length of <10). There is no option to discard these short reads in fastq_quality_filter.)

But I am wondering if this is the best way for khmer to deal with this kind of issue.

Will it be better to just skip those super short reads? (with some warnings maybe)

**Comment by ctb** [comment]
Fixed in #663.
