### ISSUE TITLE
Read object is not fully exposed to python

### ISSUE THREAD

**Issue by camillescott** [dib-lab/khmer#645]
`_khmermodule.cc` defines most of the machinery for a Read type (a simple struct declared in `read_parsers.hh`), but does not define a `__new__` method and doesn't fully expose it to python. This would be convenient for some applications.

**Comment by mr-c** [comment]
See #728 for a detailed checklist.

**Comment by ctb** [comment]
Fixed; see #728 and linked issues.

**Comment by mr-c** [comment]
Using ipython I'm not see how to make a new ReadParser read from Python...

**Comment by ctb** [comment]
Please go ahead and file a new issue, then, with more specifics about what's needed. More important IMO is #769.

**Comment by mr-c** [comment]
We should make exposing the read object part of #769 then as that is all
the same code area.

On Sat, Jun 13, 2015 at 11:47 AM C. Titus Brown <notifications@github.com>
wrote:

> Please go ahead and file a new issue, then, with more specifics about
> what's needed. More important IMO is #769
> <https://github.com/dib-lab/khmer/issues/769>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dib-lab/khmer/issues/645#issuecomment-111739555>.
>
-- 
Michael R. Crusoe: Programmer & Bioinformatician crusoe@ucdavis.edu
<mcrusoe@msu.edu>
The lab for Data Intensive Biology; University of California, Davis
https://impactstory.org/MichaelRCrusoe http://twitter.com/biocrusoe

**Comment by ctb** [comment]
I would like to see a specific use case, so -0 on just including it to round things out. So far we have no need to create a Read object in Python that I can see, and until we no longer depend on screed we have access to screed.Record().
