### ISSUE TITLE
_khmermodule.cc cleanup

### ISSUE THREAD

**Issue by mr-c** [dib-lab/khmer#728]
- [x] `tp_name` field of PyTypeObjects needs to include module name; dot separated; Example: `khmer.Read`
- [ ] rename all Python facing mentions of 'hash' to 'table' (and update Python code)
- [x] remove `_common_init_Type` and refactor accordingly
- [x] PyTypeObjects should be name `khmer_${TYPENAME}_Type`; 
- [x] all PyTypeObjects should be implemented as new style Python classes
- [x] Type methods should use their type Object in the method signature instead of `PyObject`. Cast the methods to `PyCFunction`s in the `PyMethodDef`.
- [x] Type deallocators should use their type Object in the method signature instead of `PyObject`. Cast the method in `tp_dealloc` to `(destructor)`

Types to review
- [x] `Read_Type`
- [x] `ReadParser_Type`
- [x] `ReadPairIterator_Type`
- [x] `khmer_KSubsetPartitionType`
- [x] `khmer_KCountingHashType`
- [x] `khmer_KHashbitsType`
- [x] `khmer_KLabelHashType`
- [x] `khmer_ReadAlignerType`

**Comment by luizirber** [comment]
Working on it: #785

**Comment by ctb** [comment]
More or less done (#785, #1044) and the naming scheme stuff is punted to #872.
