### ISSUE TITLE
doc test coverage concept / diff-cover / updating test thresholds

### ISSUE THREAD

**Issue by mr-c** [dib-lab/khmer#739]

**Comment by mr-c** [comment]
See https://github.com/ged-lab/khmer/pull/736#issuecomment-71243112

**Comment by standage** [comment]
Cryptic title and no description makes it difficult for me to know what to do with this one. Any comments @mr-c?

**Comment by mr-c** [comment]
Hey @standage 

During my time on the project we had to occasionally tweak the threshold for code coverage success due to shortcomings in how we measured it.

The process for updating that threshold was not documented, hence this issue.

The example I linked to above https://github.com/dib-lab/khmer/pull/736#issuecomment-71243112 shows the interaction that prompted this issue.

**Comment by betatim** [comment]
Does this mean we can close this?

With the travis and codecov setup coverage is still calculated but it is up to the humans to decide 👍  or 👎 .

**Comment by standage** [comment]
Thanks for the clarification @mr-c!

Yes, @betatim, I think we can close this.
