### ISSUE TITLE
Allow slicing of screed records

### ISSUE THREAD

**Issue by ctb** [dib-lab/khmer#768]
This pattern occurs several times in the khmer code base:

    new_read.name = read.name
    new_read.sequence = read.sequence[:trim_at]
    if hasattr(read, 'accuracy'):
        accuracy = read.accuracy
        new_read.accuracy = read.accuracy[:trim_at]

and should really just be new_read = read[:trim_at]...

This could be done at the same time as #705, too.

**Comment by bocajnotnef** [comment]
Starting work on this

**Comment by bocajnotnef** [comment]
I'm only seeing this in scripts/trim-low-abund. Are there others?

**Comment by bocajnotnef** [comment]
(Also, starting work on this)

**Comment by ctb** [comment]
On Fri, Feb 27, 2015 at 08:44:46AM -0800, bocajnotnef wrote:
> I'm only seeing this in scripts/trim-low-abund. Are there others?

filter-abund and filter-abund-single, too.  And maybe more down the road :)

**Comment by bocajnotnef** [comment]
Alright. Is there an obvious place I should look to fix this? Otherwise I'm just gonna try to do it and see what breaks.

**Comment by ctb** [comment]
On Fri, Feb 27, 2015 at 08:47:43AM -0800, bocajnotnef wrote:
> Alright. Is there an obvious place I should look to fix this? Otherwise I'm just gonna try to do it and see what breaks.

Let's talk briefly at noon.

**Comment by bocajnotnef** [comment]
- [ ] see _screed_recorcd_dict (rename to RecordDict and make public?)
 - [ ] rewrite getitem to handle slice objects

**Comment by wrightmhw** [comment]
@bocajnotnef are you still working on this? Thinking of picking it up.

**Comment by camillescott** [comment]
Relevant docs: https://docs.python.org/2/reference/datamodel.html#object.__getitem__; http://www.pythoncentral.io/how-to-slice-custom-objects-classes-in-python/

**Comment by bocajnotnef** [comment]
@wrightmhw Hadn't started--Go for it.

**Comment by bocajnotnef** [comment]
Closing--resolved by https://github.com/dib-lab/screed/issues/29
