### ISSUE TITLE
Synchronize screed and khmer read record details

### ISSUE THREAD

**Issue by ctb** [dib-lab/khmer#769]
khmer.ReadParser returns read objects that differ from screed-created read objects in silly ways; this should be fixed.

**Comment by ctb** [comment]
One question - is it OK for a legitimate read to have an _empty_ quality attribute?

**Comment by mr-c** [comment]
Note: ReadParser reads still refer to 'accuracy'

**Comment by ctb** [comment]
See also #645

**Comment by ctb** [comment]
Needs to be verified.

**Comment by mr-c** [comment]
ReadParser reads do correctly refer to 'quality' instead of 'accuracy'

Reads from FASTA files still have an 'accuracy' attribute (an empty UTF string).

```
In [6]: o = khmer.ReadParser('tests/test-data/paired.fa')

In [7]: n = o.next()

In [8]: n.
n.annotations  n.name         n.quality      n.sequence  

In [9]: n.quality
Out[9]: u''
```

**Comment by betatim** [comment]
Has the opinion on exposing the `Read` object "fully" changed since #645? Motivation for doing so would be to make it easy to test that `screed.Record` and `khmer.Read` look and feel the same.

**Comment by ctb** [comment]
On Mon, Oct 24, 2016 at 07:02:46AM -0700, Tim Head wrote:
> Has the opinion on exposing the `Read` object "fully" changed since #645? Motivation for doing so would be to make it easy to test that `screed.Record` and `khmer.Read` look and feel the same.

Yes, I think it's a good idea for that reason.
