### ISSUE TITLE
documentation of .hist output file

### ISSUE THREAD

**Issue by drtamermansour** [dib-lab/khmer#786]
The .hist output file of abundance-dist.py needs to be documented. I think the four columns of the file refer to  "k-mer counts", "Frequency", "cumulative frequency" , and "cumulative fraction"

**Comment by ctb** [comment]
On Thu, Feb 19, 2015 at 01:38:52PM -0800, Tamer Mansour wrote:
> The .hist output file of abundance-dist.py needs to be documented. I think the four columns of the file refer to  "k-mer counts", "Frequency", "cumulative frequency" , and "cumulative fraction"

Ideally (for 2.0) column headers would be added to the actual output file.  For
now, we can make this an option on output (but as it changes the output format,
it cannot be the default for a 1.x release).

**Comment by drtamermansour** [comment]
For now, we can simply print the description of the headers to the sys.stderr

**Comment by ctb** [comment]
On Thu, Feb 19, 2015 at 01:51:57PM -0800, Tamer Mansour wrote:
> For now, we can simply print the description of the headers to the sys.stderr

Sorry, should have said - many data loading libraries can take advantage
of the headers on the columns when loading data, so it's useful to have
the option of putting it in the output file.  (Plus it gets us ready for
2.0)

The column format should also be described in doc/scripts.txt.

**Comment by ctb** [comment]
Closed by #789.
