### ISSUE TITLE
document magic CI phrases

### ISSUE THREAD

**Issue by mr-c** [dib-lab/khmer#806]
`.*add\W+to\W+testlist.*|.*[Jj]enkins,?\Wadd+to\W+testlist.*`
`.*ok\W+to\W+test.*|.*[Jj]enkins,?\Wok\W+to\W+test.*`
`.*test\W+this\W+please.*|.*[Jj]enkins,?\W+test\W+this\W+please.*`

**Comment by ctb** [comment]
With #1464 no longer needed, yah?

**Comment by ctb** [comment]
(i.e. the move to travis has obviated)

**Comment by standage** [comment]
Travis ignores commits containing `[skip ci]` or `[ci skip]` in the commit message. Useful if 1) you know something is broken or 2) updating a README or something.
