### ISSUE TITLE
Change screed.open() so that parse_description defaults to False.

### ISSUE THREAD

**Issue by ctb** [dib-lab/khmer#820]
Should we? Or maybe we should remove parse_description and .description?

(To be fair to the original developers of screed, we started writing it back when Solexa reads came in FASTA and it seemed like a good idea at the time. But maybe we can just get rid of .description altogether...)

**Comment by ctb** [comment]
I'm leaning towards removing both parse_description and .description from screed.  '.description' is not used anywhere in khmer, and description parsing should be left up to the consumer of the FASTA header.

for screed 0.8, we could remove description, and then remove parse_description for screed 1.0.

thoughts?

**Comment by mr-c** [comment]
I want screed v0.8 out ASAP. I'm fine with removing them both.

**Comment by ctb** [comment]
I think: remove screed.description now, and set parse_description=False by default; then we'll edit khmer appropriately later.

**Comment by ctb** [comment]
- [ ] Is it mergable?
- [ ] Did it pass the tests?
- [ ] If it introduces new functionality, is it tested?
- [ ] Is it well formatted? Look at `make pep8`, `make diff_pylint_report`,
  and `make doc` output. Use `make format` and manual fixing as needed.
- [ ] Is it documented in the ChangeLog?
- [ ] Was a spellchecker run on the source code and documentation after
  changes were made?

@bocajnotnef @luizirber is there a place

**Comment by ctb** [comment]
Closed by https://github.com/dib-lab/screed/pull/43

**Comment by mr-c** [comment]
screed.description needs to be removed still, see https://github.com/dib-lab/screed/pull/43#issuecomment-110318857

**Comment by ctb** [comment]
- [ ] remove screed.description from screed
- [ ] remove 'parse_description=False' from throughout the code base.

Removal of parse_description=False can be done as part of 2.0 easily enough...

**Comment by ctb** [comment]
Fixing for khmer in #1180.

**Comment by mr-c** [comment]
Done.
