### ISSUE TITLE
split test_scripts.py, test_extract_long_sequences() into two functions

### ISSUE THREAD

**Issue by ctb** [dib-lab/khmer#825]
These should be two separate functions, one testing .fq and one testing .fa.

(This should probably wait until #818 is merged, because 4294fbb fixes two bugs in this function...)

**Comment by mr-c** [comment]
FYI, #818 is merged

**Comment by samanehsan** [comment]
I can take this issue!

**Comment by samanehsan** [comment]
Ahh didn't notice @jessicamizzi was already assigned to this. I'll close my PR.

**Comment by bocajnotnef** [comment]
Closing #825, fixed by #901
