### ISSUE TITLE
Vague error message when loading a counting table fails

### ISSUE THREAD

**Issue by SherineAwad** [dib-lab/khmer#841]
If a counting table filename is not passed correctly, the error message is very ambiguous.

**Comment by ctb** [comment]
On Tue, Feb 24, 2015 at 12:43:19PM -0800, Sherine wrote:
> If a counting table filename is not passed correctly, the error message is very ambiguous. 

Hi Sherine,

could you provide quick example code/output showing the problem?
2-3 line script would be a great help for others.

**Comment by SherineAwad** [comment]
CountingHash * counting;
counting->load(filename); 
If filename is something like test.fq or incorrect, it raise IO Error exception without any other details.

**Comment by mr-c** [comment]
@SherineAwad Is this still an issue?

**Comment by SherineAwad** [comment]
@mr-c No
