### ISSUE TITLE
khmer should be graceful with respect to errors while processing multiple files

### ISSUE THREAD

**Issue by camillescott** [dib-lab/khmer#87]
If we are processing multiple files and an error occurs then we should show that to the user and move on to the next file.

There should be a flag to disable this behavior, in which case we should tell the user there was an error in a specific file and quit gracefully.

"It's now handled for normalize-by-median -- but what about the other scripts? Not sure what load-graph and load-into-counting should do. filter-abund should be tolerant. abundance-dist... should probably fail. Systematic examination needed."

**Comment by ctb** [comment]
I've decided this is, in general, a horrible idea. See https://github.com/dib-lab/khmer/pull/1057#issuecomment-108999754 for full rationale.
