### ISSUE TITLE
Rename counting_hash and hashbits at Python layer

### ISSUE THREAD

**Issue by ctb** [dib-lab/khmer#872]
I suggest counting_table and/or bytegraph instead of counting_hash, and bitgraph instead of hashbits. (@mr-c has already renamed stopped using 'hash' in our scripts and docs).

counting_table could default to bigcounts=yes, bytegraph could default to bigcounts=no, but otherwise be the same structure.

Reason: I found it silly to be using counting_hash in my VanBUG talk when I was talking about graphs.

**Comment by mr-c** [comment]
How about `countgraph` & `graph`?

**Comment by ctb** [comment]
On Sat, Mar 14, 2015 at 07:38:02PM -0700, Michael R. Crusoe wrote:
> How about `countgraph` & `graph`?

Imprecise - wouldn't "graph" be a superset of "countgraph"?  What about
"nodegraph"?

We haven't really been using the 1-bit graph implementation lately, but we may
well in the future, as well as expanding to additional kinds of graphs - exact
graphs of various flavors, and different sized bins.  So maybe we can think
about that, too.

**Comment by mr-c** [comment]
+1 for nodegraph + countgraph

**Comment by ctb** [comment]
On Sat, Mar 14, 2015 at 07:43:39PM -0700, Michael R. Crusoe wrote:
> +1 for nodegraph + countgraph

Excellent.

**Comment by camillescott** [comment]
+1 node/countgraph as well

**Comment by anotherthomas** [comment]
I am working on this issue.
