### ISSUE TITLE
Behaviour of SeqAnParser with a truncated fastq

### ISSUE THREAD

**Issue by kdmurray91** [dib-lab/khmer#884]
This is a bit of a strange question, but here goes.

While making a test for #877, I made the following FASTQ file:

```
@1:1:1:1:1 1:N:0:NNNNN
CAGGCGCCCA
+
][aaX__aa[
@1:1:1:1:2 1:N:0:NNNNN
CAGGCGCCCA
```

I.e., a valid record, followed by a record truncated after the sequence.

From my understanding of the format, and certainly from a pragmatic point, this is an invalid file. But the seqan parser silently accepts it, leaving `read.quality := ""`.

And there's no indication of an invalid record (i.e., `seqan::readRecord` returns 0, no exceptions are thrown).

I'm fairly certain that it's me who is wrong and this is some corner case of the format, but it smells strange to me somehow.

Cheers,
Kevin

**Comment by kdmurray91** [comment]
Further testing indicates the same happens with

```
@1:1:1:1:1 1:N:0:NNNNN
CAGGCGCCCA
+
][aaX__aa[
@1:1:1:1:2 1:N:0:NNNNN
```

which *has* to be invalid, surely :)

**Comment by kdmurray91** [comment]
And even this:

```
@1:1:1:1:1 1:N:0:NNNNN
CAGGCGCCCA
+
][aaX__aa[
@
```

**Comment by kdmurray91** [comment]
So I gather this is a bug @ctb? If so, would you like me to dig further and/or contact seqan?

**Comment by mr-c** [comment]
Further digging is welcome! Looks like a bug with SeqAn 1.4.x. It'll be interesting to see if it also exists in 2.x.

**Comment by mr-c** [comment]
@ctb Shall we add a check for FASTQ files that have missing quality records and throw our own exception?

- [ ] Add to known issues list

**Comment by ctb** [comment]
On Mon, Mar 30, 2015 at 03:03:41AM -0700, Michael R. Crusoe wrote:
> @ctb Shall we add a check for FASTQ files that have missing quality records and throw our own exception?
> 
> - [ ] Add to known issues list

Sure.

**Comment by kdmurray91** [comment]
OK, I'm happy to a) investiage w/ SeqAn 2, and b), raise a khmer exception when the quality is "" if it's a fastq file.

**Comment by mr-c** [comment]
Thanks!

**Comment by kdmurray91** [comment]
OK, so w/ seqan 2, using the following works, throwing `seqan::UnexpectedEnd`. Which sounds about right!

```c++
#include <seqan/seq_io.h>

using namespace seqan;

int main(int argc, char **argv)
{
    std::string id, seq, qual;

    if (argc < 2) {
        return 1;
    }

    SeqFileIn seqFileIn(argv[1]);

    while (1) {
        readRecord(id, seq, qual, seqFileIn);
        std::cout << id << '\t' << seq << '\t' << qual << '\n';
    }

    return 0;
}
```

**Comment by mr-c** [comment]
Huzzah. We should still file an issue with Seqan to document the problem for 1.4.x users.

**Comment by kdmurray91** [comment]
OK, I'll double check the issue with a vanilla 1.4.2 tarball first, and raise an issue on their github. Tomorrow though, tis late down under :)

**Comment by mr-c** [comment]
Thanks @kdmurray91, I appreciate it

**Comment by kdmurray91** [comment]
Interestingly, seqan 1.4 does something different:

```c++
#include <seqan/seq_io.h>

int main(int argc, char **argv)
{
    std::string id, seq, qual;

    if (argc < 2) {
        return 1;
    }

    seqan::SequenceStream seqFileIn;
    seqan::open(seqFileIn, argv[1]);
    size_t seqs = 0;

    while (!seqan::atEnd(seqFileIn)) {
        seqan::readRecord(id, seq, qual, seqFileIn);
        std::cout << seqs++ << ' ' <<  id << '\t' << seq << '\t' << qual << '\n';
    }

    return 0;
}
```

Output:
```bash
~/src/khmer$ ./seqan14 tests/test-data/truncated.fq 
0 1:1:1:1:1 1:N:0:NNNNN	CAGGCGCCCA	][aaX__aa[
1 		
```

So, it makes a new record, but doesn't fill ANY fields.

I can confirm that the same happens with the khmer headers under `./third-party`.

So a "fix" would be to check the length of the id/seq/qual strings and raise an error if it's empty? Or should we just silently skip it?

**Comment by kdmurray91** [comment]
Gist links for future reference:

[seqan 1.4](https://gist.github.com/361142983a5bc66f55ec)
[seqan 2.0](https://gist.github.com/7ceaa01464bd8c7517cb)

**Comment by mr-c** [comment]
Intriguing. What version of Seqan were you initially testing with, 1.4.2?

On the first record only: set flag based on presence of qual string. If that flag is set then the length of seq and qual string must be equal; throw an appropriate khmer exception if not.

**Comment by kdmurray91** [comment]
Ah, it was `khmer::SeqAnParser`. I'll investigate further and make sure that my reported output was accurate. It could have been a bug in my debugging code (yo dog, i hear you like debugging...).

I'll get back to you tomorrow.

**Comment by kdmurray91** [comment]
So, with: https://gist.github.com/7f8b2178764483fbd294 (which uses khmer::read_parsers::SeqAnParser), I get the same as with vanilla seqan 1.4, i.e. a blank record at the end. I'll implement your suggestion above @mr-c

**Comment by mr-c** [comment]
Thank you for the follow up.

**Comment by kdmurray91** [comment]
@mr-c what should we do with the case of an empty sequence?

**Comment by kdmurray91** [comment]
The original bug is fixed by #897, maybe @mr-c can re-open if you want this to linger as motivation for the SeqAn2  PR/bug

**Comment by kdmurray91** [comment]
Though, a "known issue" we didn't discuss is that the following will be interpreted as a sequence only file, which it, a) kinda is, and b) well, this is never going to happen.

```
@seq
ACGCTAGCTA
```

**Comment by kdmurray91** [comment]
I checked, and the following is correctly found to be erroneous:

```
@seq1
ACGT
@seq2
ACGT
+
IIII
```

So it's only for single reads.

**Comment by mr-c** [comment]
I don't see our job to be a correctness checker all the time but I guess that can go in the known issues list.

**Comment by kdmurray91** [comment]
:+1:

**Comment by mr-c** [comment]
- [ ] add to known issues list and close

**Comment by mr-c** [comment]
documented in #1222
