### ISSUE TITLE
investigate using makeflow for pipelines

### ISSUE THREAD

**Issue by mr-c** [dib-lab/khmer#89]
http://www3.nd.edu/~ccl/software/makeflow/

(not actually a khmer issue, but we lack a good place to track meta- and general lab issues)

HPCC instruction: https://wiki.hpcc.msu.edu/display/~colbrydi@msu.edu/2011/11/11/On+Demand+MakeFlow+PBS+script

**Comment by ctb** [comment]
The world has gotten more complicated and we've largely settled on pydoit or snakemake for now. Plus, Common Workflow Language now exists. Closing b/c there are no plans to do anything specific with khmer for makeflow.
