### ISSUE TITLE
update documentation: use codespell instead of aspell

### ISSUE THREAD

**Issue by mr-c** [dib-lab/khmer#890]
in `doc/dev/coding-guidelines-and-review.txt`

**Comment by datasourcery** [comment]
I'm working this.

**Comment by luizirber** [comment]
A very hacky way to do it over only what changed on the branch `my-branch`, compared to `master`.

``` bash
$ git clone git@github.com:lucasdemarchi/codespell.git ~/bin/codespell
$ export PATH=$PATH:~/bin/codespell
$ git diff master..my-branch > diff_file
$ codespell.py diff_file
```
I tried some process substitution, but it failed, part of the file was missing. If it worked, 3rd and 4th lines could be just one:
` $ codespell.py <(git diff master..my-branch)`

I think we should run this as part of the Jenkins khmer-pullrequest job.

**Comment by bocajnotnef** [comment]
@datasourcery Status on this?

**Comment by mr-c** [comment]
@bocajnotnef have at it!

**Comment by bocajnotnef** [comment]
Closing #890
