### ISSUE TITLE
C++ library discussion

### ISSUE THREAD

**Issue by kdmurray91** [dib-lab/khmer#893]
Just continuing on from #776, which is getting a bit `C++`-y for a Python API thread :)

@mr-c  said:

> Re: C++ library. Now that #788 is merged I am happy to accept PRs that add Doxygen comments
> and/or move code out of the header files.

**Comment by kdmurray91** [comment]
I'll have a go at Doxygen-ing the bits I know about, as time permits.

**Comment by mr-c** [comment]
Thanks!
