### ISSUE TITLE
Officially stop supporting Python 2.6

### ISSUE THREAD

**Issue by mr-c** [dib-lab/khmer#904]
And include a pointer to http://www.curiousefficiency.org/posts/2015/04/stop-supporting-python26.html

hat tip to @luizirber

**Comment by mr-c** [comment]
See also #94

**Comment by ctb** [comment]
On Sat, Apr 04, 2015 at 07:07:32AM -0700, Michael R. Crusoe wrote:
> And include a pointer to http://www.curiousefficiency.org/posts/2015/04/stop-supporting-python26.html
> 
> hat tip to @luizirber 

We don't have many dependencies, though, so I'm not sure we're contributing to
the 2.6 problem.  More articulation on the technical reasons (what do we gain
by abandoning Py 2.6?) would be welcome.

**Comment by mr-c** [comment]
I think I remember some difficulties that py2.6 compatibility introduces if
one wants to have a Python 2/3 compatible codebase. I feel no need to
change anything at the moment; the C++ side is much more significant if one
buys the logic at the link.

**Comment by mr-c** [comment]
Done in #1180
