### ISSUE TITLE
Need to document policy for incomplete pull requests

### ISSUE THREAD

**Issue by mr-c** [dib-lab/khmer#939]
- [ ] Ask before taking over
- [ ] What is an appropriate time to wait before swooping in?

**Comment by standage** [comment]
Any comments on this? cc @ctb @luizirber @camillescott @betatim

**Comment by betatim** [comment]
LGTM. I usually wait for 3 working days or so after asking if it would be Ok to take over the PR.

Should this go in the docs or just something for us guys to talk about and agree?

**Comment by standage** [comment]
Definitely document in the dev docs.
