### ISSUE TITLE
[Screed][Docs] install & running test instructions out of date

### ISSUE THREAD

**Issue by mr-c** [dib-lab/khmer#970]
- [x] should install using `pip  install`, not `git clone`
- [x] run tests using nosetest
- [x] missing setup instructions for devs

**Comment by proteasome** [comment]
@mr-c directory structure has changed and should be updated for Creating a database from the API and ? elsewhere, e.g. 
screed/tests/test.fa  -> screed/tests/test-data/test.fa
http://screed.readthedocs.org/en/latest/screed.html

**Comment by mr-c** [comment]
@proteasome  Yep! Good catch

**Comment by proteasome** [comment]
@mr-c thx.   enjoyed contributing at PyCon sprint, hope to do more.    just recently (~week ago) received email about being listed as a contributor.   somehow misplaced it.  could you resend?  thx -en

**Comment by mr-c** [comment]
@proteasome You are very welcome!

**Comment by mr-c** [comment]
https://github.com/dib-lab/screed/pull/45 addresses points #1 & #2

**Comment by standage** [comment]
Closed with https://github.com/dib-lab/screed/pull/62.
