### ISSUE TITLE
Update trim-low-abund output statement

### ISSUE THREAD

**Issue by ctb** [dib-lab/khmer#973]
The statement "output in *.abundtrim'" at the end may no longer be true with the new '-o' option; this should be updated.

**Comment by bocajnotnef** [comment]
Will assess post #747

**Comment by ctb** [comment]
On Fri, Jul 24, 2015 at 05:51:22PM -0700, Jake Fenton wrote:
> Will assess post #747 

It's tied to https://github.com/dib-lab/2014-streaming/, so I'd like to
take it.

**Comment by bocajnotnef** [comment]
Alright.

**Comment by standage** [comment]
@ctb, do you still want to claim this one? Should we slate for 2.1?
