### ISSUE TITLE
clean up khmer.calc_expected_collisions() output in khmer/__init__.py

### ISSUE THREAD

**Issue by ctb** [dib-lab/khmer#980]
- [x] every line should start with **
- [x] the false positive rate should be printed out
- [x] the max false positive rate should be printed out
- [x] 'presence table' isn't always correct, eg. load-into-counting; remove 'presence'

**Comment by mr-c** [comment]
@ctb Is this a blocker for v1.4?

**Comment by ctb** [comment]
On Tue, Apr 28, 2015 at 10:07:15AM -0700, Michael R. Crusoe wrote:
> @ctb Is this a blocker for v1.4?

nope.

**Comment by ctb** [comment]
Confirm fix for 2.0; close.

**Comment by ctb** [comment]
Confirmed!
