### ISSUE TITLE
Properly handle singleton reads in normalize-by-median.

### ISSUE THREAD

**Issue by ctb** [dib-lab/khmer#988]
This fits into the #732 bucket, improving user experience.

These ideas and issues most recently raised in conversation with @drtamermansour, but leaning on conversations with @camillescott and @mr-c also.

singleton reads/read files are poorly handled by normalize-by-median in workflows and elsewhere. A few thoughts --

1. By default, normalize-by-median should accept and deal with broken-paired properly (pairs dealt with as pairs, singletons dealt with as singletons).

2. -p should require correct pairing, and we will need a new option to force into singleton mode (all sequences treated as singletons) - looking at sample-reads-randomly/#933, --force-single seems fine.

3. We should provide a new option that, with '-p' forcing pairs, allows a singleton file (or files) to be passed in and treated w/o requiring pairing.  Something like --singletons.

**Comment by ctb** [comment]
Note that option number 3 was already implemented in #957 by @susinmotion! Excellent :)

**Comment by bocajnotnef** [comment]
re 2: What does 'correctly paired' mean in this context?

**Comment by ctb** [comment]
Operationally speaking, the broken_paired_reader will return two records if the records are properly paired.  See existing -p logic.

**Comment by bocajnotnef** [comment]
If -p already does correct pairing is that component of 2 done, and we just need force-singletons?

**Comment by ctb** [comment]
yes, assuming you have integrated in broken_paired_reader.

**Comment by drtamermansour** [comment]
This discussion about correct pairing is confusing to me. Please correct me if I am getting this wrong. I think option number 1 means that the script would accept the input data file (without any arguments). The script would expect that the input has mixed proper paired and singletons (e.g. The output of fastq_quality_filter). This mean that the user does not need to extract paired ends from the interleaved files anymore.  Option  2 means the -p will expect a correctly paired end file and will fail with file containing mix of PE and single tones. The --force-single will forcibly utilize the input as single reads.

**Comment by ctb** [comment]
Yep, exactly!

**Comment by ctb** [comment]
Done in #1057 and #1010.
