### ISSUE TITLE
Support pytest as test runner

### ISSUE THREAD

**Issue by luizirber** [dib-lab/khmer#991]
Actually tests basically work, the only issue is with the attr marker from nose. Branch [feature/pytest][1] implements a [meta decorator][2] (yes, really) because nose and pytest implementations of test tagging are similar, but different enough to be incompatible.

Trying to import pytest first is a bit weird, but I didn't find any way to check which test runner is active. This still works with nose even if pytest is present, so we don't break how it worked previously.

[1]: https://github.com/ged-lab/khmer/compare/feature/pytest
[2]: https://github.com/ged-lab/khmer/compare/feature/pytest#diff-356b0cce172f19b23235de06daf67197R19

**Comment by ctb** [comment]
On Fri, May 08, 2015 at 01:52:21PM -0700, Luiz Irber wrote:
> Actually tests basically work, the only issue is with the attr marker from nose. Branch [feature/pytest][1] implements a [meta decorator][2] (yes, really) because nose and pytest implementations of test tagging are similar, but different enough to be incompatible.
> 
> Trying to import pytest first is a bit weird, but I didn't find any way to check which test runner is active. This still works with nose even if pytest is present, so we don't break how it worked previously.
> 
> [1]: https://github.com/ged-lab/khmer/compare/feature/pytest
> [2]: https://github.com/ged-lab/khmer/compare/feature/pytest#diff-356b0cce172f19b23235de06daf67197R19

Hi Luiz,

could you please outline the reasons why we should support py.test? Curious.

thanks!

**Comment by luizirber** [comment]
It started some motnhs ago because nose had problems with generating test reports for Jenkins when it was executed in more than one process. py.test worked but it wasn't that much faster.

My personal reasons are more mundane: I like the py.test default output, specially when a test fails and it shows the content of the variables in the assertion. I also have the impression py.test development is more active and it has nicer plugins, but I don't have any evidence for any of these statements.

**Comment by mr-c** [comment]
@luizirber Is it a prerequisite for Hypothesis? https://github.com/ged-lab/khmer/issues/990#issuecomment-100365383

**Comment by ctb** [comment]
ok.  Was expecting you to talk about 'tox' TBH :).

I don't have strong feelings against py.test but am -0 on adding to
maintenance headaches.  Just something to keep in mind.

**Comment by luizirber** [comment]
@mr-c nope, hypothesis is test runner agnostic.

@ctb well, there is another PR for tox. I just dumped some branches and opened issues in case someone want to try/explore/suggest another approaches. I'm already using py.test and tox and it might be useful for other people, but if I was advocating inclusion on the codebase I would open a PR, instead of just creating issues =]

**Comment by ctb** [comment]
Please go ahead and open a PR; nose is no longer being developed, and I guess we must move with the times :) :(
